/*
   viernes, 29 de marzo de 20240:23:11
   User: 
   Server: DESKTOP-04O1C92\SQL2019
   Database: SifizPlanning
   Application: 
*/

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
GO

-- Creación de la tabla TICKET.RECURSOSASISTENCIA
CREATE TABLE TICKET.RECURSOSASISTENCIA
	(
	SECUENCIAL int NOT NULL IDENTITY (1, 1),
	SECUENCIALRECURSO int NOT NULL,
	SECUENCIALCOLABORADOR int NOT NULL,
	ASISTENCIA numeric(1, 0) NOT NULL,
	PUNTUACION float(53) NOT NULL,
	ESTAACTIVO numeric(1, 0) NOT NULL
	) ON [PRIMARY]
GO

-- Configuración de la tabla TICKET.RECURSOSASISTENCIA
ALTER TABLE dbo.RECURSOSASISTENCIA SET (LOCK_ESCALATION = TABLE)
GO

-- Configuración de la tabla TICKET.RECURSOS
ALTER TABLE TICKET.RECURSOS SET (LOCK_ESCALATION = TABLE)
GO

-- Configuración de la tabla TAREAS.COLABORADOR
ALTER TABLE TAREAS.COLABORADOR SET (LOCK_ESCALATION = TABLE)
GO

-- Creación de las restricciones para TICKET.RECURSOSASISTENCIA
ALTER TABLE TICKET.RECURSOSASISTENCIA ADD CONSTRAINT
	PK_RECURSOSASISTENCIA PRIMARY KEY CLUSTERED 
	(
	SECUENCIAL
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE TICKET.RECURSOSASISTENCIA ADD CONSTRAINT
	FK_RECURSOSASISTENCIA_COLABORADOR FOREIGN KEY
	(
	SECUENCIALCOLABORADOR
	) REFERENCES TAREAS.COLABORADOR
	(
	SECUENCIAL
	) ON UPDATE NO ACTION 
	 ON DELETE NO ACTION 
GO

ALTER TABLE TICKET.RECURSOSASISTENCIA ADD CONSTRAINT
	FK_RECURSOSASISTENCIA_RECURSOS FOREIGN KEY
	(
	SECUENCIALRECURSO
	) REFERENCES TICKET.RECURSOS
	(
	SECUENCIAL
	) ON UPDATE NO ACTION 
	 ON DELETE NO ACTION 
GO

-- Configuración final de la tabla TICKET.RECURSOSASISTENCIA
ALTER TABLE TICKET.RECURSOSASISTENCIA SET (LOCK_ESCALATION = TABLE)
GO

COMMIT

-- Verificación de permisos
select Has_Perms_By_Name(N'TICKET.RECURSOSASISTENCIA', 'Object', 'ALTER') as ALT_Per, 
       Has_Perms_By_Name(N'TICKET.RECURSOSASISTENCIA', 'Object', 'VIEW DEFINITION') as View_def_Per, 
       Has_Perms_By_Name(N'TICKET.RECURSOSASISTENCIA', 'Object', 'CONTROL') as Contr_Per
GO