/*
   Saturday, March 9, 20247:50:47 PM
   User: 
   Server: DESKTOP-5N18OUN\SQL2019
   Database: SifizPlanning
   Application: 
*/

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE TICKET.ETAPASPROYECTOCLIENTE
	(
	SECUENCIAL int NOT NULL IDENTITY (1, 1),
	SECUENCIALETAPAPROYECTO int NOT NULL,
	FECHAINICIO date NOT NULL,
	FECHAFIN date NOT NULL,
	ESTAACTIVO numeric(1, 0) NOT NULL,
	) ON [PRIMARY]
GO
ALTER TABLE TICKET.ETAPASPROYECTOCLIENTE ADD CONSTRAINT
	PK_ETAPASPROYECTOCLIENTE PRIMARY KEY CLUSTERED 
	(
	SECUENCIAL
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE TICKET.ETAPASPROYECTOCLIENTE ADD CONSTRAINT
	FK_ETAPASPROYECTOCLIENTE_ETAPASPROYECTO1 FOREIGN KEY
	(
	SECUENCIALETAPAPROYECTO
	) REFERENCES TICKET.ETAPASPROYECTO
	(
	SECUENCIAL
	) ON UPDATE NO ACTION 
	 ON DELETE NO ACTION 
GO
ALTER TABLE TICKET.ETAPASPROYECTOCLIENTE SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
select Has_Perms_By_Name(N'TICKET.ETAPASPROYECTOCLIENTE', 'Object', 'ALTER') as ALT_Per, Has_Perms_By_Name(N'TICKET.ETAPASPROYECTOCLIENTE', 'Object', 'VIEW DEFINITION') as View_def_Per, Has_Perms_By_Name(N'TICKET.ETAPASPROYECTOCLIENTE', 'Object', 'CONTROL') as Contr_Per