/*
   Saturday, March 9, 20248:42:20 PM
   User: 
   Server: DESKTOP-5N18OUN\SQL2019
   Database: SifizPlanning
   Application: 
*/

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE TICKET.SUBETAPASPROYECTOSCLIENTE
	(
	SECUENCIAL int NOT NULL IDENTITY (1, 1),
	SECUENCIALRECURSOSSUBETAPASPROYECTO int NOT NULL,
	SECUENCIALETAPASPROYECTOCLIENTE int NOT NULL,
	DESCRIPCION varchar(250) NOT NULL,
	ESTAACTIVO numeric(1, 0) NOT NULL,
	FECHACOMIENZO date NOT NULL,
	FECHAFIN date NOT NULL
	) ON [PRIMARY]
GO
ALTER TABLE TICKET.SUBETAPASPROYECTOSCLIENTE ADD CONSTRAINT
	PK_SUBETAPASPROYECTOSCLIENTE PRIMARY KEY CLUSTERED 
	(
	SECUENCIAL
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE TICKET.SUBETAPASPROYECTOSCLIENTE ADD CONSTRAINT
	FK_SUBETAPASPROYECTOSCLIENTE_RECURSOSSUBETAPASPROYECTO FOREIGN KEY
	(
	SECUENCIALRECURSOSSUBETAPASPROYECTO
	) REFERENCES TICKET.RECURSOSSUBETAPASPROYECTO
	(
	SECUENCIAL
	) ON UPDATE NO ACTION 
	 ON DELETE NO ACTION 
GO
ALTER TABLE TICKET.SUBETAPASPROYECTOSCLIENTE ADD CONSTRAINT
	FK_SUBETAPASPROYECTOSCLIENTE_ETAPASPROYECTOCLIENTE FOREIGN KEY
	(
	SECUENCIALETAPASPROYECTOCLIENTE
	) REFERENCES TICKET.ETAPASPROYECTOCLIENTE
	(
	SECUENCIAL
	) ON UPDATE NO ACTION 
	 ON DELETE NO ACTION 
GO
ALTER TABLE TICKET.SUBETAPASPROYECTOSCLIENTE SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
select Has_Perms_By_Name(N'TICKET.SUBETAPASPROYECTOSCLIENTE', 'Object', 'ALTER') as ALT_Per, Has_Perms_By_Name(N'TICKET.SUBETAPASPROYECTOSCLIENTE', 'Object', 'VIEW DEFINITION') as View_def_Per, Has_Perms_By_Name(N'TICKET.SUBETAPASPROYECTOSCLIENTE', 'Object', 'CONTROL') as Contr_Per