comercialApp.controller('listadoVersionesController', ['$scope', '$timeout', '$q', function($scope, $timeout, $q) {
    // Inicializar los modelos
    $scope.filtro = '';
    $scope.filtroInfra = '';
    $scope.paginado = {
        pagina: 1,
        tam: 10,
        total: 0,
        totalPaginas: 1,
        paginas: [],
        datos: []
    };

    // Mock de datos
    $scope.versiones = [
        {
            cooperativa: '11 DE JUNIO',
            codigo: '11JUN',
            contacto: 'Piedad Cabezas',
            correo: 'pcabezas@oncedejunio.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Cristian Moreno',
            gestorServicio: 'Luisa Moreno',
            correoGestor: 'lmoreno@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\11J',
            infraestructura: 'nube'
        },
        {
            cooperativa: '4 DE OCTUBRE',
            codigo: '04OCT',
            contacto: 'Alexis Mata',
            correo: 'alexis.mata@4deoctubre.net',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Cristian Moreno',
            gestorServicio: 'Luisa Moreno',
            correoGestor: 'lmoreno@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\4Octubre',
            infraestructura: 'onpremise'
        },
        {
            cooperativa: '9 DE OCTUBRE',
            codigo: '09OCT',
            contacto: 'Tannia Toapaxi',
            correo: 'tannia.toapaxi@9octubre.fin.ec',
            version: '2.0',
            visualStudio: 'VS2017',
            repositorio: 'TFS',
            admCodigo: 'Cooperativa',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Bolivar Vallejo',
            gestorServicio: 'Jaqueline Reino',
            correoGestor: 'jreino@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'ACCIÓN IMBABURAPAK',
            codigo: 'AIMBA',
            contacto: 'Mario Guerra',
            correo: 'mguerra@accionimbaburapak.com.ec',
            version: '2.0',
            visualStudio: '',
            repositorio: 'TFS',
            admCodigo: '',
            integracion: '',
            publicacion: '',
            solucionProxies: '',
            liderProyecto: 'Operaciones',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'ANTORCHA',
            codigo: 'ANTOR',
            contacto: 'Eduardo Vergara',
            correo: 'sistemas@antorcha.fin.ec',
            version: '2.0',
            visualStudio: 'VS2015',
            repositorio: 'TFS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Sifizsoft S.A.',
            publicacion: 'Sifizsoft S.A.',
            solucionProxies: 'SI',
            liderProyecto: 'Bolivar Vallejo',
            gestorServicio: 'Gissela Torres',
            correoGestor: 'asistentecomiteoperaciones@sifizsoft.com',
            path: 'D:\\TFS2023\\VS2015\\ANTOR',
            infraestructura: ''
        },
        {
            cooperativa: 'ASPIRE',
            codigo: 'ASPIRE',
            contacto: 'Pablo Rodriguez',
            correo: 'prodriguez@coopaspire.com.do',
            version: '2.5',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: '',
            publicacion: '',
            solucionProxies: 'NO',
            liderProyecto: 'Cristian Moreno',
            gestorServicio: 'Katherin Freire',
            correoGestor: 'kfreire@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'BASE DE TAURA',
            codigo: 'BTAURA',
            contacto: 'Santiago León',
            correo: 'aux_informatica@cooptaura.fin.ec',
            version: '2.0',
            visualStudio: 'VS2019',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'NO',
            liderProyecto: 'Fernando Chamorro',
            gestorServicio: 'Luisa Moreno',
            correoGestor: 'lmoreno@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2019\\TAURA',
            infraestructura: ''
        },
        {
            cooperativa: 'CACPE BIBLIAN',
            codigo: 'CACPEB',
            contacto: 'Carlos Julio Barreto',
            correo: 'cjbarreto@cbcooperativa.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Danilo Guaña',
            gestorServicio: 'Esteban Cárdenas',
            correoGestor: 'ecardenas@sifizsoft.com',
            path: 'D:\\TFS2023\\VS2022\\CACPEB',
            infraestructura: ''
        },
        {
            cooperativa: 'CACPE PASTAZA',
            codigo: 'CACPEP',
            contacto: 'Pablo Santos',
            correo: 'psantos@cacpepas.fin.ec',
            version: '2.0',
            visualStudio: '',
            repositorio: 'TFS',
            admCodigo: 'Cooperativa',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: '',
            liderProyecto: 'Danilo Guaña',
            gestorServicio: 'Jaqueline Reino',
            correoGestor: 'jreino@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'CACPE YANTZAZA',
            codigo: 'CACPEY',
            contacto: 'Yabel Peralta',
            correo: 'yabelperalta@cacpey.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'TFS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Fernando Chamorro',
            gestorServicio: 'Jaqueline Reino',
            correoGestor: 'jreino@sifizsoft.com',
            path: 'D:\\TFS2023\\VS2022\\CACPEY',
            infraestructura: ''
        },
        {
            cooperativa: 'CACPE ZAMORA',
            codigo: 'CACPEZ',
            contacto: 'Carlos Cevallos',
            correo: 'clcevallos@cacpezamora.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'TFS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Jorge Romero',
            gestorServicio: 'Elizabeth Diaz',
            correoGestor: 'asistenteoperaciones@sifizsoft.com',
            path: 'D:\\TFS2023\\VS2013\\ZAMORA',
            infraestructura: ''
        },
        {
            cooperativa: 'CACPECO FBS 2.5',
            codigo: 'CACPEC',
            contacto: 'Fausto Cerda',
            correo: 'fcerda@cacpeco.com',
            version: '2.5',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'Cooperativa',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'NO',
            liderProyecto: 'Fernando Chamorro',
            gestorServicio: 'Katherin Freire',
            correoGestor: 'kfreire@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'CACSPMEC',
            codigo: 'CACSPMEC',
            contacto: 'Danilo Baño',
            correo: 'danilo@cacspmec.fin.ec',
            version: '2.0',
            visualStudio: '',
            repositorio: 'TFS',
            admCodigo: 'SifizSoft S. A.',
            integracion: '',
            publicacion: '',
            solucionProxies: '',
            liderProyecto: 'Diego Balseca',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'CATAR',
            codigo: 'CATAR',
            contacto: 'Alexandra Valdiviezo',
            correo: 'procesodeliquicion@coopcatar.fin.ec',
            version: '2.0',
            visualStudio: 'VS2017',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Victor Hidalgo',
            gestorServicio: 'Nataly Yanez',
            correoGestor: 'nyanez@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2017\\CATAR',
            infraestructura: ''
        },
        {
            cooperativa: 'CHIBULEO',
            codigo: 'CHIBU',
            contacto: 'Darwin Uñog',
            correo: 'darwinccbl@chibuleo.com',
            version: '2.0',
            visualStudio: 'VS2019',
            repositorio: 'TFS2019',
            admCodigo: 'Cooperativa',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Cristian Moreno',
            gestorServicio: 'Katherin Freire',
            correoGestor: 'kfreire@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'ALFONSO JARAMILLO',
            codigo: 'CAJA',
            contacto: 'Milton Castro',
            correo: 'mcastro@caja.com.ec',
            version: '2.0',
            visualStudio: '',
            repositorio: '',
            admCodigo: '',
            integracion: '',
            publicacion: '',
            solucionProxies: '',
            liderProyecto: 'N/A',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'CHONE',
            codigo: 'CHONE',
            contacto: 'Danny Alcivar',
            correo: 'danny.alcivar@coopchone.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Cristian Moreno',
            gestorServicio: 'Jaqueline Reino',
            correoGestor: 'jreino@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\CHONE',
            infraestructura: ''
        },
        {
            cooperativa: 'COCA',
            codigo: 'COCA',
            contacto: 'Jairo Pérez',
            correo: 'tecnologia@cocaltda.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Fernando Chamorro',
            gestorServicio: 'Gissela Torres',
            correoGestor: 'asistentecomiteoperaciones@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\COCA',
            infraestructura: ''
        },
        {
            cooperativa: 'COOPARTAMOS',
            codigo: 'COOPAR',
            contacto: 'Dennys Aguire',
            correo: 'daguirre@coopartamos.fin.ec',
            version: '2.0',
            visualStudio: 'VS2015',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'NO',
            liderProyecto: 'Bolivar Vallejo',
            gestorServicio: 'Rossy Landave',
            correoGestor: 'rlandave@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2015\\COOPARTAMOS',
            infraestructura: ''
        },
        {
            cooperativa: 'CORPORACIÓN CENTRO',
            codigo: 'CCENT',
            contacto: 'Juan Carlos Freire',
            correo: 'juan.freire@coopcentro.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Santiago Quishpe',
            gestorServicio: 'Jaqueline Reino',
            correoGestor: 'jreino@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\CCENT',
            infraestructura: ''
        },
        {
            cooperativa: 'CREDIAMBATO',
            codigo: 'CREDIA',
            contacto: 'Stephany Vela',
            correo: 'svela@crediambato.com.ec',
            version: '2.0',
            visualStudio: 'VS2015',
            repositorio: 'DEVOPS',
            admCodigo: '',
            integracion: '',
            publicacion: '',
            solucionProxies: '',
            liderProyecto: 'Jorge Romero',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'EDUCADORES DE CHIMBORAZO',
            codigo: 'CACECH',
            contacto: 'Eduardo Aldas',
            correo: 'aldas.eduardo@coaceducadoreschimborazo.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'NO',
            liderProyecto: 'Fernando Chamorro',
            gestorServicio: 'Nataly Yanez',
            correoGestor: 'nyanez@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\CACECH',
            infraestructura: ''
        },
        {
            cooperativa: 'EDUCADORES DE TUNGURAHUA',
            codigo: 'CACET',
            contacto: 'Fabian Bayas',
            correo: 'fabianbayas@coacet.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Fernando Chamorro',
            gestorServicio: 'Elizabeth Diaz',
            correoGestor: 'asistenteoperaciones@sifizsoft.com',
            path: 'D:\\TFS2023\\VS2013\\CACET',
            infraestructura: ''
        },
        {
            cooperativa: 'FAMA',
            codigo: 'FAMA',
            contacto: 'Franklyn Rodríguez',
            correo: 'franklyn.rodriguez@famaopdf.org.hn',
            version: '2.0',
            visualStudio: 'VS2017',
            repositorio: 'TFS',
            admCodigo: 'Cooperativa',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Santiago Quishpe',
            gestorServicio: 'Gabriela Cárdenas',
            correoGestor: 'gcardenas@intecsoft.com.ec',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'FIRESA',
            codigo: 'FIRESA',
            contacto: 'Rafael Vargas',
            correo: 'rvargas@firesa.fin.ec',
            version: '2.0',
            visualStudio: '',
            repositorio: 'DEVOPS',
            admCodigo: '',
            integracion: '',
            publicacion: '',
            solucionProxies: '',
            liderProyecto: 'N/A',
            gestorServicio: 'Bolivar Vallejo',
            correoGestor: 'bvallejo@sifizsoft.com',
            path: 'D:\\TFS2023\\VS2013\\FIRESA',
            infraestructura: ''
        },
        {
            cooperativa: 'FLORESTA',
            codigo: 'FLORE',
            contacto: 'Bryan Amaguaña',
            correo: 'bamaguana@coopfloresta.fin.ec',
            version: '2.0',
            visualStudio: 'VS2010',
            repositorio: 'TFS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'N/A',
            gestorServicio: 'Gissela Torres',
            correoGestor: 'asistentecomiteoperaciones@sifizsoft.com',
            path: 'D:\\TFS2023\\VS2010\\FLORE',
            infraestructura: ''
        },
        {
            cooperativa: 'FORTUNA',
            codigo: 'FORTU',
            contacto: 'Lizzette Betancourt',
            correo: 'lbetancourt@coopfortuna.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Cristian Moreno',
            gestorServicio: 'Gissela Torres',
            correoGestor: 'asistentecomiteoperaciones@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\FORTUNA',
            infraestructura: ''
        },
        {
            cooperativa: 'FUNDACIÓN CASA CAMPESINA CAYAMBE',
            codigo: 'FCCCA',
            contacto: 'Ana María Aroyo',
            correo: 'aarroyo@salesianoscayambe.edu.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Operaciones',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'FUNED',
            codigo: 'FUNED',
            contacto: 'Omar Fiallos',
            correo: 'omar_fiallos@visionfund.org',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Santiago Quishpe',
            gestorServicio: 'Gissela Torres',
            correoGestor: 'asistentecomiteoperaciones@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\FUNED',
            infraestructura: ''
        },
        {
            cooperativa: 'FUTURO LAMANENSE',
            codigo: 'FLAMA',
            contacto: 'Anita Rivera',
            correo: 'anitalu_rc@hotmail.com',
            version: '2.0',
            visualStudio: '',
            repositorio: 'TFS',
            admCodigo: '',
            integracion: '',
            publicacion: '',
            solucionProxies: '',
            liderProyecto: 'N/A',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'GUARANDA',
            codigo: 'GUARA',
            contacto: 'Hernan Zarate',
            correo: 'administrador@guarandaltda.fin.ec',
            version: '2.0',
            visualStudio: 'VS2015',
            repositorio: 'TFS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'NO',
            liderProyecto: 'Fernando Chamorro',
            gestorServicio: 'Gabriela Cárdenas',
            correoGestor: 'gcardenas@intecsoft.com.ec',
            path: 'D:\\TFS2023\\VS2015\\GUARA',
            infraestructura: ''
        },
        {
            cooperativa: 'INSOTEC',
            codigo: 'INSOTEC',
            contacto: 'Marco Cando',
            correo: 'mcando@insotec-ec.com',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'TFS',
            admCodigo: 'Cooperativa',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'N/A',
            gestorServicio: 'Esteban Cárdenas',
            correoGestor: 'ecardenas@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'JUVENTUD UNIDA',
            codigo: 'JUNID',
            contacto: 'Pintag Llanganate',
            correo: 'moritopintag@gmail.com',
            version: '2.5',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: '',
            liderProyecto: 'Fabricio Guaña',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'KISAPINCHA',
            codigo: 'KISAP',
            contacto: 'Vicente Vásquez',
            correo: 'tecnologia@kisapincha.com',
            version: '2.0',
            visualStudio: 'VS2019',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Bolivar Vallejo',
            gestorServicio: 'Bolivar Vallejo',
            correoGestor: 'bvallejo@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2019\\KISAPINCHA',
            infraestructura: ''
        },
        {
            cooperativa: 'LA BENÉFICA',
            codigo: 'LBENE',
            contacto: 'Simon Alcivar',
            correo: 'salcivar@labenefica.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Operaciones',
            gestorServicio: 'Rossy Landave',
            correoGestor: 'rlandave@sifizsoft.com',
            path: 'D:\\TFS2023\\VS2022\\LABENE',
            infraestructura: ''
        },
        {
            cooperativa: 'LA MANÁ',
            codigo: 'LMANA',
            contacto: 'Oscar Reyes',
            correo: 'oreyes@coaclamana.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'NO',
            liderProyecto: 'Victor Hidalgo',
            gestorServicio: 'Nataly Yanez',
            correoGestor: 'nyanez@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\LAMANÁ',
            infraestructura: ''
        },
        {
            cooperativa: 'LOS ANDES',
            codigo: 'LANDES',
            contacto: 'Edwin Montalvo',
            correo: 'emontalvo@cooperativalosandes.com',
            version: '2.5',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: '',
            integracion: '',
            publicacion: '',
            solucionProxies: '',
            liderProyecto: 'Fernando Chamorro',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'LOS ANDES LATINOS',
            codigo: 'LALAT',
            contacto: 'Angel Recalde',
            correo: 'sistemas@cooplosandeslatinos.com',
            version: '2.0',
            visualStudio: 'VS2015',
            repositorio: 'TFS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Operaciones',
            gestorServicio: 'Nataly Yanez',
            correoGestor: 'nyanez@sifizsoft.com',
            path: 'D:\\TFS2023\\VS2015\\LALAT',
            infraestructura: ''
        },
        {
            cooperativa: 'LUCHA CAMPESINA',
            codigo: 'LCAMP',
            contacto: 'Carlos Velez',
            correo: 'carlos.velez@luchacampesina.fin.ec',
            version: '2.0',
            visualStudio: '',
            repositorio: 'TFS',
            admCodigo: 'Cooperativa',
            integracion: '',
            publicacion: '',
            solucionProxies: '',
            liderProyecto: 'Jorge Romero',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'MAQUITA CUSHUN',
            codigo: 'MCUSH',
            contacto: 'Luis Vivanco',
            correo: 'luis.vivanco@maquitacushun.fin.ec',
            version: '2.0',
            visualStudio: 'VS2015',
            repositorio: 'TFS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Jorge Romero',
            gestorServicio: 'Rossy Landave',
            correoGestor: 'rlandave@sifizsoft.com',
            path: 'D:\\TFS2023\\VS2015\\MAQUITA',
            infraestructura: ''
        },
        {
            cooperativa: 'MARCABELI',
            codigo: 'MARCA',
            contacto: 'Lino Tandazo',
            correo: 'tecnologia@coacmarcabeli.fin.ec',
            version: '2.0',
            visualStudio: 'VS2019',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Operaciones',
            gestorServicio: 'Nataly Yanez',
            correoGestor: 'nyanez@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2019\\MARCABELI',
            infraestructura: ''
        },
        {
            cooperativa: 'LA MERCED DE CUENCA',
            codigo: 'LMCUE',
            contacto: 'Juan Diego Velez',
            correo: 'jvelez@coaclamerced.fin.ec',
            version: '2.0',
            visualStudio: '',
            repositorio: '',
            admCodigo: '',
            integracion: '',
            publicacion: '',
            solucionProxies: '',
            liderProyecto: 'N/A',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'MICROEMPRESARIAL SUCRE',
            codigo: 'COACMES',
            contacto: 'Wellington Morales',
            correo: 'sistemas@coacmes.com',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Danilo Guaña',
            gestorServicio: 'Gabriela Cárdenas',
            correoGestor: 'gcardenas@intecsoft.com.ec',
            path: 'D:\\DEVOPS\\VS2022\\COACMES',
            infraestructura: ''
        },
        {
            cooperativa: 'MUTUALISTA AMBATO',
            codigo: 'MUAMB',
            contacto: 'Diego Cadena',
            correo: 'diego.cadena@mutualistaambato.fin.ec',
            version: '2.0',
            visualStudio: '',
            repositorio: 'TFS',
            admCodigo: '',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'Si',
            liderProyecto: 'N/A',
            gestorServicio: 'Katherin Freire',
            correoGestor: 'kfreire@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'NEGOCIOS ANDINOS',
            codigo: 'NANDI',
            contacto: 'Wilson Hidalgo',
            correo: 'wilsonwh2@hotmail.com',
            version: '',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'Sifizsoft S. A.',
            integracion: '',
            publicacion: '',
            solucionProxies: '',
            liderProyecto: 'Bolivar Vallejo',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'PABLO MUÑOZ VEGA',
            codigo: 'CPMV',
            contacto: 'Anibal Hernandez',
            correo: 'anibalhernandez@cpmv.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'Cooperativa',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'NO',
            liderProyecto: 'Danilo Guaña',
            gestorServicio: 'Jaqueline Reino',
            correoGestor: 'jreino@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'PASTORAL SOCIAL CARITAS LATACUNGA',
            codigo: 'UPSCL',
            contacto: 'Adriana Casa',
            correo: 'adriana.casa@caritaslatacunga.org',
            version: '2.0',
            visualStudio: 'VS2019',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'NO',
            liderProyecto: 'Victor Hidalgo',
            gestorServicio: 'Nataly Yanez',
            correoGestor: 'nyanez@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2019\\CARITASLATACUNGA',
            infraestructura: ''
        },
        {
            cooperativa: 'PEDRO MONCAYO',
            codigo: 'PMONC',
            contacto: 'Alexandra Guerrero',
            correo: 'aguerrero@copedromoncayo.fin.ec',
            version: '2.5',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'NO',
            liderProyecto: 'Carlos Abril',
            gestorServicio: 'Luisa Moreno',
            correoGestor: 'lmoreno@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'PILARH',
            codigo: 'PILARH',
            contacto: 'Rolin Peña',
            correo: 'rolinp@pilarh-opdf.org',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Santiago Quishpe',
            gestorServicio: 'Bolivar Vallejo',
            correoGestor: 'bvallejo@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\PILARH',
            infraestructura: ''
        },
        {
            cooperativa: 'PISA',
            codigo: 'PISA',
            contacto: 'Juan Vasco',
            correo: 'jfvasco@plasticaucho.com',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Operaciones',
            gestorServicio: 'Rossy Landave',
            correoGestor: 'rlandave@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'PUSHAK RUNA',
            codigo: 'PRUNA',
            contacto: 'David Marge',
            correo: 'david.marge@pushakruna.com',
            version: '2.0',
            visualStudio: '',
            repositorio: 'TFS',
            admCodigo: 'Cooperativa',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: '',
            liderProyecto: 'N/A',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: 'D:\\TFS2023\\VS2013\\PRUNA',
            infraestructura: ''
        },
        {
            cooperativa: 'RHUMY WARA',
            codigo: 'RWARA',
            contacto: 'Fernando Cisneros',
            correo: 'depsistemasrhumywara@hotmail.com',
            version: '2.0',
            visualStudio: '',
            repositorio: 'TFS',
            admCodigo: '',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: '',
            liderProyecto: 'N/A',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'RIOBAMBA',
            codigo: 'RIOBA',
            contacto: 'Geovanny Baños',
            correo: 'produccion@cooprio.fin.ec',
            version: '2.5',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'Sifizsoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: '',
            liderProyecto: 'Danilo Guaña',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'SAGRARIO',
            codigo: 'SAGRA',
            contacto: 'Jaime Freire',
            correo: 'jfreire@elsagrario.fin.ec',
            version: '2.0',
            visualStudio: '',
            repositorio: 'TFS',
            admCodigo: '',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: '',
            liderProyecto: 'N/A',
            gestorServicio: 'Katherin Freire',
            correoGestor: 'kfreire@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'SALINAS',
            codigo: 'SALIN',
            contacto: 'Henry Quishpe',
            correo: 'hquishpe@coopsalinas.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Fernando Chamorro',
            gestorServicio: 'Gabriela Cárdenas',
            correoGestor: 'gcardenas@intecsoft.com.ec',
            path: 'D:\\DEVOPS\\VS2022\\SALINAS',
            infraestructura: ''
        },
        {
            cooperativa: 'SAN ANTONIO DE IBARRA',
            codigo: 'SANTOI',
            contacto: 'Roberto Villareal',
            correo: 'rvillarreal@coopsanantonio.com',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Cristian Moreno',
            gestorServicio: 'Gissela Torres',
            correoGestor: 'asistentecomiteoperaciones@sifizsoft.com',
            path: 'D:\\TFS2023\\VS2022\\SANTOI',
            infraestructura: ''
        },
        {
            cooperativa: 'SAN ANTONIO (LOS RÍOS)',
            codigo: 'SANTO',
            contacto: 'Luz Cordova',
            correo: 'luz.cordova@coopsanantonio.fin.ec',
            version: '2.0',
            visualStudio: '',
            repositorio: '',
            admCodigo: 'Cooperativa',
            integracion: 'Cooperativa',
            publicacion: '',
            solucionProxies: '',
            liderProyecto: 'N/A',
            gestorServicio: 'N/A',
            correoGestor: '',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'SAN FRANCISCO DE AMBATO',
            codigo: 'SFRAN',
            contacto: 'Diego Torres',
            correo: 'diego.torres@coac-sanfra.com',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'Cooperativa',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: '',
            liderProyecto: 'Operaciones',
            gestorServicio: 'Esteban Cárdenas',
            correoGestor: 'ecardenas@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'SAN FRANCISCO DE ASIS',
            codigo: 'SFASIS',
            contacto: 'Sergio Guallichico',
            correo: 'sguallichico@asis.fin.ec',
            version: '2.0',
            visualStudio: 'VS2019',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Operaciones',
            gestorServicio: 'Bolivar Vallejo',
            correoGestor: 'bvallejo@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'SAN ISIDRO',
            codigo: 'SISID',
            contacto: 'Cecibel Vera',
            correo: 'cecyv11@hotmail.com',
            version: '2.0',
            visualStudio: 'VS2015',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'Si',
            liderProyecto: 'Operaciones',
            gestorServicio: 'Bolivar Vallejo',
            correoGestor: 'bvallejo@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2015\\SANISIDRO',
            infraestructura: ''
        },
        {
            cooperativa: 'SAN JOSÉ (CHIMBO)',
            codigo: 'SJOSE',
            contacto: 'Nadia Gutierrez',
            correo: 'ngutierrez@coopsanjose.fin.ec',
            version: '2.5',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'NO',
            liderProyecto: 'Danilo Guaña',
            gestorServicio: 'Jaqueline Reino',
            correoGestor: 'jreino@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'SANTA ANITA',
            codigo: 'SANIT',
            contacto: 'Fredyy Cauja',
            correo: 'freddy_cauja@coacsantaanita.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Santiago Quishpe',
            gestorServicio: 'Luisa Moreno',
            correoGestor: 'lmoreno@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\SANTAANITA',
            infraestructura: ''
        },
        {
            cooperativa: 'SANTO CRISTO DE BAGAZÁN',
            codigo: 'CSCB',
            contacto: 'John del Aguila',
            correo: 'jdelaguila.v@cscb.com.pe',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'TFS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: '',
            liderProyecto: 'Cristian Moreno',
            gestorServicio: 'Katherin Freire',
            correoGestor: 'kfreire@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'SUMAK KAWSAY',
            codigo: 'SKAWSAY',
            contacto: 'Edwin Cruz',
            correo: 'edwin.cruz@sumakkawsay.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Fernando Chamorro',
            gestorServicio: 'Luisa Moreno',
            correoGestor: 'lmoreno@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\SUMAK',
            infraestructura: ''
        },
        {
            cooperativa: 'TENA',
            codigo: 'TENA',
            contacto: 'Gonzalo Ibarra',
            correo: 'gibarra@cooptena.fin.ec',
            version: '2.0',
            visualStudio: 'VS2013',
            repositorio: 'GIT',
            admCodigo: 'Cooperativa',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'SI',
            liderProyecto: 'Víctor Hidalgo',
            gestorServicio: 'Jaqueline Reino',
            correoGestor: 'jreino@sifizsoft.com',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'UNION EJIDO',
            codigo: 'UEJID',
            contacto: 'Patricio Erazo',
            correo: 'soporte@elejido.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Bolivar Vallejo',
            gestorServicio: 'Jaqueline Reino',
            correoGestor: 'jreino@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\UEjido',
            infraestructura: ''
        },
        {
            cooperativa: 'UNION POPULAR',
            codigo: 'UPOPU',
            contacto: 'Wendy Castro',
            correo: 'sistemas@coacunionpopular.com',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Operaciones',
            gestorServicio: 'Gissela Torres',
            correoGestor: 'asistentecomiteoperaciones@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\UNIONPOPULAR',
            infraestructura: ''
        },
        {
            cooperativa: 'UNIVERSIDAD CATÓLICA',
            codigo: 'UCATO',
            contacto: 'Oscar Vallejo',
            correo: 'odvallejom@coopuce.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Fernando Chamorro',
            gestorServicio: 'Luisa Moreno',
            correoGestor: 'lmoreno@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\UCATOLICA',
            infraestructura: ''
        },
        {
            cooperativa: 'UNIVERSIDAD POLITÉCNICA',
            codigo: 'POLIT',
            contacto: 'Tatiana Villota',
            correo: 'tvillota@coacpolitecnica.fin.ec',
            version: '2.0',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'SifizSoft S. A.',
            publicacion: 'SifizSoft S. A.',
            solucionProxies: 'SI',
            liderProyecto: 'Bolivar Vallejo',
            gestorServicio: 'Bolivar Vallejo',
            correoGestor: 'bvallejo@sifizsoft.com',
            path: 'D:\\DEVOPS\\VS2022\\POLITÉCNICA',
            infraestructura: ''
        },
        {
            cooperativa: 'VIRGEN DEL CISNE',
            codigo: 'VDCIS',
            contacto: 'Fernando Arías',
            correo: 'sistemas@virgendelcisne.fin.ec',
            version: '2.5',
            visualStudio: 'VS2022',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'NO',
            liderProyecto: 'Jorge Romero',
            gestorServicio: 'Gabriela Cárdenas',
            correoGestor: 'gcardenas@intecsoft.com.ec',
            path: '',
            infraestructura: ''
        },
        {
            cooperativa: 'VISIONFUND ECUADOR',
            codigo: 'VFE',
            contacto: 'William Garcia',
            correo: 'wgarcia@visionfund.ec',
            version: '2.0',
            visualStudio: 'VS2017',
            repositorio: 'DEVOPS',
            admCodigo: 'SifizSoft S. A.',
            integracion: 'Cooperativa',
            publicacion: 'Cooperativa',
            solucionProxies: 'Si',
            liderProyecto: 'Operaciones',
            gestorServicio: 'Katherin Freire',
            correoGestor: 'kfreire@sifizsoft.com',
            path: 'D:\\TFS\\VS2017\\VFE',
            infraestructura: ''
        }
    ];

    // Función de búsqueda y paginación
    $scope.buscar = function() {
        console.log('Llamando a buscar()...');
        $timeout(function() {
            realizarBusqueda();
            if(!$scope.$$phase) {
                $scope.$apply();
            }
        });
    };

    function realizarBusqueda() {
        console.log('Panel debug - Ejecutando búsqueda...');
        var datos = angular.copy($scope.versiones);
        console.log('Panel debug - Datos iniciales:', datos.length);
        console.log('Panel debug - Contenido del panel:', document.getElementById('panel-listado-versiones'));
        
        // Aplicar filtro de texto si existe
        if ($scope.filtro) {
            var texto = $scope.filtro.toLowerCase();
            datos = datos.filter(function(v) {
                return Object.values(v).join(' ').toLowerCase().indexOf(texto) !== -1;
            });
        }
        
        // Aplicar filtro de infraestructura si existe
        if ($scope.filtroInfra) {
            datos = datos.filter(function(v) {
                return v.infraestructura === $scope.filtroInfra;
            });
        }
        
        console.log('Datos después de filtros:', datos.length);

        // Actualizar paginación
        $scope.paginado.total = datos.length;
        $scope.paginado.totalPaginas = Math.max(1, Math.ceil(datos.length / $scope.paginado.tam));
        $scope.paginado.paginas = [];
        for (var i = 1; i <= $scope.paginado.totalPaginas; i++) {
            $scope.paginado.paginas.push(i);
        }

        // Obtener datos de la página actual
        var inicio = ($scope.paginado.pagina - 1) * $scope.paginado.tam;
        $scope.paginado.datos = datos.slice(inicio, inicio + $scope.paginado.tam);
        
        console.log('Datos paginados:', $scope.paginado.datos.length);
        console.log('Primera fila:', $scope.paginado.datos[0]);
    };
    $scope.cambiarPagina = function(n) {
        if(n<1||n>$scope.paginado.totalPaginas) return;
        $scope.paginado.pagina = n;
        $scope.buscar();
    };
    $scope.abrirModal = function(v) {
        $scope.editando = !!v;
        $scope.form = v ? angular.copy(v) : {};
        $('#modalVersion').modal('show');
    };
    $scope.guardar = function() {
        if($scope.editando) {
            var idx = $scope.versiones.findIndex(x=>x.codigo==$scope.form.codigo);
            if(idx>=0) $scope.versiones[idx] = angular.copy($scope.form);
        } else {
            $scope.versiones.push(angular.copy($scope.form));
        }
        $('#modalVersion').modal('hide');
        $scope.buscar();
    };
    $scope.eliminar = function(v) {
        if(confirm('¿Eliminar este registro?')) {
            $scope.versiones = $scope.versiones.filter(x=>x!==v);
            $scope.buscar();
        }
    };
    $scope.verDetalle = function(v) {
        $scope.detalle = v;
        $('#modalDetalle').modal('show');
    };
    // Inicializar datos
    function init() {
        try {
            console.log('Iniciando inicialización...');
            $timeout(function() {
                if ($scope.versiones && $scope.versiones.length > 0) {
                    console.log('Datos disponibles');
                    realizarBusqueda();
                    if (!$scope.$$phase) {
                        $scope.$apply();
                    }
                }
            });
        } catch (err) {
            console.error('Error en init:', err);
        }
    }

    // Llamar a init cuando el controlador se inicialice
    init();
    
    // Ejecutar búsqueda inicial después de un momento
    $timeout(function() {
        realizarBusqueda();
    }, 100);

    // Watch para detectar cambios en versiones
    $scope.$watch('versiones', function(newVal) {
        if (newVal && newVal.length > 0) {
            console.log('Versiones actualizadas:', newVal.length);
            $scope.buscar();
        }
    });
}]);
