USE [SifizPlanning]
GO

/****** Object:  Table [TAREAS].[FASECONTRATO]    Script Date: 11/19/2020 4:45:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [TAREAS].[FASECONTRATO](
	[SECUENCIAL] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO] [varchar](30) NOT NULL,
	[DESCRIPCION] [varchar](250) NOT NULL,
	[ESTAACTIVO] [numeric](1, 0) NOT NULL,
	[NUMEROVERIFICADOR] [int] NOT NULL,
 CONSTRAINT [PK_FASECONTRATO] PRIMARY KEY CLUSTERED 
(
	[SECUENCIAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


