CREATE TABLE [TAREAS].[MOTIVOTRABAJOINFADICIONAL] (
  [SECUENCIALMOTIVOTRABAJO] int  NOT NULL,
  [TIENECRONOGRAMA] numeric(1)  NOT NULL,
  [ESTAACTIVO] numeric(1)  NOT NULL,
  [NUMEROVERIFICADOR] int  NOT NULL,
  [SECUENCIALFASE] int  NOT NULL,
  [LINKOPENKM] varchar(250) COLLATE Modern_Spanish_CI_AS  NOT NULL,
  CONSTRAINT [PK_MOTIVOTRABAJOINFADICIONAL] PRIMARY KEY CLUSTERED ([SECUENCIALMOTIVOTRABAJO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)  
ON [PRIMARY],
  CONSTRAINT [FK_MOTIVOTRABAJOINFADICIONAL_FASECONTRATO] FOREIGN KEY ([SECUENCIALFASE]) REFERENCES [TAREAS].[FASECONTRATO] ([SECUENCIAL]) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT [FK_MOTIVOTRABAJOINFADICIONAL_MOTIVOTRABAJO] FOREIGN KEY ([SECUENCIALMOTIVOTRABAJO]) REFERENCES [TAREAS].[MOTIVOTRABAJO] ([SECUENCIAL]) ON DELETE NO ACTION ON UPDATE NO ACTION
)  
ON [PRIMARY]
GO

ALTER TABLE [TAREAS].[MOTIVOTRABAJOINFADICIONAL] SET (LOCK_ESCALATION = TABLE)