CREATE TABLE [TAREAS].[ADENDA] (
  [SECUENCIAL] int  IDENTITY(1,1) NOT NULL,
  [CODIGO] varchar(30) COLLATE Modern_Spanish_CI_AS  NOT NULL,
  [FECHAVENCIMIENTO] date  NOT NULL,
  [ESTAACTIVO] numeric(1)  NOT NULL,
  [NUMEROVERIFICADOR] int  NOT NULL,
  [SECUENCIALMOTIVOTRABINFOADIC] int  NOT NULL,
  CONSTRAINT [PK_ADENDA] PRIMARY KEY CLUSTERED ([SECUENCIAL])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)  
ON [PRIMARY],
  CONSTRAINT [FK_ADENDA_MOTIVOTRABAJOINFADICIONAL] FOREIGN KEY ([SECUENCIALMOTIVOTRABINFOADIC]) REFERENCES [TAREAS].[MOTIVOTRABAJOINFADICIONAL] ([SECUENCIALMOTIVOTRABAJO]) ON DELETE NO ACTION ON UPDATE NO ACTION
)  
ON [PRIMARY]
GO

ALTER TABLE [TAREAS].[ADENDA] SET (LOCK_ESCALATION = TABLE)