CREATE TABLE [TAREAS].[MOTIVOTRABAJOSEGUIMIENTO] (
  [SECUENCIAL] int  IDENTITY(1,1) NOT NULL,
  [FECHA] date  NOT NULL,
  [REALIZADO] varchar(250) COLLATE Modern_Spanish_CI_AS  NOT NULL,
  [PORREALIZAR] varchar(250) COLLATE Modern_Spanish_CI_AS  NOT NULL,
  [PENDIENTE] varchar(250) COLLATE Modern_Spanish_CI_AS  NOT NULL,
  [ESTAACTIVO] numeric(1)  NOT NULL,
  [NUMEROVERIFICADOR] int  NOT NULL,
  [SECUENCIALMOTTRAINFADICIONAL] int  NOT NULL,
  CONSTRAINT [PK_MOTIVOTRABAJOSEGUIMIENTO] PRIMARY KEY CLUSTERED ([SECUENCIAL])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)  
ON [PRIMARY],
  CONSTRAINT [FK_MOTIVOTRABAJOSEGUIMIENTO_MOTIVOTRABAJOINFADICIONAL] FOREIGN KEY ([SECUENCIALMOTTRAINFADICIONAL]) REFERENCES [TAREAS].[MOTIVOTRABAJOINFADICIONAL] ([SECUENCIALMOTIVOTRABAJO]) ON DELETE NO ACTION ON UPDATE NO ACTION
)  
ON [PRIMARY]
GO

ALTER TABLE [TAREAS].[MOTIVOTRABAJOSEGUIMIENTO] SET (LOCK_ESCALATION = TABLE)