USE SifizPlanning;
GO

IF OBJECT_ID('TICKET.INCIDENCIAS', 'U') IS NOT NULL
BEGIN
 ALTER TABLE TICKET.INCIDENCIAS
 ALTER COLUMN INCIDENTE NVARCHAR(MAX)

 ALTER TABLE TICKET.INCIDENCIAS
 ALTER COLUMN ACCIONES NVARCHAR(MAX)

 ALTER TABLE TICKET.INCIDENCIAS
 ALTER COLUMN ADJUNTO NVARCHAR(MAX)
END
GO