ALTER TABLE [SifizPlanning].[Ticket].[DETALLEESTIMACIONTICKET]
ALTER COLUMN [TIEMPOQA] float;

ALTER TABLE [SifizPlanning].[Ticket].[DETALLEESTIMACIONTICKET]
ALTER COLUMN [TIEMPOPRUEBA] float;

ALTER TABLE [SifizPlanning].[Ticket].[DETALLEESTIMACIONTICKET]
ALTER COLUMN [TIEMPODESARROLLO] float;

ALTER TABLE [SifizPlanning].[Ticket].[DETALLEESTIMACIONTICKET]
ALTER COLUMN [TIEMPOESTIMACION] float;

ALTER TABLE [SifizPlanning].[Ticket].[ESTIMACIONTICKET]
ALTER COLUMN [TIEMPOINICIAL] float;

ALTER TABLE [SifizPlanning].[Ticket].[ESTIMACIONTICKET]
ALTER COLUMN [TIEMPOPEGADO] float;

ALTER TABLE [SifizPlanning].[Ticket].[ITEMESPECIAL]
ALTER COLUMN [TIEMPOESTIMACION] float;

ALTER TABLE [SifizPlanning].[Ticket].[ITEMESPECIALESTIMACION]
ALTER COLUMN [TIEMPOESTIMACION] float;