//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acta
    {
        public int Secuencial { get; set; }
        public int SecuencialCliente { get; set; }
        public int SecuencialColaborador { get; set; }
        public int SecuencialEstado { get; set; }
        public int SecuencialTipo { get; set; }
        public int SecuencialContrato { get; set; }
        public System.DateTime FechaFirma { get; set; }
        public string Codigo { get; set; }
        public string LinkOpenkm { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
        public Nullable<int> SecuencialEntregable { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> DiasFacturacion { get; set; }
    
        public virtual Cliente CLIENTE { get; set; }
        public virtual Colaborador COLABORADOR { get; set; }
        public virtual MotivoTrabajo MOTIVOTRABAJO { get; set; }
        public virtual EstadoActa EstadoActa { get; set; }
        public virtual TipoActa TipoActa { get; set; }
        public virtual EntregableMotivoTrabajo EntregableMotivoTrabajo { get; set; }
    }
}
