//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadRealizada
    {
        public ActividadRealizada()
        {
            this.tareaActividadRealizada = new HashSet<TareaActividadRealizada>();
            this.ACTIVIDADACTIVIDADREALIZADA = new HashSet<ActividadActividadRealizada>();
        }
    
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActiva { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<TareaActividadRealizada> tareaActividadRealizada { get; set; }
        public virtual ICollection<ActividadActividadRealizada> ACTIVIDADACTIVIDADREALIZADA { get; set; }
    }
}
