//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadActividadRealizada
    {
        public int Secuencial { get; set; }
        public int SecuencialActividad { get; set; }
        public int SecuencialActividadRealizada { get; set; }
        public decimal EstaActiva { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual Actividad actividad { get; set; }
        public virtual ActividadRealizada actividadRealizada { get; set; }
    }
}
