//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adenda
    {
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
        public int SecuencialMotivoTrabajoInformacionAdicional { get; set; }
        public string LinkOpenKM { get; set; }
    
        public virtual MotivoTrabajoInformacionAdicional motivoTrabajoInformacionAdicional { get; set; }
    }
}
