//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjuntoContrato
    {
        public int Secuencial { get; set; }
        public string Url { get; set; }
        public int SecuencialContrato { get; set; }
        public string Descripcion { get; set; }
    
        public virtual MotivoTrabajo motivoTrabajo { get; set; }
    }
}
