//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BotonEstadoTicket
    {
        public int Secuencial { get; set; }
        public string ClaseCss { get; set; }
        public string Funcion { get; set; }
        public string Descripcion { get; set; }
        public int NumeroVerificador { get; set; }
        public int SecuencialEstadoTicket { get; set; }
        public string CssIcono { get; set; }
    
        public virtual EstadoTicket estadoTicket { get; set; }
    }
}
