//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildDetailsView
    {
        public string BuildDetailsBK { get; set; }
        public Nullable<long> BuildDuration { get; set; }
        public Nullable<System.Guid> TeamProjectProjectNodeGUID { get; set; }
        public string TeamProjectProjectNodeName { get; set; }
        public Nullable<int> TeamProjectProjectNodeType { get; set; }
        public string TeamProjectProjectNodeTypeName { get; set; }
        public Nullable<bool> TeamProjectIsDeleted { get; set; }
        public string TeamProjectReportPath { get; set; }
        public string TeamProjectProjectPath { get; set; }
        public Nullable<int> TeamProjectDepth { get; set; }
        public string BuildBK { get; set; }
        public string BuildID { get; set; }
        public string BuildName { get; set; }
        public string BuildType { get; set; }
        public string BuildDefinitionName { get; set; }
        public string BuildDropLocation { get; set; }
        public Nullable<System.DateTime> BuildStartTime { get; set; }
        public Nullable<int> BuildTeamProjectCollectionSK { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> DateYear { get; set; }
        public string DateYearString { get; set; }
        public Nullable<System.DateTime> DateMonth { get; set; }
        public string DateMonthString { get; set; }
        public Nullable<int> DateMonthOfYear { get; set; }
        public Nullable<System.DateTime> DateWeek { get; set; }
        public string DateWeekString { get; set; }
        public Nullable<int> DateWeekOfYear { get; set; }
        public string Date { get; set; }
        public Nullable<int> DateDayOfYear { get; set; }
        public Nullable<int> DateDayOfMonth { get; set; }
        public Nullable<int> DateDayOfWeek { get; set; }
        public string BuildQualityName { get; set; }
        public string BuildStatusName { get; set; }
        public Nullable<int> BuildStatusNameId { get; set; }
        public string LastUpdatedByName { get; set; }
        public string LastUpdatedBySID { get; set; }
        public string LastUpdatedByDomain { get; set; }
        public string LastUpdatedByAlias { get; set; }
        public string LastUpdatedByEmail { get; set; }
    }
}
