//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildProjectView
    {
        public string BuildProjectBK { get; set; }
        public Nullable<int> CompileErrors { get; set; }
        public Nullable<int> CompileWarnings { get; set; }
        public Nullable<int> StaticAnalysisErrors { get; set; }
        public Nullable<int> StaticAnalysisWarnings { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> DateYear { get; set; }
        public string DateYearString { get; set; }
        public Nullable<System.DateTime> DateMonth { get; set; }
        public string DateMonthString { get; set; }
        public Nullable<int> DateMonthOfYear { get; set; }
        public Nullable<System.DateTime> DateWeek { get; set; }
        public string DateWeekString { get; set; }
        public Nullable<int> DateWeekOfYear { get; set; }
        public string Date { get; set; }
        public Nullable<int> DateDayOfYear { get; set; }
        public Nullable<int> DateDayOfMonth { get; set; }
        public Nullable<int> DateDayOfWeek { get; set; }
        public Nullable<System.Guid> TeamProjectProjectNodeGUID { get; set; }
        public string TeamProjectProjectNodeName { get; set; }
        public Nullable<int> TeamProjectProjectNodeType { get; set; }
        public string TeamProjectProjectNodeTypeName { get; set; }
        public Nullable<bool> TeamProjectIsDeleted { get; set; }
        public string TeamProjectReportPath { get; set; }
        public string TeamProjectProjectPath { get; set; }
        public Nullable<int> TeamProjectDepth { get; set; }
        public string BuildBK { get; set; }
        public string BuildID { get; set; }
        public string BuildName { get; set; }
        public string BuildType { get; set; }
        public string BuildDefinitionName { get; set; }
        public string BuildDropLocation { get; set; }
        public Nullable<System.DateTime> BuildStartTime { get; set; }
        public Nullable<int> BuildTeamProjectCollectionSK { get; set; }
        public string BuildPlatformName { get; set; }
        public string BuildFlavorName { get; set; }
        public string SourceProjectFileName { get; set; }
        public string SourceProjectFileBK { get; set; }
        public string SourceProjectFilePath { get; set; }
        public string SourceProjectFileExtension { get; set; }
        public Nullable<int> SourceProjectTeamProjectCollectionSK { get; set; }
    }
}
