//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildChangesetView
    {
        public string BuildChangesetBK { get; set; }
        public Nullable<System.Guid> TeamProjectProjectNodeGUID { get; set; }
        public string TeamProjectProjectNodeName { get; set; }
        public Nullable<int> TeamProjectProjectNodeType { get; set; }
        public string TeamProjectProjectNodeTypeName { get; set; }
        public Nullable<bool> TeamProjectIsDeleted { get; set; }
        public string TeamProjectReportPath { get; set; }
        public string TeamProjectProjectPath { get; set; }
        public Nullable<int> TeamProjectDepth { get; set; }
        public string BuildBK { get; set; }
        public string BuildID { get; set; }
        public string BuildName { get; set; }
        public string BuildType { get; set; }
        public string BuildDefinitionName { get; set; }
        public string BuildDropLocation { get; set; }
        public Nullable<System.DateTime> BuildStartTime { get; set; }
        public Nullable<int> BuildTeamProjectCollectionSK { get; set; }
        public string ChangesetBK { get; set; }
        public Nullable<int> ChangesetID { get; set; }
        public string ChangesetTitle { get; set; }
        public string ChangesetPolicyOverrideComment { get; set; }
        public Nullable<int> ChangesetTeamProjectCollectionSK { get; set; }
        public Nullable<int> ChangesetCheckedInBySK { get; set; }
    }
}
