//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_LastUpdatedTime
    {
        public string CollectionName { get; set; }
        public Nullable<System.Guid> CollectionId { get; set; }
        public string JobName { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public int EnabledState { get; set; }
        public System.DateTime WarehouseLastUpdated { get; set; }
        public System.DateTime SnapshotLastUpdated { get; set; }
        public System.DateTime AnalysisLastUpdated { get; set; }
        public string Warning { get; set; }
    }
}
