//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WitFields
    {
        public int SK { get; set; }
        public string ReferenceName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<int> ReportingType { get; set; }
        public Nullable<int> ReportingFormula { get; set; }
        public string ReportingReferenceName { get; set; }
        public string ReportingDisplayName { get; set; }
        public int DataTypeTo { get; set; }
        public int ReportingTypeTo { get; set; }
        public int ReportingFormulaTo { get; set; }
        public string ReportingReferenceNameTo { get; set; }
        public string ReportingDisplayNameTo { get; set; }
        public string TeamProjectCollectionBK { get; set; }
        public int FieldId { get; set; }
        public Nullable<int> WarehouseState { get; set; }
        public string BackfillWatermark { get; set; }
    }
}
