//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalificacionTicketCliente
    {
        public int Secuencial { get; set; }
        public int SecuencialCalificacion { get; set; }
        public int SecuencialTicket { get; set; }
        public int Calificacion { get; set; }
    
        public virtual CalificacionTicket calificacionTicket { get; set; }
        public virtual Ticket ticket { get; set; }
    }
}
