//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampoCatalogo
    {
        public int Secuencial { get; set; }
        public int SecuencialTablaCatalogo { get; set; }
        public string NombreMostrar { get; set; }
        public string NombreNegocio { get; set; }
        public string Descripcion { get; set; }
        public int SecuencialTipoCampo { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual CampoCatalogo_TablaCatalogo campoCatalogo_tablaCatalogo { get; set; }
        public virtual TablaCatalogo tablaCatalogo { get; set; }
        public virtual TipoCampo tipoCampo { get; set; }
    }
}
