//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaTicketTipoContrClient
    {
        public int Secuencial { get; set; }
        public int SecuencialCategoriaTicket { get; set; }
        public int SecuencialTipoContratoCliente { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual CategoriaTicket categoriaTicket { get; set; }
        public virtual TipoContratoCliente tipoContratoCliente { get; set; }
    }
}
