//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaTicket
    {
        public CategoriaTicket()
        {
            this.ticket = new HashSet<Ticket>();
            this.ticketHistorico = new HashSet<TicketHistorico>();
            this.categoriaTicketTipoContrClient = new HashSet<CategoriaTicketTipoContrClient>();
            this.TICKET_CATEGORIAREVISADA = new HashSet<Ticket_CategoriaRevisada>();
            this.ticketHistoricoCategoria = new HashSet<TicketHistorico>();
        }
    
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActiva { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<Ticket> ticket { get; set; }
        public virtual ICollection<TicketHistorico> ticketHistorico { get; set; }
        public virtual ICollection<CategoriaTicketTipoContrClient> categoriaTicketTipoContrClient { get; set; }
        public virtual ICollection<Ticket_CategoriaRevisada> TICKET_CATEGORIAREVISADA { get; set; }
        public virtual ICollection<TicketHistorico> ticketHistoricoCategoria { get; set; }
    }
}
