//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteAuxiliar
    {
        public ClienteAuxiliar()
        {
            this.etapasProyectoCliente = new HashSet<EtapasProyectoCliente>();
            this.tiemposProyecto = new HashSet<TiemposProyecto>();
        }
    
        public int Secuencial { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
        public int SecuencialCliente { get; set; }
        public int SecuencialVersionDesarrollo { get; set; }
        public int SecuencialRepositorio { get; set; }
        public Nullable<int> SecuencialUbicacion { get; set; }
        public decimal TieneCodigoFuente { get; set; }
        public int SecuencialResponsableAcceso { get; set; }
        public int SecuencialResponsableCodigo { get; set; }
        public int SecuencialResponsablePublicacion { get; set; }
        public int SecuencialVersionBaseDatos { get; set; }
        public int SecuencialLiderProyecto { get; set; }
        public decimal TieneSolucionProxies { get; set; }
        public System.DateTime FechaProduccion { get; set; }
        public string PathFuentes { get; set; }
        public string VersionFBS { get; set; }
    
        public virtual Cliente cliente { get; set; }
        public virtual Colaborador colaborador { get; set; }
        public virtual Repositorio repositorio { get; set; }
        public virtual ResponsableProyectos ubicacion { get; set; }
        public virtual ResponsableProyectos responsableAcceso { get; set; }
        public virtual ResponsableProyectos responsableCodigo { get; set; }
        public virtual ResponsableProyectos responsablePublicacion { get; set; }
        public virtual VersionBaseDatos versionBaseDatos { get; set; }
        public virtual VersionDesarrollo versionDesarrollo { get; set; }
        public virtual ICollection<EtapasProyectoCliente> etapasProyectoCliente { get; set; }
        public virtual ICollection<TiemposProyecto> tiemposProyecto { get; set; }
    }
}
