//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.persona_cliente = new HashSet<Persona_Cliente>();
            this.contratoCliente = new HashSet<ContratoCliente>();
            this.motivoTrabajo = new HashSet<MotivoTrabajo>();
            this.tarea = new HashSet<Tarea>();
            this.colaboradorIncidencia = new HashSet<ColaboradorIncidencia>();
            this.proyectoTFS = new HashSet<ProyectoTFS>();
            this.Acta = new HashSet<Acta>();
            this.FuncionalidadCliente = new HashSet<FuncionalidadCliente>();
            this.proyectoModuloCliente = new HashSet<ProyectoModuloCliente>();
            this.gestorServicios = new HashSet<GestorServicios>();
            this.comentarioHorasMantenimiento = new HashSet<ComentarioHorasMantenimiento>();
            this.comentarioTicketCliente = new HashSet<ComentarioTicketCliente>();
            this.clienteAuxiliar = new HashSet<ClienteAuxiliar>();
            this.ofertas = new HashSet<Ofertas>();
            this.INCIDENCIAS = new HashSet<Incidencias>();
            this.TIEMPOCERRADOTICKET = new HashSet<TiempoCerradoTicket>();
            this.clienteReporteMantenimiento = new HashSet<ClienteReporteMantenimiento>();
        }
    
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<Persona_Cliente> persona_cliente { get; set; }
        public virtual ICollection<ContratoCliente> contratoCliente { get; set; }
        public virtual ICollection<MotivoTrabajo> motivoTrabajo { get; set; }
        public virtual ICollection<Tarea> tarea { get; set; }
        public virtual ICollection<ColaboradorIncidencia> colaboradorIncidencia { get; set; }
        public virtual ICollection<ProyectoTFS> proyectoTFS { get; set; }
        public virtual ICollection<Acta> Acta { get; set; }
        public virtual ICollection<FuncionalidadCliente> FuncionalidadCliente { get; set; }
        public virtual ICollection<ProyectoModuloCliente> proyectoModuloCliente { get; set; }
        public virtual ICollection<GestorServicios> gestorServicios { get; set; }
        public virtual ICollection<ComentarioHorasMantenimiento> comentarioHorasMantenimiento { get; set; }
        public virtual ICollection<ComentarioTicketCliente> comentarioTicketCliente { get; set; }
        public virtual ICollection<ClienteAuxiliar> clienteAuxiliar { get; set; }
        public virtual ICollection<Ofertas> ofertas { get; set; }
        public virtual ICollection<Incidencias> INCIDENCIAS { get; set; }
        public virtual ICollection<TiempoCerradoTicket> TIEMPOCERRADOTICKET { get; set; }
        public virtual ICollection<ClienteReporteMantenimiento> clienteReporteMantenimiento { get; set; }
    }
}
