//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTEREPORTEMTTO
    {
        public int SECUENCIAL { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ESTAACTIVO { get; set; }
        public int NUMEROVERIFICADOR { get; set; }
        public int SECUENCIALCLIENTE { get; set; }
    }
}
