//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeChurnView
    {
        public string CodeChurnBK { get; set; }
        public Nullable<int> LinesAdded { get; set; }
        public Nullable<int> LinesModified { get; set; }
        public Nullable<int> LinesDeleted { get; set; }
        public Nullable<int> NetLinesAdded { get; set; }
        public Nullable<System.Guid> TeamProjectProjectNodeGUID { get; set; }
        public string TeamProjectProjectNodeName { get; set; }
        public Nullable<int> TeamProjectProjectNodeType { get; set; }
        public string TeamProjectProjectNodeTypeName { get; set; }
        public Nullable<bool> TeamProjectIsDeleted { get; set; }
        public string TeamProjectReportPath { get; set; }
        public string TeamProjectProjectPath { get; set; }
        public Nullable<int> TeamProjectDepth { get; set; }
        public string ChangesetBK { get; set; }
        public Nullable<int> ChangesetID { get; set; }
        public string ChangesetTitle { get; set; }
        public string ChangesetPolicyOverrideComment { get; set; }
        public Nullable<int> ChangesetTeamProjectCollectionSK { get; set; }
        public string CheckedInByName { get; set; }
        public string CheckedInBySID { get; set; }
        public string CheckedInByDomain { get; set; }
        public string CheckedInByAlias { get; set; }
        public string CheckedInByEmail { get; set; }
        public string FileName { get; set; }
        public string FilenameFileBK { get; set; }
        public string FilenameFilePath { get; set; }
        public string FilenameFileExtension { get; set; }
        public Nullable<int> FilenameTeamProjectCollectionSK { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> DateYear { get; set; }
        public string DateYearString { get; set; }
        public Nullable<System.DateTime> DateMonth { get; set; }
        public string DateMonthString { get; set; }
        public Nullable<int> DateMonthOfYear { get; set; }
        public Nullable<System.DateTime> DateWeek { get; set; }
        public string DateWeekString { get; set; }
        public Nullable<int> DateWeekOfYear { get; set; }
        public string Date { get; set; }
        public Nullable<int> DateDayOfYear { get; set; }
        public Nullable<int> DateDayOfMonth { get; set; }
        public Nullable<int> DateDayOfWeek { get; set; }
    }
}
