//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaborador
    {
        public Colaborador()
        {
            this.tarea_coordinador = new HashSet<Tarea_Coordinador>();
            this.fotoColaborador = new HashSet<FotoColaborador>();
            this.colaborador_jefeInmediato1 = new HashSet<Colaborador_JefeInmediato>();
            this.colaboradorEspecialidad = new HashSet<ColaboradorEspecialidad>();
            this.estimacionTicket = new HashSet<EstimacionTicket>();
            this.cotizacionTicket = new HashSet<CotizacionTicket>();
            this.solicitudTarea = new HashSet<SolicitudTarea>();
            this.tarea = new HashSet<Tarea>();
            this.permiso = new HashSet<Permiso>();
            this.vacaciones = new HashSet<Vacaciones>();
            this.colaboradorIncidencia = new HashSet<ColaboradorIncidencia>();
            this.nivelColaboradorModulo = new HashSet<NivelColaboradorModulo>();
            this.colaboradorNivelCompetencia = new HashSet<ColaboradorNivelCompetencia>();
            this.marcaElectronica = new HashSet<MarcaElectronica>();
            this.usuarioTFS = new HashSet<UsuarioTFS>();
            this.TICKET_RESOLUCIONDESACUERDO = new HashSet<Ticket_ResolucionDesacuerdo>();
            this.TICKET_RESOLUCION = new HashSet<Ticket_Resolucion>();
            this.TICKET_ERROR = new HashSet<Ticket_Error>();
            this.TICKET_PRIORIDADREVISADA = new HashSet<Ticket_PrioridadRevisada>();
            this.TICKET_CATEGORIAREVISADA = new HashSet<Ticket_CategoriaRevisada>();
            this.COMENTARIOTICKET = new HashSet<ComentarioTicket>();
            this.NOTERMINACIONTICKET = new HashSet<NoTerminacionTicket>();
            this.Acta = new HashSet<Acta>();
            this.entregableMotivoTrabajo = new HashSet<EntregableMotivoTrabajo>();
            this.motivoTrabajo = new HashSet<MotivoTrabajo>();
            this.gestorServicios = new HashSet<GestorServicios>();
            this.clientesLider = new HashSet<ClienteAuxiliar>();
            this.ofertas = new HashSet<Ofertas>();
            this.NIVELCOLABORADORTECNOLOGIA = new HashSet<NivelColaboradorTecnologia>();
            this.incidencias = new HashSet<Incidencias>();
            this.INCIDENCIASRECURSOS = new HashSet<IncidenciasRecursos>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialPersona { get; set; }
        public int SecuencialSede { get; set; }
        public int SecuencialCargo { get; set; }
        public int NumeroVerificador { get; set; }
        public int SecuencialDepartamento { get; set; }
        public Nullable<bool> PublicacionesDosCinco { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual Cargo cargo { get; set; }
        public virtual ICollection<Tarea_Coordinador> tarea_coordinador { get; set; }
        public virtual Colaborador_JefeInmediato colaborador_jefeInmediato { get; set; }
        public virtual ICollection<FotoColaborador> fotoColaborador { get; set; }
        public virtual ICollection<Colaborador_JefeInmediato> colaborador_jefeInmediato1 { get; set; }
        public virtual Persona persona { get; set; }
        public virtual Sede sede { get; set; }
        public virtual ICollection<ColaboradorEspecialidad> colaboradorEspecialidad { get; set; }
        public virtual Departamento departamento { get; set; }
        public virtual ICollection<EstimacionTicket> estimacionTicket { get; set; }
        public virtual ICollection<CotizacionTicket> cotizacionTicket { get; set; }
        public virtual ICollection<SolicitudTarea> solicitudTarea { get; set; }
        public virtual ICollection<Tarea> tarea { get; set; }
        public virtual ICollection<Permiso> permiso { get; set; }
        public virtual ICollection<Vacaciones> vacaciones { get; set; }
        public virtual ICollection<ColaboradorIncidencia> colaboradorIncidencia { get; set; }
        public virtual ICollection<NivelColaboradorModulo> nivelColaboradorModulo { get; set; }
        public virtual ICollection<ColaboradorNivelCompetencia> colaboradorNivelCompetencia { get; set; }
        public virtual ICollection<MarcaElectronica> marcaElectronica { get; set; }
        public virtual ICollection<UsuarioTFS> usuarioTFS { get; set; }
        public virtual ICollection<Ticket_ResolucionDesacuerdo> TICKET_RESOLUCIONDESACUERDO { get; set; }
        public virtual ICollection<Ticket_Resolucion> TICKET_RESOLUCION { get; set; }
        public virtual ICollection<Ticket_Error> TICKET_ERROR { get; set; }
        public virtual ICollection<Ticket_PrioridadRevisada> TICKET_PRIORIDADREVISADA { get; set; }
        public virtual ICollection<Ticket_CategoriaRevisada> TICKET_CATEGORIAREVISADA { get; set; }
        public virtual ICollection<ComentarioTicket> COMENTARIOTICKET { get; set; }
        public virtual ICollection<NoTerminacionTicket> NOTERMINACIONTICKET { get; set; }
        public virtual ICollection<Acta> Acta { get; set; }
        public virtual ICollection<EntregableMotivoTrabajo> entregableMotivoTrabajo { get; set; }
        public virtual ICollection<MotivoTrabajo> motivoTrabajo { get; set; }
        public virtual ICollection<GestorServicios> gestorServicios { get; set; }
        public virtual ICollection<ClienteAuxiliar> clientesLider { get; set; }
        public virtual ICollection<Ofertas> ofertas { get; set; }
        public virtual ICollection<NivelColaboradorTecnologia> NIVELCOLABORADORTECNOLOGIA { get; set; }
        public virtual ICollection<Incidencias> incidencias { get; set; }
        public virtual ICollection<IncidenciasRecursos> INCIDENCIASRECURSOS { get; set; }
    }
}
