//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColaboradorIncidencia
    {
        public int Secuencial { get; set; }
        public int SecuencialTipoError { get; set; }
        public int SecuencialColaborador { get; set; }
        public int SecuencialImplicacionError { get; set; }
        public int SecuencialCliente { get; set; }
        public int SecuencialUsuario { get; set; }
        public System.DateTime FechaIncidencia { get; set; }
        public string Hecho { get; set; }
        public string Justificacion { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public decimal EstaActiva { get; set; }
        public int NumeroVerificador { get; set; }
        public int Puntos { get; set; }
    
        public virtual Usuario usuario { get; set; }
        public virtual Cliente cliente { get; set; }
        public virtual Colaborador colaborador { get; set; }
        public virtual ImplicacionError implicacionError { get; set; }
        public virtual TipoError tipoError { get; set; }
    }
}
