//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentarioTicket
    {
        public ComentarioTicket()
        {
            this.comentarioTicketCliente = new HashSet<ComentarioTicketCliente>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialTicket { get; set; }
        public int SecuencialColaborador { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Detalle { get; set; }
        public int NumeroVerificador { get; set; }
        public Nullable<decimal> VerTodos { get; set; }
    
        public virtual Colaborador colaborador { get; set; }
        public virtual Ticket ticket { get; set; }
        public virtual ICollection<ComentarioTicketCliente> comentarioTicketCliente { get; set; }
    }
}
