//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentarioTarea
    {
        public int Secuencial { get; set; }
        public int SecuencialUsuario { get; set; }
        public int SecuencialTareaActividad { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal EstaActivo { get; set; }
        public string Importancia { get; set; }
    
        public virtual Usuario usuario { get; set; }
        public virtual TareaActividadRealizada tareaActividadRealizada { get; set; }
    }
}
