//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentarioGeneral
    {
        public ComentarioGeneral()
        {
            this.usuarioLeeComentarioGeneral = new HashSet<UsuarioLeeComentarioGeneral>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialUsuario { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string TipoComentario { get; set; }
        public string Comentario { get; set; }
        public string Importancia { get; set; }
    
        public virtual Usuario usuario { get; set; }
        public virtual ICollection<UsuarioLeeComentarioGeneral> usuarioLeeComentarioGeneral { get; set; }
    }
}
