//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competencia
    {
        public Competencia()
        {
            this.colaboradorNivelCompetencia = new HashSet<ColaboradorNivelCompetencia>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialSubCategCompetencia { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActiva { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<ColaboradorNivelCompetencia> colaboradorNivelCompetencia { get; set; }
        public virtual SubCategoriaCompetencia subCategoriaCompetencia { get; set; }
    }
}
