//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoDesarrolloFunc
    {
        public int Secuencial { get; set; }
        public int SecuencialContratoCliente { get; set; }
        public int SecuencialFuncionalidad { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ContratoDesarrollo contratoDesarrollo { get; set; }
        public virtual Funcionalidad funcionalidad { get; set; }
    }
}
