//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoDesarrollo
    {
        public ContratoDesarrollo()
        {
            this.contratoDesarrolloFunc = new HashSet<ContratoDesarrolloFunc>();
        }
    
        public int SecuencialContratoCliente { get; set; }
    
        public virtual ContratoCliente contratoCliente { get; set; }
        public virtual ICollection<ContratoDesarrolloFunc> contratoDesarrolloFunc { get; set; }
    }
}
