//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoCliente
    {
        public ContratoCliente()
        {
            this.contratoAdjunto = new HashSet<ContratoAdjunto>();
            this.ticket_contratoCliente = new HashSet<Ticket_ContratoCliente>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialCliente { get; set; }
        public int SecuencialTipoContratoCliente { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual Cliente cliente { get; set; }
        public virtual ICollection<ContratoAdjunto> contratoAdjunto { get; set; }
        public virtual ContratoDesarrollo contratoDesarrollo { get; set; }
        public virtual ContratoMantenimiento contratoMantenimiento { get; set; }
        public virtual ICollection<Ticket_ContratoCliente> ticket_contratoCliente { get; set; }
        public virtual TipoContratoCliente tipoContratoCliente { get; set; }
    }
}
