//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorreoNoEnviado
    {
        public int Secuencial { get; set; }
        public string EmailEnvia { get; set; }
        public string Password { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Asunto { get; set; }
        public string Texto { get; set; }
        public string EmailDestinos { get; set; }
        public bool AdjuntarImagen { get; set; }
        public string Imagenes { get; set; }
        public string Adjuntos { get; set; }
        public string MensajeError { get; set; }
        public bool EstaActivo { get; set; }
    }
}
