//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionTicket
    {
        public CotizacionTicket()
        {
            this.ofertaCotizacionTicket = new HashSet<OfertaCotizacionTicket>();
        }
    
        public int Secuencial { get; set; }
        public Nullable<int> SecuencialColaborador { get; set; }
        public int SecuencialTicket { get; set; }
        public decimal PrecioFinal { get; set; }
        public decimal EstaCotizado { get; set; }
        public decimal CotizacionAceptada { get; set; }
        public decimal Renegociar { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual Colaborador colaborador { get; set; }
        public virtual ICollection<OfertaCotizacionTicket> ofertaCotizacionTicket { get; set; }
        public virtual Ticket ticket { get; set; }
    }
}
