//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentWorkItemView
    {
        public string CurrentWorkItemBK { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> Microsoft_VSTS_Common_BusinessValue { get; set; }
        public Nullable<double> Microsoft_VSTS_Scheduling_RemainingWork { get; set; }
        public Nullable<double> Microsoft_VSTS_Scheduling_OriginalEstimate { get; set; }
        public Nullable<double> Microsoft_VSTS_Scheduling_CompletedWork { get; set; }
        public Nullable<double> Microsoft_VSTS_Scheduling_StoryPoints { get; set; }
        public Nullable<double> Microsoft_VSTS_Scheduling_Effort { get; set; }
        public Nullable<int> WorkItemSK { get; set; }
        public string WorkItem { get; set; }
        public string PreviousState { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public Nullable<System.DateTime> System_RevisedDate { get; set; }
        public Nullable<System.DateTime> System_ChangedDate { get; set; }
        public Nullable<int> System_Id { get; set; }
        public string System_Title { get; set; }
        public string System_State { get; set; }
        public Nullable<int> System_Rev { get; set; }
        public string System_ChangedBy { get; set; }
        public string System_Reason { get; set; }
        public string System_AssignedTo { get; set; }
        public string System_WorkItemType { get; set; }
        public Nullable<System.DateTime> System_CreatedDate { get; set; }
        public string System_CreatedBy { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Common_ActivatedDate { get; set; }
        public string Microsoft_VSTS_Common_ActivatedBy { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Common_ResolvedDate { get; set; }
        public string Microsoft_VSTS_Common_ResolvedBy { get; set; }
        public string Microsoft_VSTS_Common_ResolvedReason { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Common_ClosedDate { get; set; }
        public string Microsoft_VSTS_Common_ClosedBy { get; set; }
        public Nullable<int> Microsoft_VSTS_Common_Priority { get; set; }
        public string Microsoft_VSTS_Common_Severity { get; set; }
        public Nullable<double> Microsoft_VSTS_Common_StackRank { get; set; }
        public string Microsoft_VSTS_Build_IntegrationBuild { get; set; }
        public string Microsoft_VSTS_Build_FoundIn { get; set; }
        public string Microsoft_VSTS_CodeReview_ClosedStatus { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_CodeReview_AcceptedDate { get; set; }
        public string Microsoft_VSTS_CodeReview_AcceptedBy { get; set; }
        public string Microsoft_VSTS_Common_Risk { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_TargetDate { get; set; }
        public string Microsoft_VSTS_Common_Rating { get; set; }
        public string Microsoft_VSTS_Common_Issue { get; set; }
        public string Microsoft_VSTS_Common_Activity { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_StartDate { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_FinishDate { get; set; }
        public string Microsoft_VSTS_TCM_AutomationStatus { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_DueDate { get; set; }
        public Nullable<double> Microsoft_VSTS_Common_BacklogPriority { get; set; }
        public string Microsoft_VSTS_CMMI_Blocked { get; set; }
        public string Sifizsoft_Identificador { get; set; }
        public string Sifizsoft_TipoTrabajo { get; set; }
        public string Sifizsoft_TiempoUtilizado { get; set; }
        public string Sifizsoft_TiempoFaltante { get; set; }
        public Nullable<System.DateTime> Sifizsoft_FechaEjecucion { get; set; }
        public string Tipo_TipoTrabajo { get; set; }
        public string Sifizsoft_Orden { get; set; }
        public string Sifizsoft_TiempoInterno { get; set; }
        public string Sifizsoft_TipoRecurso { get; set; }
        public string Sifizsoft_TipoTarea { get; set; }
        public string Sifizsoft_Criterio { get; set; }
        public string Sifizsoft_Exigibilidad { get; set; }
        public string Sifizsoft_Origen { get; set; }
        public string Sifizsoft_TiempoTarea { get; set; }
        public string Sifizsoft_TiempoRestante { get; set; }
        public Nullable<int> ProjectNodeSK { get; set; }
        public Nullable<System.Guid> ProjectNodeGUID { get; set; }
        public string ProjectNodeName { get; set; }
        public Nullable<int> ProjectNodeType { get; set; }
        public string ProjectNodeTypeName { get; set; }
        public Nullable<bool> ProjectIsDeleted { get; set; }
        public string ProjectPath { get; set; }
        public string AreaName { get; set; }
        public string AreaPath { get; set; }
        public string AreaGUID { get; set; }
        public string ParentAreaGUID { get; set; }
        public string AreaForwardingID { get; set; }
        public string AreaProjectGUID { get; set; }
        public string IterationName { get; set; }
        public string IterationPath { get; set; }
        public string IterationGUID { get; set; }
        public string ParentIterationGUID { get; set; }
        public string IterationForwardingID { get; set; }
        public string IterationProjectGUID { get; set; }
    }
}
