//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleGestionPermiso
    {
        public int Secuencial { get; set; }
        public string Detalle { get; set; }
        public int SecuencialGestionPermiso { get; set; }
    
        public virtual GestionPermiso gestionPermiso { get; set; }
    }
}
