//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEstimacionTicket
    {
        public int Secuencial { get; set; }
        public int SecuencialNivelColaborador { get; set; }
        public int SecuencialEstimacionTicket { get; set; }
        public string Detalle { get; set; }
        public Nullable<double> TiempoEstimacion { get; set; }
        public Nullable<double> TiempoDesarrollo { get; set; }
        public Nullable<double> TiempoPrueba { get; set; }
        public Nullable<int> SecuencialEntregableEstimacion { get; set; }
        public Nullable<double> TiempoQA { get; set; }
    
        public virtual NivelColaborador nivelColaborador { get; set; }
        public virtual EstimacionTicket estimacionTicket { get; set; }
        public virtual EntregableDetalleEstimacion entregableDetalleEstimacion { get; set; }
    }
}
