//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevopsAccesoProyectos
    {
        public int Id { get; set; }
        public string Organizacion { get; set; }
        public string NombreUsuario { get; set; }
        public string Usuario { get; set; }
        public string Modulo { get; set; }
        public bool EsTck { get; set; }
        public bool EsReq { get; set; }
        public bool EsDev { get; set; }
        public Nullable<int> SerieTicket { get; set; }
        public Nullable<int> SerieDesarrollo { get; set; }
        public Nullable<int> SerieRequerimiento { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> SecuencialTarea { get; set; }
    }
}
