//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiasDisponiblesVacaciones
    {
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> EstaActivo { get; set; }
        public Nullable<int> NumeroVerificador { get; set; }
        public int SecuencialColaborador { get; set; }
        public int DiasDisponibles { get; set; }
    
        public virtual Colaborador colaborador { get; set; }
    }
}
