//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimArea
    {
        public DimArea()
        {
            this.DimArea1 = new HashSet<DimArea>();
            this.DimArea11 = new HashSet<DimArea>();
            this.DimTestPlan = new HashSet<DimTestPlan>();
            this.DimTestResult = new HashSet<DimTestResult>();
            this.DimWorkItem = new HashSet<DimWorkItem>();
            this.FactTestResult = new HashSet<FactTestResult>();
        }
    
        public int AreaSK { get; set; }
        public string AreaName { get; set; }
        public string AreaGUID { get; set; }
        public string ParentAreaGUID { get; set; }
        public string AreaPath { get; set; }
        public Nullable<int> Depth { get; set; }
        public string ForwardingID { get; set; }
        public string ProjectGUID { get; set; }
        public Nullable<int> ParentAreaSK { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual ICollection<DimArea> DimArea1 { get; set; }
        public virtual DimArea DimArea2 { get; set; }
        public virtual ICollection<DimArea> DimArea11 { get; set; }
        public virtual DimArea DimArea3 { get; set; }
        public virtual ICollection<DimTestPlan> DimTestPlan { get; set; }
        public virtual ICollection<DimTestResult> DimTestResult { get; set; }
        public virtual ICollection<DimWorkItem> DimWorkItem { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
    }
}
