//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimAssembly
    {
        public DimAssembly()
        {
            this.FactBuildCoverage = new HashSet<FactBuildCoverage>();
            this.FactRunCoverage = new HashSet<FactRunCoverage>();
        }
    
        public int AssemblySK { get; set; }
        public string AssemblyBK { get; set; }
        public string Assembly { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
    
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual ICollection<FactBuildCoverage> FactBuildCoverage { get; set; }
        public virtual ICollection<FactRunCoverage> FactRunCoverage { get; set; }
    }
}
