//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimBuildPlatform
    {
        public DimBuildPlatform()
        {
            this.FactBuildCoverage = new HashSet<FactBuildCoverage>();
            this.FactBuildProject = new HashSet<FactBuildProject>();
            this.FactRunCoverage = new HashSet<FactRunCoverage>();
            this.FactTestResult = new HashSet<FactTestResult>();
        }
    
        public int BuildPlatformSK { get; set; }
        public string BuildPlatformName { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual ICollection<FactBuildCoverage> FactBuildCoverage { get; set; }
        public virtual ICollection<FactBuildProject> FactBuildProject { get; set; }
        public virtual ICollection<FactRunCoverage> FactRunCoverage { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
    }
}
