//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimBuildStatus
    {
        public DimBuildStatus()
        {
            this.FactBuildDetails = new HashSet<FactBuildDetails>();
        }
    
        public int BuildStatusSK { get; set; }
        public string BuildStatusName { get; set; }
        public Nullable<int> BuildStatusNameId { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual ICollection<FactBuildDetails> FactBuildDetails { get; set; }
    }
}
