//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimBuild
    {
        public DimBuild()
        {
            this.FactBuildChangeset = new HashSet<FactBuildChangeset>();
            this.FactBuildCoverage = new HashSet<FactBuildCoverage>();
            this.FactBuildDetails = new HashSet<FactBuildDetails>();
            this.FactBuildProject = new HashSet<FactBuildProject>();
            this.FactRunCoverage = new HashSet<FactRunCoverage>();
            this.FactTestResult = new HashSet<FactTestResult>();
        }
    
        public int BuildSK { get; set; }
        public string BuildBK { get; set; }
        public string BuildID { get; set; }
        public string BuildName { get; set; }
        public string BuildType { get; set; }
        public string BuildDefinitionName { get; set; }
        public string DropLocation { get; set; }
        public Nullable<System.DateTime> BuildStartTime { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
    
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual ICollection<FactBuildChangeset> FactBuildChangeset { get; set; }
        public virtual ICollection<FactBuildCoverage> FactBuildCoverage { get; set; }
        public virtual ICollection<FactBuildDetails> FactBuildDetails { get; set; }
        public virtual ICollection<FactBuildProject> FactBuildProject { get; set; }
        public virtual ICollection<FactRunCoverage> FactRunCoverage { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
    }
}
