//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimConfiguration
    {
        public DimConfiguration()
        {
            this.FactTestResult = new HashSet<FactTestResult>();
        }
    
        public int ConfigurationSK { get; set; }
        public string ConfigurationBK { get; set; }
        public Nullable<int> ConfigurationId { get; set; }
        public string Name { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
    
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
    }
}
