//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimChangeset
    {
        public DimChangeset()
        {
            this.FactBuildChangeset = new HashSet<FactBuildChangeset>();
            this.FactCodeChurn = new HashSet<FactCodeChurn>();
            this.FactWorkItemChangeset = new HashSet<FactWorkItemChangeset>();
        }
    
        public int ChangesetSK { get; set; }
        public string ChangesetBK { get; set; }
        public Nullable<int> ChangesetID { get; set; }
        public string ChangesetTitle { get; set; }
        public string PolicyOverrideComment { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public Nullable<int> CheckedInBySK { get; set; }
    
        public virtual DimPerson DimPerson { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual ICollection<FactBuildChangeset> FactBuildChangeset { get; set; }
        public virtual ICollection<FactCodeChurn> FactCodeChurn { get; set; }
        public virtual ICollection<FactWorkItemChangeset> FactWorkItemChangeset { get; set; }
    }
}
