//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimCodeElement
    {
        public DimCodeElement()
        {
            this.FactBuildCoverage = new HashSet<FactBuildCoverage>();
        }
    
        public int CodeElementSK { get; set; }
        public string CodeElementBK { get; set; }
        public string Namespace { get; set; }
        public string Class { get; set; }
        public string Name { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
    
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual ICollection<FactBuildCoverage> FactBuildCoverage { get; set; }
    }
}
