//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        public DimDate()
        {
            this.FactBuildCoverage = new HashSet<FactBuildCoverage>();
            this.FactBuildDetails = new HashSet<FactBuildDetails>();
            this.FactBuildProject = new HashSet<FactBuildProject>();
            this.FactCodeChurn = new HashSet<FactCodeChurn>();
            this.FactRunCoverage = new HashSet<FactRunCoverage>();
            this.FactTestResult = new HashSet<FactTestResult>();
            this.FactWorkItemHistory = new HashSet<FactWorkItemHistory>();
        }
    
        public System.DateTime DateSK { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string YearString { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public string MonthString { get; set; }
        public Nullable<int> MonthOfYear { get; set; }
        public Nullable<System.DateTime> Week { get; set; }
        public string WeekString { get; set; }
        public Nullable<int> WeekOfYear { get; set; }
        public string Date { get; set; }
        public Nullable<int> DayOfYear { get; set; }
        public Nullable<int> DayOfMonth { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual ICollection<FactBuildCoverage> FactBuildCoverage { get; set; }
        public virtual ICollection<FactBuildDetails> FactBuildDetails { get; set; }
        public virtual ICollection<FactBuildProject> FactBuildProject { get; set; }
        public virtual ICollection<FactCodeChurn> FactCodeChurn { get; set; }
        public virtual ICollection<FactRunCoverage> FactRunCoverage { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
        public virtual ICollection<FactWorkItemHistory> FactWorkItemHistory { get; set; }
    }
}
