//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimFile
    {
        public DimFile()
        {
            this.DimFile1 = new HashSet<DimFile>();
            this.FactBuildProject = new HashSet<FactBuildProject>();
            this.FactCodeChurn = new HashSet<FactCodeChurn>();
        }
    
        public int FileSK { get; set; }
        public string FileName { get; set; }
        public string FileBK { get; set; }
        public string FilePath { get; set; }
        public string FileExtension { get; set; }
        public Nullable<int> ParentFileSK { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
    
        public virtual ICollection<DimFile> DimFile1 { get; set; }
        public virtual DimFile DimFile2 { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual ICollection<FactBuildProject> FactBuildProject { get; set; }
        public virtual ICollection<FactCodeChurn> FactCodeChurn { get; set; }
    }
}
