//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimIteration
    {
        public DimIteration()
        {
            this.DimIteration1 = new HashSet<DimIteration>();
            this.DimIteration11 = new HashSet<DimIteration>();
            this.DimTestPlan = new HashSet<DimTestPlan>();
            this.DimTestResult = new HashSet<DimTestResult>();
            this.DimWorkItem = new HashSet<DimWorkItem>();
            this.FactTestResult = new HashSet<FactTestResult>();
        }
    
        public int IterationSK { get; set; }
        public string IterationName { get; set; }
        public string IterationGUID { get; set; }
        public string ParentIterationGUID { get; set; }
        public string IterationPath { get; set; }
        public Nullable<int> Depth { get; set; }
        public string ForwardingID { get; set; }
        public string ProjectGUID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> ParentIterationSK { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual ICollection<DimIteration> DimIteration1 { get; set; }
        public virtual DimIteration DimIteration2 { get; set; }
        public virtual ICollection<DimIteration> DimIteration11 { get; set; }
        public virtual DimIteration DimIteration3 { get; set; }
        public virtual ICollection<DimTestPlan> DimTestPlan { get; set; }
        public virtual ICollection<DimTestResult> DimTestResult { get; set; }
        public virtual ICollection<DimWorkItem> DimWorkItem { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
    }
}
