//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPerson
    {
        public DimPerson()
        {
            this.DimChangeset = new HashSet<DimChangeset>();
            this.DimTestPlan = new HashSet<DimTestPlan>();
            this.DimTestResult = new HashSet<DimTestResult>();
            this.DimTestResult1 = new HashSet<DimTestResult>();
            this.DimTestResultAttributes = new HashSet<DimTestResultAttributes>();
            this.DimTestResultAttributes1 = new HashSet<DimTestResultAttributes>();
            this.DimTestRun = new HashSet<DimTestRun>();
            this.DimWorkItem = new HashSet<DimWorkItem>();
            this.DimWorkItem1 = new HashSet<DimWorkItem>();
            this.DimWorkItem2 = new HashSet<DimWorkItem>();
            this.FactBuildDetails = new HashSet<FactBuildDetails>();
            this.FactWorkItemLinkHistory = new HashSet<FactWorkItemLinkHistory>();
            this.FactWorkItemLinkHistory1 = new HashSet<FactWorkItemLinkHistory>();
        }
    
        public int PersonSK { get; set; }
        public string Name { get; set; }
        public string SID { get; set; }
        public string Domain { get; set; }
        public string Alias { get; set; }
        public string Email { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual ICollection<DimChangeset> DimChangeset { get; set; }
        public virtual ICollection<DimTestPlan> DimTestPlan { get; set; }
        public virtual ICollection<DimTestResult> DimTestResult { get; set; }
        public virtual ICollection<DimTestResult> DimTestResult1 { get; set; }
        public virtual ICollection<DimTestResultAttributes> DimTestResultAttributes { get; set; }
        public virtual ICollection<DimTestResultAttributes> DimTestResultAttributes1 { get; set; }
        public virtual ICollection<DimTestRun> DimTestRun { get; set; }
        public virtual ICollection<DimWorkItem> DimWorkItem { get; set; }
        public virtual ICollection<DimWorkItem> DimWorkItem1 { get; set; }
        public virtual ICollection<DimWorkItem> DimWorkItem2 { get; set; }
        public virtual ICollection<FactBuildDetails> FactBuildDetails { get; set; }
        public virtual ICollection<FactWorkItemLinkHistory> FactWorkItemLinkHistory { get; set; }
        public virtual ICollection<FactWorkItemLinkHistory> FactWorkItemLinkHistory1 { get; set; }
    }
}
