//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimTestSuite
    {
        public DimTestSuite()
        {
            this.DimTestSuite1 = new HashSet<DimTestSuite>();
            this.FactTestResult = new HashSet<FactTestResult>();
        }
    
        public int TestSuiteSK { get; set; }
        public string TestSuiteBK { get; set; }
        public string ParentTestSuiteBK { get; set; }
        public Nullable<int> TestSuiteId { get; set; }
        public Nullable<int> ParentTestSuiteId { get; set; }
        public string SuiteName { get; set; }
        public string SuitePath { get; set; }
        public Nullable<byte> SuiteTypeId { get; set; }
        public string SuiteType { get; set; }
        public Nullable<int> RequirementId { get; set; }
        public Nullable<int> ParentSuiteSK { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectSK { get; set; }
    
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual ICollection<DimTestSuite> DimTestSuite1 { get; set; }
        public virtual DimTestSuite DimTestSuite2 { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
    }
}
