//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimTestResult
    {
        public DimTestResult()
        {
            this.FactTestResult = new HashSet<FactTestResult>();
            this.FactWorkItemTestResult = new HashSet<FactWorkItemTestResult>();
        }
    
        public int ResultSK { get; set; }
        public string ResultBK { get; set; }
        public string ResultId { get; set; }
        public string TestCaseId { get; set; }
        public string ExecutionId { get; set; }
        public string Test { get; set; }
        public string ComputerName { get; set; }
        public string Outcome { get; set; }
        public Nullable<byte> OutcomeId { get; set; }
        public string ReadinessState { get; set; }
        public Nullable<byte> ReadinessStateId { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<long> Duration { get; set; }
        public string ResolutionState { get; set; }
        public string FailureType { get; set; }
        public Nullable<byte> FailureTypeId { get; set; }
        public Nullable<byte> Priority { get; set; }
        public Nullable<int> TestCaseRevision { get; set; }
        public string TestTypeId { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public Nullable<int> OwnerSK { get; set; }
        public Nullable<int> ExecutedBySK { get; set; }
        public Nullable<int> AreaSK { get; set; }
        public Nullable<int> IterationSK { get; set; }
        public Nullable<int> TestResultAttributesSK { get; set; }
    
        public virtual DimArea DimArea { get; set; }
        public virtual DimIteration DimIteration { get; set; }
        public virtual DimPerson DimPerson { get; set; }
        public virtual DimPerson DimPerson1 { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual DimTestResultAttributes DimTestResultAttributes { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
        public virtual ICollection<FactWorkItemTestResult> FactWorkItemTestResult { get; set; }
    }
}
