//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimToolArtifactDisplayUrl
    {
        public int ToolArtifactDisplayUrlSK { get; set; }
        public string ToolArtifactDisplayUrlBK { get; set; }
        public string ToolType { get; set; }
        public string ToolArtifactDisplayUrl { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
    
        public virtual DimTeamProject DimTeamProject { get; set; }
    }
}
