//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimTeamProject
    {
        public DimTeamProject()
        {
            this.DimAssembly = new HashSet<DimAssembly>();
            this.DimBuild = new HashSet<DimBuild>();
            this.DimChangeset = new HashSet<DimChangeset>();
            this.DimCodeElement = new HashSet<DimCodeElement>();
            this.DimConfiguration = new HashSet<DimConfiguration>();
            this.DimFile = new HashSet<DimFile>();
            this.DimTeamProject1 = new HashSet<DimTeamProject>();
            this.DimTestPlan = new HashSet<DimTestPlan>();
            this.DimTestResult = new HashSet<DimTestResult>();
            this.DimTestResultAttributes = new HashSet<DimTestResultAttributes>();
            this.DimTestRun = new HashSet<DimTestRun>();
            this.DimTestSuite = new HashSet<DimTestSuite>();
            this.DimToolArtifactDisplayUrl = new HashSet<DimToolArtifactDisplayUrl>();
            this.DimWorkItem = new HashSet<DimWorkItem>();
            this.DimWorkItem1 = new HashSet<DimWorkItem>();
            this.DimWorkItemLinkType = new HashSet<DimWorkItemLinkType>();
            this.FactBuildChangeset = new HashSet<FactBuildChangeset>();
            this.FactBuildCoverage = new HashSet<FactBuildCoverage>();
            this.FactBuildDetails = new HashSet<FactBuildDetails>();
            this.FactBuildProject = new HashSet<FactBuildProject>();
            this.FactCodeChurn = new HashSet<FactCodeChurn>();
            this.FactCurrentWorkItem = new HashSet<FactCurrentWorkItem>();
            this.FactRunCoverage = new HashSet<FactRunCoverage>();
            this.FactTestResult = new HashSet<FactTestResult>();
            this.FactWorkItemChangeset = new HashSet<FactWorkItemChangeset>();
            this.FactWorkItemHistory = new HashSet<FactWorkItemHistory>();
            this.FactWorkItemLinkHistory = new HashSet<FactWorkItemLinkHistory>();
            this.FactWorkItemTestResult = new HashSet<FactWorkItemTestResult>();
        }
    
        public int ProjectNodeSK { get; set; }
        public System.Guid ProjectNodeGUID { get; set; }
        public string ProjectNodeName { get; set; }
        public Nullable<int> ProjectNodeType { get; set; }
        public string ProjectNodeTypeName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ReportPath { get; set; }
        public string ProjectPath { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<int> ParentNodeSK { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual ICollection<DimAssembly> DimAssembly { get; set; }
        public virtual ICollection<DimBuild> DimBuild { get; set; }
        public virtual ICollection<DimChangeset> DimChangeset { get; set; }
        public virtual ICollection<DimCodeElement> DimCodeElement { get; set; }
        public virtual ICollection<DimConfiguration> DimConfiguration { get; set; }
        public virtual ICollection<DimFile> DimFile { get; set; }
        public virtual ICollection<DimTeamProject> DimTeamProject1 { get; set; }
        public virtual DimTeamProject DimTeamProject2 { get; set; }
        public virtual ICollection<DimTestPlan> DimTestPlan { get; set; }
        public virtual ICollection<DimTestResult> DimTestResult { get; set; }
        public virtual ICollection<DimTestResultAttributes> DimTestResultAttributes { get; set; }
        public virtual ICollection<DimTestRun> DimTestRun { get; set; }
        public virtual ICollection<DimTestSuite> DimTestSuite { get; set; }
        public virtual ICollection<DimToolArtifactDisplayUrl> DimToolArtifactDisplayUrl { get; set; }
        public virtual ICollection<DimWorkItem> DimWorkItem { get; set; }
        public virtual ICollection<DimWorkItem> DimWorkItem1 { get; set; }
        public virtual ICollection<DimWorkItemLinkType> DimWorkItemLinkType { get; set; }
        public virtual ICollection<FactBuildChangeset> FactBuildChangeset { get; set; }
        public virtual ICollection<FactBuildCoverage> FactBuildCoverage { get; set; }
        public virtual ICollection<FactBuildDetails> FactBuildDetails { get; set; }
        public virtual ICollection<FactBuildProject> FactBuildProject { get; set; }
        public virtual ICollection<FactCodeChurn> FactCodeChurn { get; set; }
        public virtual ICollection<FactCurrentWorkItem> FactCurrentWorkItem { get; set; }
        public virtual ICollection<FactRunCoverage> FactRunCoverage { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
        public virtual ICollection<FactWorkItemChangeset> FactWorkItemChangeset { get; set; }
        public virtual ICollection<FactWorkItemHistory> FactWorkItemHistory { get; set; }
        public virtual ICollection<FactWorkItemLinkHistory> FactWorkItemLinkHistory { get; set; }
        public virtual ICollection<FactWorkItemTestResult> FactWorkItemTestResult { get; set; }
    }
}
