//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimToday
    {
        public int TodaySK { get; set; }
        public int Index { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string YearString { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public string MonthString { get; set; }
        public Nullable<int> MonthOfYear { get; set; }
        public Nullable<System.DateTime> Week { get; set; }
        public string WeekString { get; set; }
        public Nullable<int> WeekOfYear { get; set; }
        public string Date { get; set; }
        public Nullable<int> DayOfYear { get; set; }
        public Nullable<int> DayOfMonth { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    }
}
