//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimTestResultAttributes
    {
        public DimTestResultAttributes()
        {
            this.DimTestResult = new HashSet<DimTestResult>();
            this.FactTestResult = new HashSet<FactTestResult>();
        }
    
        public int ResultAttributeSK { get; set; }
        public string ResultAttributeBK { get; set; }
        public string Outcome { get; set; }
        public Nullable<byte> OutcomeId { get; set; }
        public string ReadinessState { get; set; }
        public Nullable<byte> ReadinessStateId { get; set; }
        public string ResolutionState { get; set; }
        public string FailureType { get; set; }
        public Nullable<byte> FailureTypeId { get; set; }
        public Nullable<byte> Priority { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public Nullable<int> OwnerSK { get; set; }
        public Nullable<int> ExecutedBySK { get; set; }
    
        public virtual DimPerson DimPerson { get; set; }
        public virtual DimPerson DimPerson1 { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual ICollection<DimTestResult> DimTestResult { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
    }
}
