//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimTestPlan
    {
        public DimTestPlan()
        {
            this.FactTestResult = new HashSet<FactTestResult>();
        }
    
        public int TestPlanSK { get; set; }
        public string TestPlanBK { get; set; }
        public Nullable<int> TestPlanId { get; set; }
        public string Name { get; set; }
        public Nullable<byte> StateId { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public Nullable<int> PlanOwnerSK { get; set; }
        public Nullable<int> AreaSK { get; set; }
        public Nullable<int> IterationSK { get; set; }
    
        public virtual DimArea DimArea { get; set; }
        public virtual DimIteration DimIteration { get; set; }
        public virtual DimPerson DimPerson { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
    }
}
