//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimTestRun
    {
        public DimTestRun()
        {
            this.FactRunCoverage = new HashSet<FactRunCoverage>();
            this.FactTestResult = new HashSet<FactTestResult>();
        }
    
        public int TestRunSK { get; set; }
        public string TestRunBK { get; set; }
        public Nullable<int> TestRunId { get; set; }
        public string Title { get; set; }
        public Nullable<byte> StateId { get; set; }
        public string State { get; set; }
        public Nullable<bool> IsAutomated { get; set; }
        public Nullable<bool> IsBuildVerificationRun { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public Nullable<int> RunOwnerSK { get; set; }
    
        public virtual DimPerson DimPerson { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual ICollection<FactRunCoverage> FactRunCoverage { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
    }
}
