//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimWorkItemLinkType
    {
        public DimWorkItemLinkType()
        {
            this.FactWorkItemLinkHistory = new HashSet<FactWorkItemLinkHistory>();
        }
    
        public int WorkItemLinkTypeSK { get; set; }
        public string WorkItemLinkTypeBK { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public int LinkID { get; set; }
        public string ReferenceName { get; set; }
        public string LinkName { get; set; }
        public Nullable<int> Rules { get; set; }
        public Nullable<bool> IsDenyDelete { get; set; }
        public Nullable<bool> IsDenyEdit { get; set; }
        public Nullable<bool> IsDirectional { get; set; }
        public Nullable<bool> IsNonCircular { get; set; }
        public Nullable<bool> IsSingleTarget { get; set; }
        public Nullable<bool> IsTree { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual ICollection<FactWorkItemLinkHistory> FactWorkItemLinkHistory { get; set; }
    }
}
