//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimWorkItem
    {
        public DimWorkItem()
        {
            this.FactCurrentWorkItem = new HashSet<FactCurrentWorkItem>();
            this.FactTestResult = new HashSet<FactTestResult>();
            this.FactWorkItemHistory = new HashSet<FactWorkItemHistory>();
        }
    
        public int WorkItemSK { get; set; }
        public string WorkItemBK { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public Nullable<int> TeamProjectSK { get; set; }
        public Nullable<int> AreaSK { get; set; }
        public Nullable<int> IterationSK { get; set; }
        public Nullable<int> System_AssignedTo__PersonSK { get; set; }
        public Nullable<int> System_ChangedBy__PersonSK { get; set; }
        public Nullable<int> System_CreatedBy__PersonSK { get; set; }
        public string PreviousState { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public string System_WorkItemType { get; set; }
        public Nullable<int> System_Id { get; set; }
        public string System_Title { get; set; }
        public Nullable<System.DateTime> System_RevisedDate { get; set; }
        public Nullable<System.DateTime> System_ChangedDate { get; set; }
        public string System_State { get; set; }
        public Nullable<int> System_Rev { get; set; }
        public string System_Reason { get; set; }
        public Nullable<System.DateTime> System_CreatedDate { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Common_ActivatedDate { get; set; }
        public Nullable<int> Microsoft_VSTS_Common_ActivatedBy__PersonSK { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Common_ResolvedDate { get; set; }
        public Nullable<int> Microsoft_VSTS_Common_ResolvedBy__PersonSK { get; set; }
        public string Microsoft_VSTS_Common_ResolvedReason { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Common_ClosedDate { get; set; }
        public Nullable<int> Microsoft_VSTS_Common_ClosedBy__PersonSK { get; set; }
        public Nullable<int> Microsoft_VSTS_Common_Priority { get; set; }
        public string Microsoft_VSTS_Common_Severity { get; set; }
        public Nullable<double> Microsoft_VSTS_Common_StackRank { get; set; }
        public string Microsoft_VSTS_Build_IntegrationBuild { get; set; }
        public string Microsoft_VSTS_Build_FoundIn { get; set; }
        public string Microsoft_VSTS_CodeReview_ClosedStatus { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_CodeReview_AcceptedDate { get; set; }
        public Nullable<int> Microsoft_VSTS_CodeReview_AcceptedBy__PersonSK { get; set; }
        public string Microsoft_VSTS_Common_Risk { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_TargetDate { get; set; }
        public string Microsoft_VSTS_Common_Rating { get; set; }
        public string Microsoft_VSTS_Common_Issue { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_StartDate { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_FinishDate { get; set; }
        public string Microsoft_VSTS_TCM_AutomationStatus { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_DueDate { get; set; }
        public Nullable<double> Microsoft_VSTS_Common_BacklogPriority { get; set; }
        public string Microsoft_VSTS_CMMI_Blocked { get; set; }
        public string Sifizsoft_Identificador { get; set; }
        public string Sifizsoft_TipoTrabajo { get; set; }
        public string Microsoft_VSTS_Common_Activity { get; set; }
        public string Sifizsoft_TiempoUtilizado { get; set; }
        public string Sifizsoft_TiempoFaltante { get; set; }
        public Nullable<System.DateTime> Sifizsoft_FechaEjecucion { get; set; }
        public string Tipo_TipoTrabajo { get; set; }
        public string Sifizsoft_Orden { get; set; }
        public string Sifizsoft_TiempoInterno { get; set; }
        public string Sifizsoft_TipoRecurso { get; set; }
        public string Sifizsoft_TipoTarea { get; set; }
        public string Sifizsoft_Criterio { get; set; }
        public string Sifizsoft_Exigibilidad { get; set; }
        public string Sifizsoft_Origen { get; set; }
        public string Sifizsoft_TiempoTarea { get; set; }
        public string Sifizsoft_TiempoRestante { get; set; }
    
        public virtual C_DimTestCaseOverlay C_DimTestCaseOverlay { get; set; }
        public virtual DimArea DimArea { get; set; }
        public virtual DimIteration DimIteration { get; set; }
        public virtual DimPerson DimPerson { get; set; }
        public virtual DimPerson DimPerson1 { get; set; }
        public virtual DimPerson DimPerson2 { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual DimTeamProject DimTeamProject1 { get; set; }
        public virtual ICollection<FactCurrentWorkItem> FactCurrentWorkItem { get; set; }
        public virtual ICollection<FactTestResult> FactTestResult { get; set; }
        public virtual ICollection<FactWorkItemHistory> FactWorkItemHistory { get; set; }
    }
}
