//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimWorkItemCategory
    {
        public DimWorkItemCategory()
        {
            this.FactWorkItemToCategory = new HashSet<FactWorkItemToCategory>();
        }
    
        public int WorkItemCategorySK { get; set; }
        public string WorkItemCategoryBK { get; set; }
        public string ReferenceName { get; set; }
        public string Name { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual ICollection<FactWorkItemToCategory> FactWorkItemToCategory { get; set; }
    }
}
