//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntregableMotivoTrabajo
    {
        public EntregableMotivoTrabajo()
        {
            this.tarea = new HashSet<Tarea>();
            this.Acta = new HashSet<Acta>();
            this.ENTREGABLETICKET = new HashSet<EntregableTicket>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialMotivoTrabajo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int Avance { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
        public Nullable<int> SecuencialColaborador { get; set; }
        public Nullable<System.DateTime> FechaProduccion { get; set; }
        public Nullable<int> DiasGarantia { get; set; }
    
        public virtual MotivoTrabajo motivoTrabajo { get; set; }
        public virtual ICollection<Tarea> tarea { get; set; }
        public virtual ICollection<Acta> Acta { get; set; }
        public virtual Colaborador colaborador { get; set; }
        public virtual ICollection<EntregableTicket> ENTREGABLETICKET { get; set; }
    }
}
