//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntregableDetalleEstimacion
    {
        public EntregableDetalleEstimacion()
        {
            this.detalleEstimacionTicket = new HashSet<DetalleEstimacionTicket>();
        }
    
        public int Secuencial { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<DetalleEstimacionTicket> detalleEstimacionTicket { get; set; }
    }
}
