//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoTicket
    {
        public EstadoTicket()
        {
            this.ticket = new HashSet<Ticket>();
            this.flujoEstadoTicket = new HashSet<FlujoEstadoTicket>();
            this.flujoEstadoTicket1 = new HashSet<FlujoEstadoTicket>();
            this.ticketHistorico = new HashSet<TicketHistorico>();
            this.BotonEstadoTicket = new HashSet<BotonEstadoTicket>();
            this.ESTADOTICKETPROXIMAACTIVIDAD = new HashSet<EstadoTicketProximaActividad>();
        }
    
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<Ticket> ticket { get; set; }
        public virtual ICollection<FlujoEstadoTicket> flujoEstadoTicket { get; set; }
        public virtual ICollection<FlujoEstadoTicket> flujoEstadoTicket1 { get; set; }
        public virtual ICollection<TicketHistorico> ticketHistorico { get; set; }
        public virtual ICollection<BotonEstadoTicket> BotonEstadoTicket { get; set; }
        public virtual ICollection<EstadoTicketProximaActividad> ESTADOTICKETPROXIMAACTIVIDAD { get; set; }
    }
}
