//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoPermiso
    {
        public EstadoPermiso()
        {
            this.permiso = new HashSet<Permiso>();
            this.gestionPermiso = new HashSet<GestionPermiso>();
            this.gestionPermiso1 = new HashSet<GestionPermiso>();
        }
    
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<Permiso> permiso { get; set; }
        public virtual ICollection<GestionPermiso> gestionPermiso { get; set; }
        public virtual ICollection<GestionPermiso> gestionPermiso1 { get; set; }
    }
}
