//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoTicketProximaActividad
    {
        public int Secuencial { get; set; }
        public int SecuencialEstadoTicket { get; set; }
        public int SecuencialProximaActividad { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
        public Nullable<decimal> TieneGauge { get; set; }
        public Nullable<int> Minimo { get; set; }
        public Nullable<int> Maximo { get; set; }
        public Nullable<int> ValorMedio { get; set; }
        public Nullable<int> ValorAlto { get; set; }
    
        public virtual EstadoTicket estadoTicket { get; set; }
        public virtual ProximaActividad proximaActividad { get; set; }
    }
}
