//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimacionTicket
    {
        public EstimacionTicket()
        {
            this.detalleEstimacionTicket = new HashSet<DetalleEstimacionTicket>();
            this.ITEMESPECIAL = new HashSet<ItemEspecial>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialTicket { get; set; }
        public int SecuencialColaborador { get; set; }
        public string EntregablesAdicionales { get; set; }
        public string InformacionComplementaria { get; set; }
        public decimal EstimacionTerminada { get; set; }
        public decimal EstaActiva { get; set; }
        public decimal FactorTiempo { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public decimal NumeroHoras { get; set; }
        public Nullable<bool> RequerimientoNuevo { get; set; }
        public Nullable<int> TiempoInicial { get; set; }
        public Nullable<int> TiempoPegado { get; set; }
    
        public virtual Colaborador colaborador { get; set; }
        public virtual ICollection<DetalleEstimacionTicket> detalleEstimacionTicket { get; set; }
        public virtual Ticket ticket { get; set; }
        public virtual ICollection<ItemEspecial> ITEMESPECIAL { get; set; }
    }
}
