//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtapasProyectoCliente
    {
        public EtapasProyectoCliente()
        {
            this.subEtapasProyectosCliente = new HashSet<SubEtapasProyectosCliente>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialEtapaProyecto { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public decimal EstaActivo { get; set; }
        public Nullable<int> SecuencialClienteAuxiliar { get; set; }
        public string Detalle { get; set; }
        public Nullable<decimal> Seleccionado { get; set; }
        public Nullable<double> Porciento { get; set; }
    
        public virtual ClienteAuxiliar clienteAuxiliar { get; set; }
        public virtual ICollection<SubEtapasProyectosCliente> subEtapasProyectosCliente { get; set; }
    }
}
