//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactBuildChangeset
    {
        public int BuildChangesetSK { get; set; }
        public string BuildChangesetBK { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectSK { get; set; }
        public Nullable<int> BuildSK { get; set; }
        public Nullable<int> ChangesetSK { get; set; }
    
        public virtual DimBuild DimBuild { get; set; }
        public virtual DimChangeset DimChangeset { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
    }
}
