//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactWorkItemChangeset
    {
        public string WorkItemChangesetBK { get; set; }
        public int WorkItemID { get; set; }
        public int ChangesetSK { get; set; }
        public int TeamProjectCollectionSK { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> RemovedDateTime { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual DimChangeset DimChangeset { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
    }
}
