//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactBuildProject
    {
        public int BuildProjectSK { get; set; }
        public string BuildProjectBK { get; set; }
        public Nullable<int> CompileErrors { get; set; }
        public Nullable<int> CompileWarnings { get; set; }
        public Nullable<int> StaticAnalysisErrors { get; set; }
        public Nullable<int> StaticAnalysisWarnings { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<System.DateTime> DateSK { get; set; }
        public Nullable<int> TeamProjectSK { get; set; }
        public Nullable<int> BuildSK { get; set; }
        public Nullable<int> BuildPlatformSK { get; set; }
        public Nullable<int> BuildFlavorSK { get; set; }
        public Nullable<int> SourceProjectSK { get; set; }
    
        public virtual DimBuild DimBuild { get; set; }
        public virtual DimBuildFlavor DimBuildFlavor { get; set; }
        public virtual DimBuildPlatform DimBuildPlatform { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimFile DimFile { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
    }
}
