//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactCurrentWorkItem
    {
        public string CurrentWorkItemBK { get; set; }
        public int WorkItemSK { get; set; }
        public int TeamProjectSK { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> Microsoft_VSTS_Common_BusinessValue { get; set; }
        public Nullable<double> Microsoft_VSTS_Scheduling_OriginalEstimate { get; set; }
        public Nullable<double> Microsoft_VSTS_Scheduling_CompletedWork { get; set; }
        public Nullable<double> Microsoft_VSTS_Scheduling_StoryPoints { get; set; }
        public Nullable<double> Microsoft_VSTS_Scheduling_Effort { get; set; }
        public Nullable<double> Microsoft_VSTS_Scheduling_RemainingWork { get; set; }
    
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual DimWorkItem DimWorkItem { get; set; }
    }
}
