//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactTestResult
    {
        public int TestResultSK { get; set; }
        public string TestResultBK { get; set; }
        public Nullable<int> DateResultRecordCount { get; set; }
        public Nullable<int> BuildResultRecordCount { get; set; }
        public Nullable<int> PointRecordCount { get; set; }
        public Nullable<int> ResultCount { get; set; }
        public Nullable<int> ResultTransitionCount { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public Nullable<int> PointId { get; set; }
        public Nullable<int> ChangeNumber { get; set; }
        public Nullable<int> TestCaseId { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectSK { get; set; }
        public Nullable<int> ResultSK { get; set; }
        public Nullable<int> TestResultAttributesSK { get; set; }
        public Nullable<int> BuildSK { get; set; }
        public Nullable<int> TestRunSK { get; set; }
        public Nullable<int> AreaSK { get; set; }
        public Nullable<int> IterationSK { get; set; }
        public Nullable<System.DateTime> DateSK { get; set; }
        public Nullable<int> TestPlanSK { get; set; }
        public Nullable<int> BuildPlatformSK { get; set; }
        public Nullable<int> BuildFlavorSK { get; set; }
        public Nullable<int> ConfigurationSK { get; set; }
        public Nullable<int> TestSuiteSK { get; set; }
        public Nullable<int> RelatedWorkItemSK { get; set; }
    
        public virtual DimArea DimArea { get; set; }
        public virtual DimBuild DimBuild { get; set; }
        public virtual DimBuildFlavor DimBuildFlavor { get; set; }
        public virtual DimBuildPlatform DimBuildPlatform { get; set; }
        public virtual DimConfiguration DimConfiguration { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimIteration DimIteration { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual DimTestPlan DimTestPlan { get; set; }
        public virtual DimTestResult DimTestResult { get; set; }
        public virtual DimTestResultAttributes DimTestResultAttributes { get; set; }
        public virtual DimTestRun DimTestRun { get; set; }
        public virtual DimTestSuite DimTestSuite { get; set; }
        public virtual DimWorkItem DimWorkItem { get; set; }
    }
}
