//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactBuildCoverage
    {
        public int BuildCoverageSK { get; set; }
        public string BuildCoverageBK { get; set; }
        public Nullable<int> LinesCovered { get; set; }
        public Nullable<int> LinesNotCovered { get; set; }
        public Nullable<int> LinesPartiallyCovered { get; set; }
        public Nullable<int> BlocksCovered { get; set; }
        public Nullable<int> BlocksNotCovered { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectSK { get; set; }
        public Nullable<int> BuildSK { get; set; }
        public Nullable<int> AssemblySK { get; set; }
        public Nullable<int> CodeElementSK { get; set; }
        public Nullable<System.DateTime> DateSK { get; set; }
        public Nullable<int> BuildPlatformSK { get; set; }
        public Nullable<int> BuildFlavorSK { get; set; }
    
        public virtual DimAssembly DimAssembly { get; set; }
        public virtual DimBuild DimBuild { get; set; }
        public virtual DimBuildFlavor DimBuildFlavor { get; set; }
        public virtual DimBuildPlatform DimBuildPlatform { get; set; }
        public virtual DimCodeElement DimCodeElement { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
    }
}
