//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactCodeChurn
    {
        public int CodeChurnSK { get; set; }
        public string CodeChurnBK { get; set; }
        public Nullable<int> LinesAdded { get; set; }
        public Nullable<int> LinesModified { get; set; }
        public Nullable<int> LinesDeleted { get; set; }
        public Nullable<int> NetLinesAdded { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectSK { get; set; }
        public Nullable<int> ChangesetSK { get; set; }
        public Nullable<int> FilenameSK { get; set; }
        public Nullable<System.DateTime> DateSK { get; set; }
    
        public virtual DimChangeset DimChangeset { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimFile DimFile { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
    }
}
