//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactWorkItemLinkHistory
    {
        public int WorkItemLinkHistorySK { get; set; }
        public string WorkItemLinkHistoryBK { get; set; }
        public Nullable<int> WorkItemLinkTypeSK { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public Nullable<int> CreatedByPersonSK { get; set; }
        public Nullable<int> RemovedByPersonSK { get; set; }
        public Nullable<int> SourceWorkItemID { get; set; }
        public Nullable<int> TargetWorkItemID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> RemovedDate { get; set; }
        public string Comment { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual DimPerson DimPerson { get; set; }
        public virtual DimPerson DimPerson1 { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
        public virtual DimWorkItemLinkType DimWorkItemLinkType { get; set; }
    }
}
