//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactBuildDetails
    {
        public int BuildDetailsSK { get; set; }
        public string BuildDetailsBK { get; set; }
        public Nullable<long> BuildDuration { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectSK { get; set; }
        public Nullable<int> BuildSK { get; set; }
        public Nullable<System.DateTime> DateSK { get; set; }
        public Nullable<int> BuildQualitySK { get; set; }
        public Nullable<int> BuildStatusSK { get; set; }
        public Nullable<int> LastUpdatedBySK { get; set; }
    
        public virtual DimBuild DimBuild { get; set; }
        public virtual DimBuildQuality DimBuildQuality { get; set; }
        public virtual DimBuildStatus DimBuildStatus { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimPerson DimPerson { get; set; }
        public virtual DimTeamProject DimTeamProject { get; set; }
    }
}
