//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactWorkItemToCategory
    {
        public int WorkItemCategorySK { get; set; }
        public int TeamProjectSK { get; set; }
        public string WorkItemTypeName { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    
        public virtual DimWorkItemCategory DimWorkItemCategory { get; set; }
    }
}
