//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBSLogError
    {
        public int Secuencial { get; set; }
        public int SecuencialFbsLogEquipo { get; set; }
        public string Cliente { get; set; }
        public string Empresa { get; set; }
        public string Oficina { get; set; }
        public System.DateTime FechaMaquina { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public string Usuario { get; set; }
        public string RutaMenu { get; set; }
        public string NombreFichero { get; set; }
        public string MensajeDisculpa { get; set; }
        public string MensajeError { get; set; }
        public string NombreModulo { get; set; }
        public string NombreClase { get; set; }
        public string NombreMetodo { get; set; }
        public decimal Linea { get; set; }
        public decimal Columna { get; set; }
        public string StackTrace { get; set; }
        public string CodigoError { get; set; }
        public string MensajeExcepcion { get; set; }
        public string Publicacion { get; set; }
        public string MaquinaPublicacion { get; set; }
        public string Servidor { get; set; }
        public string BaseDatos { get; set; }
        public string TipoError { get; set; }
    
        public virtual FBSLogEquipo fbsLogEquipo { get; set; }
    }
}
