//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBSLogEquipo
    {
        public FBSLogEquipo()
        {
            this.fbsLogError = new HashSet<FBSLogError>();
        }
    
        public int Secuencial { get; set; }
        public string Ip { get; set; }
        public string Nombre { get; set; }
        public string Mac { get; set; }
    
        public virtual ICollection<FBSLogError> fbsLogError { get; set; }
    }
}
