//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormalizacionOfertas
    {
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public int SecuencialOferta { get; set; }
        public Nullable<int> SecuencialEstadoOferta { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<System.DateTime> FechaAprobacionOferta { get; set; }
        public string NoContrato { get; set; }
        public Nullable<decimal> Formalizado { get; set; }
        public string SeguimientoFormalizacion { get; set; }
        public Nullable<double> ValorAnticipo { get; set; }
        public Nullable<System.DateTime> FechaOrdenFacturacionAnticipo { get; set; }
        public string NoOrdenFacturacionAnticipo { get; set; }
        public Nullable<double> ValorEntrega { get; set; }
        public string NoOrdenFacturacionEntrega { get; set; }
        public Nullable<double> ValorFacturacionProgramada { get; set; }
        public string NoOrdenFacturacionProgramada { get; set; }
        public Nullable<decimal> EstaActivo { get; set; }
    
        public virtual EstadoOferta estadoOferta { get; set; }
        public virtual OfertaOferta ofertaOferta { get; set; }
    }
}
