//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionalidad
    {
        public Funcionalidad()
        {
            this.contratoDesarrolloFunc = new HashSet<ContratoDesarrolloFunc>();
            this.ticketFuncionalidad = new HashSet<TicketFuncionalidad>();
            this.FuncionalidadCliente = new HashSet<FuncionalidadCliente>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialModulo { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActiva { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<ContratoDesarrolloFunc> contratoDesarrolloFunc { get; set; }
        public virtual ICollection<TicketFuncionalidad> ticketFuncionalidad { get; set; }
        public virtual ICollection<FuncionalidadCliente> FuncionalidadCliente { get; set; }
        public virtual Modulo modulo { get; set; }
    }
}
