//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionPermiso
    {
        public GestionPermiso()
        {
            this.detalleGestionPermiso = new HashSet<DetalleGestionPermiso>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialPermiso { get; set; }
        public int SecuencialEstadoPermisoInicial { get; set; }
        public int SecuencialEstadoPermisoFinal { get; set; }
        public int SecuencialUsuario { get; set; }
        public System.DateTime FechaOperacion { get; set; }
    
        public virtual ICollection<DetalleGestionPermiso> detalleGestionPermiso { get; set; }
        public virtual EstadoPermiso estadoPermiso { get; set; }
        public virtual EstadoPermiso estadoPermiso1 { get; set; }
        public virtual Permiso permiso { get; set; }
        public virtual Usuario usuario { get; set; }
    }
}
