//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestion_SolicitudTarea
    {
        public Gestion_SolicitudTarea()
        {
            this.tarea = new HashSet<Tarea>();
        }
    
        public int SecuencialSolicitudTarea { get; set; }
        public int SecuencialUsuario { get; set; }
        public System.DateTime HoraGestion { get; set; }
    
        public virtual Usuario usuario { get; set; }
        public virtual SolicitudTarea solicitudTarea { get; set; }
        public virtual ICollection<Tarea> tarea { get; set; }
    }
}
