//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoTareaEstado
    {
        public int Secuencial { get; set; }
        public int SecuencialEstadoTarea { get; set; }
        public int SecuencialTarea { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public int SecuencialUsuario { get; set; }
    
        public virtual Usuario usuario { get; set; }
        public virtual EstadoTarea estadoTarea { get; set; }
        public virtual Tarea tarea { get; set; }
    }
}
