//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoInformacionTicket
    {
        public HistoricoInformacionTicket()
        {
            this.historicoAdjunto = new HashSet<HistoricoAdjunto>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialTicketHistorico { get; set; }
        public int VersionTicketHistorico { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Texto { get; set; }
    
        public virtual ICollection<HistoricoAdjunto> historicoAdjunto { get; set; }
        public virtual TicketHistorico ticketHistorico { get; set; }
    }
}
