//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorasConsumidas
    {
        public int Secuencial { get; set; }
        public int SecuencialContratoCliente { get; set; }
        public decimal Mes { get; set; }
        public decimal Anio { get; set; }
        public int HorasConsumidas1 { get; set; }
    
        public virtual ContratoMantenimiento contratoMantenimiento { get; set; }
    }
}
