//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencias
    {
        public int Secuencial { get; set; }
        public int SecuencialCliente { get; set; }
        public int SecuencialModulo { get; set; }
        public string Incidente { get; set; }
        public string Adjunto { get; set; }
        public string Acciones { get; set; }
    
        public virtual Cliente cliente { get; set; }
        public virtual Modulo modulo { get; set; }
    }
}
