//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoTickets
    {
        public int Id { get; set; }
        public string Cliente { get; set; }
        public string Prioridad { get; set; }
        public string Tipo { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<int> NumeroReprocesos { get; set; }
        public string EstimadoPor { get; set; }
        public string AsignadoA { get; set; }
        public string ProbadoPor { get; set; }
        public string EntregadoPor { get; set; }
        public Nullable<System.DateTime> HorasEstimadas { get; set; }
        public Nullable<System.DateTime> HorasAsignadas { get; set; }
        public Nullable<System.DateTime> HorasEmpleadas { get; set; }
        public Nullable<System.DateTime> HorasPrueba { get; set; }
        public Nullable<System.DateTime> HorasEntrega { get; set; }
        public string Estado { get; set; }
        public string AplicaA { get; set; }
    }
}
