//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemEspecialEstimacion
    {
        public int Secuencial { get; set; }
        public int SecuencialItemEspecialCatalogo { get; set; }
        public int SecuencialEstimacion { get; set; }
        public int SecuencialNivelColaborador { get; set; }
        public int TiempoEstimacion { get; set; }
    
        public virtual EstimacionTicket ESTIMACIONTICKET { get; set; }
        public virtual ItemEspecialCatalogo ITEMESPECIALCATALOGO { get; set; }
        public virtual NivelColaborador NIVELCOLABORADOR { get; set; }
    }
}
