//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemEspecial
    {
        public int Secuencial { get; set; }
        public string Descripcion { get; set; }
        public int TiempoEstimacion { get; set; }
        public int SecuencialEstimacion { get; set; }
        public int SecuencialTipoRecurso { get; set; }
    
        public virtual EstimacionTicket ESTIMACIONTICKET { get; set; }
        public virtual TipoRecurso TIPORECURSO { get; set; }
    }
}
