//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int Secuencial { get; set; }
        public int SecuencialUsuarioEnvia { get; set; }
        public int SecuencialUsuarioRecibe { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Texto { get; set; }
        public bool Enviado { get; set; }
    
        public virtual Usuario usuario { get; set; }
        public virtual Usuario usuario1 { get; set; }
    }
}
