//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SifizPlanningEntidades : DbContext
    {
        public SifizPlanningEntidades()
            : base("name=SifizPlanningEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioRol> UsuarioRol { get; set; }
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Colaborador> Colaborador { get; set; }
        public virtual DbSet<Colaborador_JefeInmediato> Colaborador_JefeInmediato { get; set; }
        public virtual DbSet<DiaInactivo> DiaInactivo { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<EstadoTarea> EstadoTarea { get; set; }
        public virtual DbSet<FotoColaborador> FotoColaborador { get; set; }
        public virtual DbSet<LugarTarea> LugarTarea { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<Tarea_Coordinador> Tarea_Coordinador { get; set; }
        public virtual DbSet<ColaboradorEspecialidad> ColaboradorEspecialidad { get; set; }
        public virtual DbSet<HistoricoTareaEstado> HistoricoTareaEstado { get; set; }
        public virtual DbSet<Tarea_TareaRelacionada> Tarea_TareaRelacionada { get; set; }
        public virtual DbSet<CampoCatalogo> CampoCatalogo { get; set; }
        public virtual DbSet<CampoCatalogo_TablaCatalogo> CampoCatalogo_TablaCatalogo { get; set; }
        public virtual DbSet<TablaCatalogo> TablaCatalogo { get; set; }
        public virtual DbSet<TipoCampo> TipoCampo { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<AdjuntoTicket> AdjuntoTicket { get; set; }
        public virtual DbSet<CategoriaTicket> CategoriaTicket { get; set; }
        public virtual DbSet<ContratoAdjunto> ContratoAdjunto { get; set; }
        public virtual DbSet<ContratoCliente> ContratoCliente { get; set; }
        public virtual DbSet<ContratoDesarrollo> ContratoDesarrollo { get; set; }
        public virtual DbSet<ContratoDesarrolloFunc> ContratoDesarrolloFunc { get; set; }
        public virtual DbSet<ContratoMantenimiento> ContratoMantenimiento { get; set; }
        public virtual DbSet<EstadoTicket> EstadoTicket { get; set; }
        public virtual DbSet<FlujoEstadoTicket> FlujoEstadoTicket { get; set; }
        public virtual DbSet<Funcionalidad> Funcionalidad { get; set; }
        public virtual DbSet<HorasConsumidas> HorasConsumidas { get; set; }
        public virtual DbSet<NivelColaborador> NivelColaborador { get; set; }
        public virtual DbSet<Persona_Cliente> Persona_Cliente { get; set; }
        public virtual DbSet<PrioridadTicket> PrioridadTicket { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Ticket_ContratoCliente> Ticket_ContratoCliente { get; set; }
        public virtual DbSet<TicketHistorico> TicketHistorico { get; set; }
        public virtual DbSet<TipoContratoCliente> TipoContratoCliente { get; set; }
        public virtual DbSet<RolSysMenu> RolSysMenu { get; set; }
        public virtual DbSet<SysMenu> SysMenu { get; set; }
        public virtual DbSet<CategoriaTicketTipoContrClient> CategoriaTicketTipoContrClient { get; set; }
        public virtual DbSet<TicketFuncionalidad> TicketFuncionalidad { get; set; }
        public virtual DbSet<GrupoEmail> GrupoEmail { get; set; }
        public virtual DbSet<PersonaGrupoEmail> PersonaGrupoEmail { get; set; }
        public virtual DbSet<TicketTarea> TicketTarea { get; set; }
        public virtual DbSet<BotonEstadoTicket> BotonEstadoTicket { get; set; }
        public virtual DbSet<DetalleEstimacionTicket> DetalleEstimacionTicket { get; set; }
        public virtual DbSet<EstimacionTicket> EstimacionTicket { get; set; }
        public virtual DbSet<CotizacionTicket> CotizacionTicket { get; set; }
        public virtual DbSet<OfertaCotizacionTicket> OfertaCotizacionTicket { get; set; }
        public virtual DbSet<ActividadRealizada> ActividadRealizada { get; set; }
        public virtual DbSet<TareaActividadRealizada> TareaActividadRealizada { get; set; }
        public virtual DbSet<Gestion_SolicitudTarea> Gestion_SolicitudTarea { get; set; }
        public virtual DbSet<SolicitudTarea> SolicitudTarea { get; set; }
        public virtual DbSet<ComentarioTarea> ComentarioTarea { get; set; }
        public virtual DbSet<Renegociacion> Renegociacion { get; set; }
        public virtual DbSet<EntregableMotivoTrabajo> EntregableMotivoTrabajo { get; set; }
        public virtual DbSet<MotivoTrabajo> MotivoTrabajo { get; set; }
        public virtual DbSet<TipoMotivoTrabajo> TipoMotivoTrabajo { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<DetalleGestionPermiso> DetalleGestionPermiso { get; set; }
        public virtual DbSet<EstadoPermiso> EstadoPermiso { get; set; }
        public virtual DbSet<GestionPermiso> GestionPermiso { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<TipoPermiso> TipoPermiso { get; set; }
        public virtual DbSet<Vacaciones> Vacaciones { get; set; }
        public virtual DbSet<ColaboradorIncidencia> ColaboradorIncidencia { get; set; }
        public virtual DbSet<ImplicacionError> ImplicacionError { get; set; }
        public virtual DbSet<TipoError> TipoError { get; set; }
        public virtual DbSet<EstadoEntregable> EstadoEntregable { get; set; }
        public virtual DbSet<NivelColaboradorModulo> NivelColaboradorModulo { get; set; }
        public virtual DbSet<CategoriaCompetencia> CategoriaCompetencia { get; set; }
        public virtual DbSet<ColaboradorNivelCompetencia> ColaboradorNivelCompetencia { get; set; }
        public virtual DbSet<Competencia> Competencia { get; set; }
        public virtual DbSet<SubCategoriaCompetencia> SubCategoriaCompetencia { get; set; }
        public virtual DbSet<TareaCompensatoria> TareaCompensatoria { get; set; }
        public virtual DbSet<TareaCompensatoriaPermiso> TareaCompensatoriaPermiso { get; set; }
        public virtual DbSet<TareaCompensatoriaVacacion> TareaCompensatoriaVacacion { get; set; }
        public virtual DbSet<FBSLogEquipo> FBSLogEquipo { get; set; }
        public virtual DbSet<FBSLogError> FBSLogError { get; set; }
        public virtual DbSet<MarcaElectronica> MarcaElectronica { get; set; }
        public virtual DbSet<HistoricoAdjunto> HistoricoAdjunto { get; set; }
        public virtual DbSet<HistoricoInformacionTicket> HistoricoInformacionTicket { get; set; }
        public virtual DbSet<TipoErrorImplicacion> TipoErrorImplicacion { get; set; }
        public virtual DbSet<ColeccionTFS> ColeccionTFS { get; set; }
        public virtual DbSet<ProyectoTFS> ProyectoTFS { get; set; }
        public virtual DbSet<ServidorTFS> ServidorTFS { get; set; }
        public virtual DbSet<TicketAsignacionTFS> TicketAsignacionTFS { get; set; }
        public virtual DbSet<UsuarioTFS> UsuarioTFS { get; set; }
        public virtual DbSet<ProximaActividad> ProximaActividad { get; set; }
        public virtual DbSet<TipoRecurso> TipoRecurso { get; set; }
        public virtual DbSet<Mensaje> Mensaje { get; set; }
        public virtual DbSet<Ticket_Error> Ticket_Error { get; set; }
        public virtual DbSet<Ticket_PrioridadRevisada> Ticket_PrioridadRevisada { get; set; }
        public virtual DbSet<Ticket_Resolucion> Ticket_Resolucion { get; set; }
        public virtual DbSet<Ticket_ResolucionDesacuerdo> Ticket_ResolucionDesacuerdo { get; set; }
        public virtual DbSet<Ticket_CategoriaRevisada> Ticket_CategoriaRevisada { get; set; }
        public virtual DbSet<ComentarioTicket> ComentarioTicket { get; set; }
        public virtual DbSet<Ticket_RequierePublicacion> Ticket_RequierePublicacion { get; set; }
        public virtual DbSet<NotificacionTicket> NotificacionTicket { get; set; }
        public virtual DbSet<TipoNotificacionTicket> TipoNotificacionTicket { get; set; }
        public virtual DbSet<ActividadPropuesta> ActividadPropuesta { get; set; }
        public virtual DbSet<CausaNoTerminacion> CausaNoTerminacion { get; set; }
        public virtual DbSet<NoTerminacionTicket> NoTerminacionTicket { get; set; }
        public virtual DbSet<ActividadActividadRealizada> ActividadActividadRealizada { get; set; }
        public virtual DbSet<EstadoTicketProximaActividad> EstadoTicketProximaActividad { get; set; }
        public virtual DbSet<ComentarioGeneral> ComentarioGeneral { get; set; }
        public virtual DbSet<UsuarioLeeComentarioGeneral> UsuarioLeeComentarioGeneral { get; set; }
        public virtual DbSet<NoTerminacionTarea> NoTerminacionTarea { get; set; }
        public virtual DbSet<CorreoNoEnviado> CorreoNoEnviado { get; set; }
        public virtual DbSet<TICKET_COMPLEMENTO> TICKET_COMPLEMENTO { get; set; }
        public virtual DbSet<Reporte> Reporte { get; set; }
        public virtual DbSet<EstadoActa> EstadoActa { get; set; }
        public virtual DbSet<TipoActa> TipoActa { get; set; }
        public virtual DbSet<Acta> Acta { get; set; }
        public virtual DbSet<TipoModulo> TipoModulo { get; set; }
        public virtual DbSet<FuncionalidadCliente> FuncionalidadCliente { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<EstadoContrato> EstadoContrato { get; set; }
        public virtual DbSet<Adenda> Adenda { get; set; }
        public virtual DbSet<FaseContrato> FaseContrato { get; set; }
        public virtual DbSet<MotivoTrabajoInformacionAdicional> MotivoTrabajoInformacionAdicional { get; set; }
        public virtual DbSet<MotivoTrabajoSeguimiento> MotivoTrabajoSeguimiento { get; set; }
        public virtual DbSet<SubModulo> SubModulo { get; set; }
        public virtual DbSet<TipoPlazo> TipoPlazo { get; set; }
        public virtual DbSet<MotivoPrioridadTicket> MotivoPrioridadTicket { get; set; }
        public virtual DbSet<MotivoTrabajoTicket> MotivoTrabajoTicket { get; set; }
        public virtual DbSet<TicketsMantenimiento> TicketsMantenimiento { get; set; }
        public virtual DbSet<ProyectoModuloCliente> ProyectoModuloCliente { get; set; }
        public virtual DbSet<AdjuntoContrato> AdjuntoContrato { get; set; }
        public virtual DbSet<GestorServicios> GestorServicios { get; set; }
        public virtual DbSet<TareaMantenimiento> TareaMantenimiento { get; set; }
        public virtual DbSet<ComentarioMantenimientoTickets> ComentarioMantenimientoTickets { get; set; }
        public virtual DbSet<TareaMantenimientoBorrar> TareaMantenimientoBorrar { get; set; }
        public virtual DbSet<TicketMantenimientoBorar> TicketMantenimientoBorar { get; set; }
        public virtual DbSet<TicketMantenimientoAgregar> TicketMantenimientoAgregar { get; set; }
        public virtual DbSet<ComentarioHorasMantenimiento> ComentarioHorasMantenimiento { get; set; }
        public virtual DbSet<MotivoDevolucionTicket> MotivoDevolucionTicket { get; set; }
        public virtual DbSet<EntregableTicket> ENTREGABLETICKET { get; set; }
        public virtual DbSet<Repositorio> Repositorio { get; set; }
        public virtual DbSet<VersionBaseDatos> VersionBaseDatos { get; set; }
        public virtual DbSet<VersionDesarrollo> VersionDesarrollo { get; set; }
        public virtual DbSet<ComentarioTicketCliente> ComentarioTicketCliente { get; set; }
        public virtual DbSet<EntregableDetalleEstimacion> EntregableDetalleEstimacion { get; set; }
        public virtual DbSet<ClienteAuxiliar> ClienteAuxiliar { get; set; }
        public virtual DbSet<ResponsableProyectos> ResponsableProyectos { get; set; }
        public virtual DbSet<TicketVersionCliente> TicketVersionCliente { get; set; }
        public virtual DbSet<Semaforo> Semaforo { get; set; }
        public virtual DbSet<SemaforoPrioridad> SemaforoPrioridad { get; set; }
        public virtual DbSet<ResolucionSemaforoPrioridad> ResolucionSemaforoPrioridad { get; set; }
        public virtual DbSet<Ofertas> Ofertas { get; set; }
        public virtual DbSet<SolicitudVacaciones> SolicitudVacaciones { get; set; }
        public virtual DbSet<SolicitudPermisos> SolicitudPermisos { get; set; }
        public virtual DbSet<InfoTickets> InfoTickets { get; set; }
        public virtual DbSet<TecnologiasYProcesos> TecnologiasYProcesos { get; set; }
        public virtual DbSet<NivelColaboradorTecnologia> NivelColaboradorTecnologia { get; set; }
        public virtual DbSet<Feriados> Feriados { get; set; }
        public virtual DbSet<Incidencias> Incidencias { get; set; }
        public virtual DbSet<CategoriaRecursos> CategoriaRecursos { get; set; }
        public virtual DbSet<CalificacionTicket> CalificacionTicket { get; set; }
        public virtual DbSet<CalificacionTicketCliente> CalificacionTicketCliente { get; set; }
        public virtual DbSet<Recursos> Recursos { get; set; }
        public virtual DbSet<ItemEspecial> ItemEspecial { get; set; }
        public virtual DbSet<ItemEspecialCatalogo> ItemEspecialCatalogo { get; set; }
        public virtual DbSet<ItemEspecialEstimacion> ItemEspecialEstimacion { get; set; }
        public virtual DbSet<TiempoCerradoTicket> TiempoCerradoTicket { get; set; }
        public virtual DbSet<EtapasProyecto> EtapasProyecto { get; set; }
        public virtual DbSet<EtapasProyectoCliente> EtapasProyectoCliente { get; set; }
        public virtual DbSet<RecursosSubEtapasProyecto> RecursosSubEtapasProyecto { get; set; }
        public virtual DbSet<SubEtapasProyectosCliente> SUBETAPASPROYECTOSCLIENTE { get; set; }
        public virtual DbSet<IncidenciasRecursos> IncidenciasRecursos { get; set; }
        public virtual DbSet<RecursosAsistencia> RecursosAsistencia { get; set; }
        public virtual DbSet<ServicioImplantacionCore> ServicioImplantacionCore { get; set; }
        public virtual DbSet<TiemposProyecto> TiemposProyecto { get; set; }
        public virtual DbSet<OfertaRequerimiento> OFERTAREQUERIMIENTO { get; set; }
        public virtual DbSet<Requerimiento> REQUERIMIENTO { get; set; }
        public virtual DbSet<ClienteReporteMantenimiento> ClienteReporteMantenimiento { get; set; }
        public virtual DbSet<TareaCapacitacion> TareaCapacitacion { get; set; }
    }
}
