//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.nivelColaboradorModulo = new HashSet<NivelColaboradorModulo>();
            this.tarea = new HashSet<Tarea>();
            this.funcionalidad = new HashSet<Funcionalidad>();
            this.subModulo = new HashSet<SubModulo>();
            this.proyectoModuloCliente = new HashSet<ProyectoModuloCliente>();
            this.TICKET = new HashSet<Ticket>();
            this.INCIDENCIAS = new HashSet<Incidencias>();
            this.recursos = new HashSet<Recursos>();
        }
    
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
        public Nullable<int> SecuencialTipoModulo { get; set; }
        public string Ordenar { get; set; }
    
        public virtual TipoModulo TipoModulo { get; set; }
        public virtual ICollection<NivelColaboradorModulo> nivelColaboradorModulo { get; set; }
        public virtual ICollection<Tarea> tarea { get; set; }
        public virtual ICollection<Funcionalidad> funcionalidad { get; set; }
        public virtual ICollection<SubModulo> subModulo { get; set; }
        public virtual ICollection<ProyectoModuloCliente> proyectoModuloCliente { get; set; }
        public virtual ICollection<Ticket> TICKET { get; set; }
        public virtual ICollection<Incidencias> INCIDENCIAS { get; set; }
        public virtual ICollection<Recursos> recursos { get; set; }
    }
}
