//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoTrabajoSeguimiento
    {
        public int Secuencial { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Realizado { get; set; }
        public string PorRealizar { get; set; }
        public string Pendiente { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
        public int SecuencialMotivoTrabajoInformacionAdicional { get; set; }
        public Nullable<int> SecuencialUsuario { get; set; }
    
        public virtual MotivoTrabajoInformacionAdicional motivoTrabajoInformacionAdicional { get; set; }
        public virtual Usuario usuario { get; set; }
    }
}
