//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoTrabajo
    {
        public MotivoTrabajo()
        {
            this.entregableMotivoTrabajo = new HashSet<EntregableMotivoTrabajo>();
            this.Acta = new HashSet<Acta>();
            this.motivoTrabajoTicket = new HashSet<MotivoTrabajoTicket>();
            this.adjuntoContrato = new HashSet<AdjuntoContrato>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialTipoMotivoTrabajo { get; set; }
        public int SecuencialCliente { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.DateTime FechaInicioPlanificacion { get; set; }
        public System.DateTime FechaFinPlanificacion { get; set; }
        public decimal Avance { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
        public Nullable<int> SecuencialEstadoContrato { get; set; }
        public Nullable<int> SecuencialColaborador { get; set; }
        public Nullable<int> SecuencialTipoPlazo { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<int> HorasMes { get; set; }
    
        public virtual Cliente cliente { get; set; }
        public virtual ICollection<EntregableMotivoTrabajo> entregableMotivoTrabajo { get; set; }
        public virtual TipoMotivoTrabajo tipoMotivoTrabajo { get; set; }
        public virtual ICollection<Acta> Acta { get; set; }
        public virtual EstadoContrato estadoContrato { get; set; }
        public virtual MotivoTrabajoInformacionAdicional motivoTrabajoInformacionAdicional { get; set; }
        public virtual Colaborador colaborador { get; set; }
        public virtual TipoPlazo tipoPlazo { get; set; }
        public virtual ICollection<MotivoTrabajoTicket> motivoTrabajoTicket { get; set; }
        public virtual ICollection<AdjuntoContrato> adjuntoContrato { get; set; }
    }
}
