//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoTrabajoInformacionAdicional
    {
        public MotivoTrabajoInformacionAdicional()
        {
            this.adenda = new HashSet<Adenda>();
            this.motivoTrabajoSeguimiento = new HashSet<MotivoTrabajoSeguimiento>();
        }
    
        public int SecuencialMotivoTrabajo { get; set; }
        public decimal TieneCronograma { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
        public int SecuencialFase { get; set; }
        public string LinkOpenKm { get; set; }
        public System.DateTime FechaProduccion { get; set; }
        public int DiasGarantia { get; set; }
        public Nullable<decimal> PagadoTotalmente { get; set; }
        public Nullable<System.DateTime> FechaActa { get; set; }
        public Nullable<decimal> AceptaCambiosNormativos { get; set; }
        public Nullable<int> Estimacion { get; set; }
    
        public virtual ICollection<Adenda> adenda { get; set; }
        public virtual FaseContrato faseContrato { get; set; }
        public virtual MotivoTrabajo motivoTrabajo { get; set; }
        public virtual ICollection<MotivoTrabajoSeguimiento> motivoTrabajoSeguimiento { get; set; }
    }
}
