//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelColaborador
    {
        public NivelColaborador()
        {
            this.detalleEstimacionTicket = new HashSet<DetalleEstimacionTicket>();
            this.ITEMESPECIAL = new HashSet<ItemEspecial>();
        }
    
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<DetalleEstimacionTicket> detalleEstimacionTicket { get; set; }
        public virtual ICollection<ItemEspecial> ITEMESPECIAL { get; set; }
    }
}
