//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoTerminacionTarea
    {
        public int Secuencial { get; set; }
        public int SecuencialTarea { get; set; }
        public int SecuencialCausaNoTerminacion { get; set; }
        public int SecuencialActividadPropuesta { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Comentario { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ActividadPropuesta actividadPropuesta { get; set; }
        public virtual CausaNoTerminacion causaNoTerminacion { get; set; }
        public virtual Tarea tarea { get; set; }
    }
}
