//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaCotizacionTicket
    {
        public OfertaCotizacionTicket()
        {
            this.renegociacion = new HashSet<Renegociacion>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialCotizacionTicket { get; set; }
        public string TextoOferta { get; set; }
        public decimal Precio { get; set; }
        public decimal OfertaAceptada { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal PrecioHoras { get; set; }
        public decimal TotalHoras { get; set; }
        public decimal PorcientoIncremento { get; set; }
        public decimal Renegociable { get; set; }
    
        public virtual CotizacionTicket cotizacionTicket { get; set; }
        public virtual ICollection<Renegociacion> renegociacion { get; set; }
    }
}
