//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ofertas
    {
        public int Secuencial { get; set; }
        public int SecuencialCliente { get; set; }
        public int SecuencialColaborador { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaDisponibilidad { get; set; }
        public string Detalle { get; set; }
        public int HorasEstimacion { get; set; }
        public Nullable<System.DateTime> FechaProduccion { get; set; }
    
        public virtual Cliente cliente { get; set; }
        public virtual Colaborador colaborador { get; set; }
    }
}
