//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaRequerimiento
    {
        public OfertaRequerimiento()
        {
            this.OFERTAOFERTA = new HashSet<OfertaOferta>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialCLiente { get; set; }
        public int SecuencialRequerimiento { get; set; }
        public Nullable<int> SecuencialTicketTarea { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> FechaPedidoCLiente { get; set; }
    
        public virtual ICollection<OfertaOferta> OFERTAOFERTA { get; set; }
    }
}
