//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaOferta
    {
        public OfertaOferta()
        {
            this.FORMALIZACIONOFERTAS = new HashSet<FormalizacionOfertas>();
        }
    
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public Nullable<System.DateTime> FechaRecepcionEstimacion { get; set; }
        public Nullable<System.DateTime> FechaGeneracionOferta { get; set; }
        public Nullable<System.DateTime> FechaEnvioRevision { get; set; }
        public Nullable<System.DateTime> FechaAprobacionOfertaGerencia { get; set; }
        public Nullable<System.DateTime> FechaEnvioOfertaCliente { get; set; }
        public Nullable<System.DateTime> FechaVencimientoOferta { get; set; }
        public Nullable<int> SecuencialOfertaRequerimiento { get; set; }
        public Nullable<int> EstaActivo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string FormaPago { get; set; }
        public Nullable<bool> Descuento { get; set; }
        public string Estado { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> SecuencialEstadoGestion { get; set; }
        public string Observacion { get; set; }
    
        public virtual OfertaRequerimiento OfertaRequerimiento { get; set; }
        public virtual ICollection<FormalizacionOfertas> FORMALIZACIONOFERTAS { get; set; }
        public virtual EstadoGestionOferta estadoGestionOferta { get; set; }
    }
}
