//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.persona = new HashSet<Persona>();
        }
    
        public int Secuencial { get; set; }
        public decimal CodNum { get; set; }
        public string CodA2 { get; set; }
        public string CodA3 { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<Persona> persona { get; set; }
    }
}
