//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public Permiso()
        {
            this.gestionPermiso = new HashSet<GestionPermiso>();
            this.tareaCompensatoriaPermiso = new HashSet<TareaCompensatoriaPermiso>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialTipoPermiso { get; set; }
        public int SecuencialEstadoPermiso { get; set; }
        public int SecuencialColaborador { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Motivo { get; set; }
    
        public virtual EstadoPermiso estadoPermiso { get; set; }
        public virtual ICollection<GestionPermiso> gestionPermiso { get; set; }
        public virtual Colaborador colaborador { get; set; }
        public virtual TipoPermiso tipoPermiso { get; set; }
        public virtual ICollection<TareaCompensatoriaPermiso> tareaCompensatoriaPermiso { get; set; }
    }
}
