//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.usuario = new HashSet<Usuario>();
            this.colaborador = new HashSet<Colaborador>();
            this.personaGrupoEmail = new HashSet<PersonaGrupoEmail>();
        }
    
        public int Secuencial { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaNac { get; set; }
        public int SecuencialPais { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<Usuario> usuario { get; set; }
        public virtual ICollection<Colaborador> colaborador { get; set; }
        public virtual Pais pais { get; set; }
        public virtual Persona_Cliente persona_cliente { get; set; }
        public virtual ICollection<PersonaGrupoEmail> personaGrupoEmail { get; set; }
    }
}
