//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaGrupoEmail
    {
        public int Secuencial { get; set; }
        public int SecuencialPersona { get; set; }
        public int SecuencialGrupoEmail { get; set; }
        public int NumeroVerificador { get; set; }
        public decimal EstaActivo { get; set; }
    
        public virtual GrupoEmail grupoEmail { get; set; }
        public virtual Persona persona { get; set; }
    }
}
