//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona_Cliente
    {
        public Persona_Cliente()
        {
            this.TICKET = new HashSet<Ticket>();
            this.TICKETHISTORICO = new HashSet<TicketHistorico>();
        }
    
        public int SecuencialPersona { get; set; }
        public int SecuencialCliente { get; set; }
        public int NumeroVerificador { get; set; }
        public string Telefono { get; set; }
    
        public virtual Cliente cliente { get; set; }
        public virtual Persona persona { get; set; }
        public virtual ICollection<Ticket> TICKET { get; set; }
        public virtual ICollection<TicketHistorico> TICKETHISTORICO { get; set; }
    }
}
