//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrioridadTicket
    {
        public PrioridadTicket()
        {
            this.ticket = new HashSet<Ticket>();
            this.ticketHistorico = new HashSet<TicketHistorico>();
            this.TICKET_PRIORIDADREVISADA = new HashSet<Ticket_PrioridadRevisada>();
            this.ticketHistoricoPrioridad = new HashSet<TicketHistorico>();
            this.semaforoPrioridad = new HashSet<SemaforoPrioridad>();
            this.RESOLUCIONSEMAFOROPRIORIDAD = new HashSet<ResolucionSemaforoPrioridad>();
        }
    
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActiva { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<Ticket> ticket { get; set; }
        public virtual ICollection<TicketHistorico> ticketHistorico { get; set; }
        public virtual ICollection<Ticket_PrioridadRevisada> TICKET_PRIORIDADREVISADA { get; set; }
        public virtual ICollection<TicketHistorico> ticketHistoricoPrioridad { get; set; }
        public virtual ICollection<SemaforoPrioridad> semaforoPrioridad { get; set; }
        public virtual ICollection<ResolucionSemaforoPrioridad> RESOLUCIONSEMAFOROPRIORIDAD { get; set; }
    }
}
