//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecursosAsistencia
    {
        public int Secuencial { get; set; }
        public int SecuencialRecurso { get; set; }
        public int SecuencialColaborador { get; set; }
        public decimal Asistencia { get; set; }
        public double Puntuacion { get; set; }
        public decimal EstaActivo { get; set; }
        public Nullable<decimal> Convocado { get; set; }
    
        public virtual Colaborador colaborador { get; set; }
        public virtual Recursos recursos { get; set; }
    }
}
