//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recursos
    {
        public int Secuencial { get; set; }
        public string Titulo { get; set; }
        public string Detalle { get; set; }
        public System.DateTime Fecha { get; set; }
        public int SecuencialModulo { get; set; }
        public string Adjunto { get; set; }
        public string TiempoCapacitacion { get; set; }
        public string AdjuntoAsistencia { get; set; }
    
        public virtual Modulo modulo { get; set; }
    }
}
