//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResolucionSemaforoPrioridad
    {
        public int Secuencial { get; set; }
        public int SecuencialPrioridad { get; set; }
        public int SecuencialSemaforo { get; set; }
        public int Horas { get; set; }
        public Nullable<decimal> EstaActivo { get; set; }
        public Nullable<int> NumeroVerificador { get; set; }
    
        public virtual PrioridadTicket prioridadTicket { get; set; }
        public virtual Semaforo semaforo { get; set; }
    }
}
