//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsableProyectos
    {
        public ResponsableProyectos()
        {
            this.CLIENTEAUXILIAR = new HashSet<ClienteAuxiliar>();
            this.CLIENTEAUXILIAR1 = new HashSet<ClienteAuxiliar>();
            this.CLIENTEAUXILIAR2 = new HashSet<ClienteAuxiliar>();
            this.CLIENTEAUXILIAR3 = new HashSet<ClienteAuxiliar>();
        }
    
        public int Secuencial { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
        public decimal EsTecnico { get; set; }
    
        public virtual ICollection<ClienteAuxiliar> CLIENTEAUXILIAR { get; set; }
        public virtual ICollection<ClienteAuxiliar> CLIENTEAUXILIAR1 { get; set; }
        public virtual ICollection<ClienteAuxiliar> CLIENTEAUXILIAR2 { get; set; }
        public virtual ICollection<ClienteAuxiliar> CLIENTEAUXILIAR3 { get; set; }
    }
}
