//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsableProyectos
    {
        public ResponsableProyectos()
        {
            this.clientesUbicacion = new HashSet<ClienteAuxiliar>();
            this.clientesResponsableAcceso = new HashSet<ClienteAuxiliar>();
            this.clientesResponsableCodigo = new HashSet<ClienteAuxiliar>();
            this.clientesResponsablePublicacion = new HashSet<ClienteAuxiliar>();
        }
    
        public int Secuencial { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
        public decimal EsTecnico { get; set; }
    
        public virtual ICollection<ClienteAuxiliar> clientesUbicacion { get; set; }
        public virtual ICollection<ClienteAuxiliar> clientesResponsableAcceso { get; set; }
        public virtual ICollection<ClienteAuxiliar> clientesResponsableCodigo { get; set; }
        public virtual ICollection<ClienteAuxiliar> clientesResponsablePublicacion { get; set; }
    }
}
