//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semaforo
    {
        public Semaforo()
        {
            this.semaforoPrioridad = new HashSet<SemaforoPrioridad>();
            this.RESOLUCIONSEMAFOROPRIORIDAD = new HashSet<ResolucionSemaforoPrioridad>();
        }
    
        public int Secuencial { get; set; }
        public string Codigo { get; set; }
        public decimal EstaActivo { get; set; }
        public string Descripcion { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<SemaforoPrioridad> semaforoPrioridad { get; set; }
        public virtual ICollection<ResolucionSemaforoPrioridad> RESOLUCIONSEMAFOROPRIORIDAD { get; set; }
    }
}
