//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudTarea
    {
        public int Secuencial { get; set; }
        public int SecuencialColaborador { get; set; }
        public System.DateTime HoraSolicitud { get; set; }
        public string Descripcion { get; set; }
        public decimal Aceptada { get; set; }
        public decimal Rechazada { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual Colaborador colaborador { get; set; }
        public virtual Gestion_SolicitudTarea gestion_solicitudTarea { get; set; }
    }
}
