//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudVacaciones
    {
        public int Secuencial { get; set; }
        public string ApellidosNombres { get; set; }
        public string Cargo { get; set; }
        public string Cedula { get; set; }
        public System.DateTime FechaIngresoSolicitud { get; set; }
        public string Empresa { get; set; }
        public System.DateTime FechaIngresoInstitucion { get; set; }
        public int AniosServicio { get; set; }
        public int DiasCorresponden { get; set; }
        public int DiasDisfrutar { get; set; }
        public int DiasPendientes { get; set; }
        public int DelAnio { get; set; }
        public int AlAnio { get; set; }
        public System.DateTime FechaInicioVacaciones { get; set; }
        public System.DateTime FechaFinVacaciones { get; set; }
        public System.DateTime FechaPresentarseTrabajar { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> Estado { get; set; }
    }
}
