//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPermisos
    {
        public int Secuencial { get; set; }
        public string ApellidosNombres { get; set; }
        public string Cedula { get; set; }
        public string Cargo { get; set; }
        public string Area { get; set; }
        public System.DateTime FechaIngresoSolicitud { get; set; }
        public string Empresa { get; set; }
        public bool Personal { get; set; }
        public bool Matrimonio { get; set; }
        public bool Comida { get; set; }
        public bool Paternidad { get; set; }
        public bool Otros { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.TimeSpan HoraSalida { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public System.TimeSpan HoraRetorno { get; set; }
        public string Motivo { get; set; }
        public string Jefe { get; set; }
        public Nullable<decimal> Estado { get; set; }
    }
}
