//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubEtapasProyectosCliente
    {
        public int Secuencial { get; set; }
        public int SecuencialRecuros { get; set; }
        public int SecuencialEtapaProyecto { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActivo { get; set; }
        public System.DateTime FechaComienzo { get; set; }
        public System.DateTime FechaFin { get; set; }
    
        public virtual EtapasProyectoCliente etapasProyectosCliente { get; set; }
        public virtual RecursosSubEtapasProyecto recursosSubEtapasProyecto { get; set; }
    }
}
