//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaCatalogo
    {
        public TablaCatalogo()
        {
            this.campoCatalogo = new HashSet<CampoCatalogo>();
            this.campoCatalogo_tablaCatalogo = new HashSet<CampoCatalogo_TablaCatalogo>();
        }
    
        public int Secuencial { get; set; }
        public string NombreMostrar { get; set; }
        public string NombreNegocio { get; set; }
        public string Descripcion { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ICollection<CampoCatalogo> campoCatalogo { get; set; }
        public virtual ICollection<CampoCatalogo_TablaCatalogo> campoCatalogo_tablaCatalogo { get; set; }
    }
}
