//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaCompensatoria
    {
        public TareaCompensatoria()
        {
            this.tareaCompensatoriaVacacion = new HashSet<TareaCompensatoriaVacacion>();
            this.tareaCompensatoriaPermiso = new HashSet<TareaCompensatoriaPermiso>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialTarea { get; set; }
        public int SecuencialUsuario { get; set; }
        public int TiempoMinutos { get; set; }
        public int TiempoConsumido { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public decimal EstaActiva { get; set; }
    
        public virtual Usuario usuario { get; set; }
        public virtual Tarea tarea { get; set; }
        public virtual ICollection<TareaCompensatoriaVacacion> tareaCompensatoriaVacacion { get; set; }
        public virtual ICollection<TareaCompensatoriaPermiso> tareaCompensatoriaPermiso { get; set; }
    }
}
