//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaActividadRealizada
    {
        public TareaActividadRealizada()
        {
            this.comentarioTarea = new HashSet<ComentarioTarea>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialTarea { get; set; }
        public int SecuencialActividadRealizada { get; set; }
        public int SecuencialUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public System.DateTime HoraFin { get; set; }
        public System.DateTime HoraOperacion { get; set; }
        public Nullable<int> SECUENCIALTICKET { get; set; }
        public Nullable<int> SECUENCIALCONTRATO { get; set; }
    
        public virtual Usuario usuario { get; set; }
        public virtual ActividadRealizada actividadRealizada { get; set; }
        public virtual ICollection<ComentarioTarea> comentarioTarea { get; set; }
        public virtual Tarea tarea { get; set; }
    }
}
