//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea_TareaRelacionada
    {
        public int SecuencialTareaRelacionada { get; set; }
        public int SecuencialTarea { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual Tarea tarea { get; set; }
        public virtual Tarea tarea1 { get; set; }
    }
}
