//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public Tarea()
        {
            this.historicoTareaEstado = new HashSet<HistoricoTareaEstado>();
            this.ticketTarea = new HashSet<TicketTarea>();
            this.tareaActividadRealizada = new HashSet<TareaActividadRealizada>();
            this.tarea_tareaRelacionada = new HashSet<Tarea_TareaRelacionada>();
            this.tareaCompensatoria = new HashSet<TareaCompensatoria>();
            this.NOTERMINACIONTAREA = new HashSet<NoTerminacionTarea>();
            this.tareaMantenimiento = new HashSet<TareaMantenimiento>();
            this.TAREAMANTENIMIENTOBORRAR = new HashSet<TareaMantenimientoBorrar>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialColaborador { get; set; }
        public int SecuencialActividad { get; set; }
        public int SecuencialLugarTarea { get; set; }
        public int SecuencialEstadoTarea { get; set; }
        public int SecuencialModulo { get; set; }
        public int SecuencialCliente { get; set; }
        public string Detalle { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public decimal HorasUtilizadas { get; set; }
        public int NumeroVerificador { get; set; }
        public Nullable<System.TimeSpan> TiempoEstimacion { get; set; }
    
        public virtual Actividad actividad { get; set; }
        public virtual Cliente cliente { get; set; }
        public virtual Colaborador colaborador { get; set; }
        public virtual EstadoTarea estadoTarea { get; set; }
        public virtual ICollection<HistoricoTareaEstado> historicoTareaEstado { get; set; }
        public virtual LugarTarea lugarTarea { get; set; }
        public virtual ICollection<TicketTarea> ticketTarea { get; set; }
        public virtual ICollection<TareaActividadRealizada> tareaActividadRealizada { get; set; }
        public virtual Tarea_Coordinador tarea_coordinador { get; set; }
        public virtual ICollection<Tarea_TareaRelacionada> tarea_tareaRelacionada { get; set; }
        public virtual Tarea_TareaRelacionada tarea_tareaRelacionada1 { get; set; }
        public virtual EntregableMotivoTrabajo entregableMotivoTrabajo { get; set; }
        public virtual Gestion_SolicitudTarea gestion_solicitudTarea { get; set; }
        public virtual ICollection<TareaCompensatoria> tareaCompensatoria { get; set; }
        public virtual ICollection<NoTerminacionTarea> NOTERMINACIONTAREA { get; set; }
        public virtual Modulo modulo { get; set; }
        public virtual ICollection<TareaMantenimiento> tareaMantenimiento { get; set; }
        public virtual ICollection<TareaMantenimientoBorrar> TAREAMANTENIMIENTOBORRAR { get; set; }
    }
}
