//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaCompensatoriaVacacion
    {
        public int Secuencial { get; set; }
        public int SecuencialTareaCompensatoria { get; set; }
        public int SecuencialVacaciones { get; set; }
        public int TiempoMinutos { get; set; }
        public decimal EstaActiva { get; set; }
    
        public virtual Vacaciones vacaciones { get; set; }
        public virtual TareaCompensatoria tareaCompensatoria { get; set; }
    }
}
