//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResultView
    {
        public string TestResultBK { get; set; }
        public Nullable<int> DateResultRecordCount { get; set; }
        public Nullable<int> BuildResultRecordCount { get; set; }
        public Nullable<int> PointRecordCount { get; set; }
        public Nullable<int> ResultCount { get; set; }
        public Nullable<int> ResultTransitionCount { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public Nullable<int> PointId { get; set; }
        public Nullable<int> ChangeNumber { get; set; }
        public Nullable<int> TestCaseId { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<System.Guid> TeamProjectProjectNodeGUID { get; set; }
        public string TeamProjectProjectNodeName { get; set; }
        public Nullable<int> TeamProjectProjectNodeType { get; set; }
        public string TeamProjectProjectNodeTypeName { get; set; }
        public Nullable<bool> TeamProjectIsDeleted { get; set; }
        public string TeamProjectReportPath { get; set; }
        public string TeamProjectProjectPath { get; set; }
        public Nullable<int> TeamProjectDepth { get; set; }
        public string ResultBK { get; set; }
        public string ResultId { get; set; }
        public string ResultTestCaseId { get; set; }
        public string ResultExecutionId { get; set; }
        public string ResultTest { get; set; }
        public string ResultComputerName { get; set; }
        public string ResultOutcome { get; set; }
        public Nullable<byte> ResultOutcomeId { get; set; }
        public string ResultReadinessState { get; set; }
        public Nullable<byte> ResultReadinessStateId { get; set; }
        public string ResultErrorMessage { get; set; }
        public Nullable<System.DateTime> ResultDateStarted { get; set; }
        public Nullable<System.DateTime> ResultDateCompleted { get; set; }
        public Nullable<System.DateTime> ResultCreationDate { get; set; }
        public Nullable<long> ResultDuration { get; set; }
        public string ResultResolutionState { get; set; }
        public string ResultFailureType { get; set; }
        public Nullable<byte> ResultFailureTypeId { get; set; }
        public Nullable<byte> ResultPriority { get; set; }
        public Nullable<int> ResultTestCaseRevision { get; set; }
        public string ResultTestTypeId { get; set; }
        public Nullable<int> ResultTeamProjectCollectionSK { get; set; }
        public Nullable<int> ResultOwnerSK { get; set; }
        public Nullable<int> ResultExecutedBySK { get; set; }
        public Nullable<int> ResultAreaSK { get; set; }
        public Nullable<int> ResultIterationSK { get; set; }
        public Nullable<int> ResultTestResultAttributesSK { get; set; }
        public string TestResultAttributesResultAttributeBK { get; set; }
        public string TestResultAttributesOutcome { get; set; }
        public Nullable<byte> TestResultAttributesOutcomeId { get; set; }
        public string TestResultAttributesReadinessState { get; set; }
        public Nullable<byte> TestResultAttributesReadinessStateId { get; set; }
        public string TestResultAttributesResolutionState { get; set; }
        public string TestResultAttributesFailureType { get; set; }
        public Nullable<byte> TestResultAttributesFailureTypeId { get; set; }
        public Nullable<byte> TestResultAttributesPriority { get; set; }
        public Nullable<int> TestResultAttributesTeamProjectCollectionSK { get; set; }
        public Nullable<int> TestResultAttributesOwnerSK { get; set; }
        public Nullable<int> TestResultAttributesExecutedBySK { get; set; }
        public string BuildBK { get; set; }
        public string BuildID { get; set; }
        public string BuildName { get; set; }
        public string BuildType { get; set; }
        public string BuildDefinitionName { get; set; }
        public string BuildDropLocation { get; set; }
        public Nullable<System.DateTime> BuildStartTime { get; set; }
        public Nullable<int> BuildTeamProjectCollectionSK { get; set; }
        public string TestRunBK { get; set; }
        public Nullable<int> TestRunId { get; set; }
        public string TestRunTitle { get; set; }
        public Nullable<byte> TestRunStateId { get; set; }
        public string TestRunState { get; set; }
        public Nullable<bool> TestRunIsAutomated { get; set; }
        public Nullable<bool> TestRunIsBuildVerificationRun { get; set; }
        public Nullable<System.DateTime> TestRunCreationDate { get; set; }
        public Nullable<System.DateTime> TestRunStartDate { get; set; }
        public Nullable<System.DateTime> TestRunCompleteDate { get; set; }
        public Nullable<int> TestRunTeamProjectCollectionSK { get; set; }
        public Nullable<int> TestRunRunOwnerSK { get; set; }
        public string AreaName { get; set; }
        public string AreaGUID { get; set; }
        public string AreaParentAreaGUID { get; set; }
        public string AreaPath { get; set; }
        public Nullable<int> AreaDepth { get; set; }
        public string AreaForwardingID { get; set; }
        public string AreaProjectGUID { get; set; }
        public string IterationName { get; set; }
        public string IterationGUID { get; set; }
        public string IterationParentIterationGUID { get; set; }
        public string IterationPath { get; set; }
        public Nullable<int> IterationDepth { get; set; }
        public string IterationForwardingID { get; set; }
        public string IterationProjectGUID { get; set; }
        public Nullable<System.DateTime> IterationStartDate { get; set; }
        public Nullable<System.DateTime> IterationFinishDate { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> DateYear { get; set; }
        public string DateYearString { get; set; }
        public Nullable<System.DateTime> DateMonth { get; set; }
        public string DateMonthString { get; set; }
        public Nullable<int> DateMonthOfYear { get; set; }
        public Nullable<System.DateTime> DateWeek { get; set; }
        public string DateWeekString { get; set; }
        public Nullable<int> DateWeekOfYear { get; set; }
        public string Date { get; set; }
        public Nullable<int> DateDayOfYear { get; set; }
        public Nullable<int> DateDayOfMonth { get; set; }
        public Nullable<int> DateDayOfWeek { get; set; }
        public string TestPlanBK { get; set; }
        public Nullable<int> TestPlanId { get; set; }
        public string TestPlanName { get; set; }
        public Nullable<byte> TestPlanStateId { get; set; }
        public string TestPlanState { get; set; }
        public Nullable<System.DateTime> TestPlanStartDate { get; set; }
        public Nullable<System.DateTime> TestPlanEndDate { get; set; }
        public Nullable<int> TestPlanTeamProjectCollectionSK { get; set; }
        public Nullable<int> TestPlanPlanOwnerSK { get; set; }
        public Nullable<int> TestPlanAreaSK { get; set; }
        public Nullable<int> TestPlanIterationSK { get; set; }
        public string BuildPlatformName { get; set; }
        public string BuildFlavorName { get; set; }
        public string ConfigurationBK { get; set; }
        public Nullable<int> ConfigurationId { get; set; }
        public string ConfigurationName { get; set; }
        public Nullable<int> ConfigurationTeamProjectCollectionSK { get; set; }
        public string TestSuiteBK { get; set; }
        public string TestSuiteParentTestSuiteBK { get; set; }
        public Nullable<int> TestSuiteId { get; set; }
        public Nullable<int> TestSuiteParentTestSuiteId { get; set; }
        public string TestSuiteSuiteName { get; set; }
        public string TestSuiteSuitePath { get; set; }
        public Nullable<byte> TestSuiteSuiteTypeId { get; set; }
        public string TestSuiteSuiteType { get; set; }
        public Nullable<int> TestSuiteRequirementId { get; set; }
        public Nullable<int> TestSuiteTeamProjectSK { get; set; }
    }
}
