//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TFSWarehouseEntities : DbContext
    {
        public TFSWarehouseEntities()
            : base("name=TFSWarehouseEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 180;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_DimAreaOverlay> C_DimAreaOverlay { get; set; }
        public virtual DbSet<C_DimIterationOverlay> C_DimIterationOverlay { get; set; }
        public virtual DbSet<C_DimTestCaseOverlay> C_DimTestCaseOverlay { get; set; }
        public virtual DbSet<C_WarehouseUpdate> C_WarehouseUpdate { get; set; }
        public virtual DbSet<DimArea> DimArea { get; set; }
        public virtual DbSet<DimAssembly> DimAssembly { get; set; }
        public virtual DbSet<DimBuild> DimBuild { get; set; }
        public virtual DbSet<DimBuildFlavor> DimBuildFlavor { get; set; }
        public virtual DbSet<DimBuildPlatform> DimBuildPlatform { get; set; }
        public virtual DbSet<DimBuildQuality> DimBuildQuality { get; set; }
        public virtual DbSet<DimBuildStatus> DimBuildStatus { get; set; }
        public virtual DbSet<DimChangeset> DimChangeset { get; set; }
        public virtual DbSet<DimCodeElement> DimCodeElement { get; set; }
        public virtual DbSet<DimConfiguration> DimConfiguration { get; set; }
        public virtual DbSet<DimDate> DimDate { get; set; }
        public virtual DbSet<DimFile> DimFile { get; set; }
        public virtual DbSet<DimIteration> DimIteration { get; set; }
        public virtual DbSet<DimMachine> DimMachine { get; set; }
        public virtual DbSet<DimPerson> DimPerson { get; set; }
        public virtual DbSet<DimTeamProject> DimTeamProject { get; set; }
        public virtual DbSet<DimTestPlan> DimTestPlan { get; set; }
        public virtual DbSet<DimTestResult> DimTestResult { get; set; }
        public virtual DbSet<DimTestResultAttributes> DimTestResultAttributes { get; set; }
        public virtual DbSet<DimTestRun> DimTestRun { get; set; }
        public virtual DbSet<DimTestSuite> DimTestSuite { get; set; }
        public virtual DbSet<DimToday> DimToday { get; set; }
        public virtual DbSet<DimToolArtifactDisplayUrl> DimToolArtifactDisplayUrl { get; set; }
        public virtual DbSet<DimWorkItem> DimWorkItem { get; set; }
        public virtual DbSet<DimWorkItemCategory> DimWorkItemCategory { get; set; }
        public virtual DbSet<DimWorkItemLinkType> DimWorkItemLinkType { get; set; }
        public virtual DbSet<FactBuildChangeset> FactBuildChangeset { get; set; }
        public virtual DbSet<FactBuildCoverage> FactBuildCoverage { get; set; }
        public virtual DbSet<FactBuildDetails> FactBuildDetails { get; set; }
        public virtual DbSet<FactBuildProject> FactBuildProject { get; set; }
        public virtual DbSet<FactCodeChurn> FactCodeChurn { get; set; }
        public virtual DbSet<FactRunCoverage> FactRunCoverage { get; set; }
        public virtual DbSet<FactTestResult> FactTestResult { get; set; }
        public virtual DbSet<FactWorkItemLinkHistory> FactWorkItemLinkHistory { get; set; }
        public virtual DbSet<FactWorkItemToCategory> FactWorkItemToCategory { get; set; }
        public virtual DbSet<tbl_TransactionMark> tbl_TransactionMark { get; set; }
        public virtual DbSet<C_LastUpdatedTime> C_LastUpdatedTime { get; set; }
        public virtual DbSet<C_WitFields> C_WitFields { get; set; }
        public virtual DbSet<FactCurrentWorkItem> FactCurrentWorkItem { get; set; }
        public virtual DbSet<FactWorkItemChangeset> FactWorkItemChangeset { get; set; }
        public virtual DbSet<FactWorkItemHistory> FactWorkItemHistory { get; set; }
        public virtual DbSet<FactWorkItemTestResult> FactWorkItemTestResult { get; set; }
        public virtual DbSet<C_WarehouseConfig> C_WarehouseConfig { get; set; }
        public virtual DbSet<BuildChangesetView> BuildChangesetView { get; set; }
        public virtual DbSet<BuildCoverageView> BuildCoverageView { get; set; }
        public virtual DbSet<BuildDetailsView> BuildDetailsView { get; set; }
        public virtual DbSet<BuildProjectView> BuildProjectView { get; set; }
        public virtual DbSet<CodeChurnView> CodeChurnView { get; set; }
        public virtual DbSet<CurrentWorkItemView> CurrentWorkItemView { get; set; }
        public virtual DbSet<RunCoverageView> RunCoverageView { get; set; }
        public virtual DbSet<TestResultView> TestResultView { get; set; }
        public virtual DbSet<vDimAreaOverlay> vDimAreaOverlay { get; set; }
        public virtual DbSet<vDimChangesetOverlay> vDimChangesetOverlay { get; set; }
        public virtual DbSet<vDimIterationOverlay> vDimIterationOverlay { get; set; }
        public virtual DbSet<vDimTeamProjectAreaOverlay> vDimTeamProjectAreaOverlay { get; set; }
        public virtual DbSet<vDimTeamProjectIterationOverlay> vDimTeamProjectIterationOverlay { get; set; }
        public virtual DbSet<vDimTeamProjectOverlay> vDimTeamProjectOverlay { get; set; }
        public virtual DbSet<vDimTestCaseOverlay> vDimTestCaseOverlay { get; set; }
        public virtual DbSet<vDimTestPlanOverlay> vDimTestPlanOverlay { get; set; }
        public virtual DbSet<vDimTestResultOverlay> vDimTestResultOverlay { get; set; }
        public virtual DbSet<vDimTestRunOverlay> vDimTestRunOverlay { get; set; }
        public virtual DbSet<vDimWorkItemOverlay> vDimWorkItemOverlay { get; set; }
        public virtual DbSet<vDimWorkItemTreeOverlay> vDimWorkItemTreeOverlay { get; set; }
        public virtual DbSet<vFactLinkedCurrentWorkItem> vFactLinkedCurrentWorkItem { get; set; }
        public virtual DbSet<vFactLinkedCurrentWorkItemTestCase> vFactLinkedCurrentWorkItemTestCase { get; set; }
        public virtual DbSet<vFactTestResultOverlay> vFactTestResultOverlay { get; set; }
        public virtual DbSet<vFactWorkItemChangesetOverlay> vFactWorkItemChangesetOverlay { get; set; }
        public virtual DbSet<vFactWorkItemTestResultOverlay> vFactWorkItemTestResultOverlay { get; set; }
        public virtual DbSet<vFactWorkItemToCategoryOverlay> vFactWorkItemToCategoryOverlay { get; set; }
        public virtual DbSet<vFactWorkItemToTree> vFactWorkItemToTree { get; set; }
        public virtual DbSet<WorkItemHistoryView> WorkItemHistoryView { get; set; }
    
        public virtual int DestroyWorkItems(string workItems, string tpcBK)
        {
            var workItemsParameter = workItems != null ?
                new ObjectParameter("workItems", workItems) :
                new ObjectParameter("workItems", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DestroyWorkItems", workItemsParameter, tpcBKParameter);
        }
    
        [DbFunction("TFSWarehouseEntities", "GetLastUpdatedInfoFromProjectNodeGUID")]
        public virtual IQueryable<GetLastUpdatedInfoFromProjectNodeGUID_Result> GetLastUpdatedInfoFromProjectNodeGUID(Nullable<System.Guid> projectNodeGUID)
        {
            var projectNodeGUIDParameter = projectNodeGUID.HasValue ?
                new ObjectParameter("projectNodeGUID", projectNodeGUID) :
                new ObjectParameter("projectNodeGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetLastUpdatedInfoFromProjectNodeGUID_Result>("[TFSWarehouseEntities].[GetLastUpdatedInfoFromProjectNodeGUID](@projectNodeGUID)", projectNodeGUIDParameter);
        }
    
        [DbFunction("TFSWarehouseEntities", "GetProjectNodeInfoFromReportFolder")]
        public virtual IQueryable<GetProjectNodeInfoFromReportFolder_Result> GetProjectNodeInfoFromReportFolder(string reportingServicesReportFolder)
        {
            var reportingServicesReportFolderParameter = reportingServicesReportFolder != null ?
                new ObjectParameter("reportingServicesReportFolder", reportingServicesReportFolder) :
                new ObjectParameter("reportingServicesReportFolder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetProjectNodeInfoFromReportFolder_Result>("[TFSWarehouseEntities].[GetProjectNodeInfoFromReportFolder](@reportingServicesReportFolder)", reportingServicesReportFolderParameter);
        }
    
        [DbFunction("TFSWarehouseEntities", "GetWorkItemsForLinkPath")]
        public virtual IQueryable<GetWorkItemsForLinkPath_Result> GetWorkItemsForLinkPath(Nullable<System.Guid> projectCollectionGUID, string workItemIdList, string linkPath, Nullable<System.DateTime> asOfDate, Nullable<int> maxHops)
        {
            var projectCollectionGUIDParameter = projectCollectionGUID.HasValue ?
                new ObjectParameter("projectCollectionGUID", projectCollectionGUID) :
                new ObjectParameter("projectCollectionGUID", typeof(System.Guid));
    
            var workItemIdListParameter = workItemIdList != null ?
                new ObjectParameter("workItemIdList", workItemIdList) :
                new ObjectParameter("workItemIdList", typeof(string));
    
            var linkPathParameter = linkPath != null ?
                new ObjectParameter("linkPath", linkPath) :
                new ObjectParameter("linkPath", typeof(string));
    
            var asOfDateParameter = asOfDate.HasValue ?
                new ObjectParameter("asOfDate", asOfDate) :
                new ObjectParameter("asOfDate", typeof(System.DateTime));
    
            var maxHopsParameter = maxHops.HasValue ?
                new ObjectParameter("maxHops", maxHops) :
                new ObjectParameter("maxHops", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetWorkItemsForLinkPath_Result>("[TFSWarehouseEntities].[GetWorkItemsForLinkPath](@projectCollectionGUID, @workItemIdList, @linkPath, @asOfDate, @maxHops)", projectCollectionGUIDParameter, workItemIdListParameter, linkPathParameter, asOfDateParameter, maxHopsParameter);
        }
    
        [DbFunction("TFSWarehouseEntities", "GetWorkItemsForLinkPathXml")]
        public virtual IQueryable<GetWorkItemsForLinkPathXml_Result> GetWorkItemsForLinkPathXml(Nullable<System.Guid> projectCollectionGUID, string workItemIdList, string linkPath, Nullable<System.DateTime> asOfDate, Nullable<int> maxHops)
        {
            var projectCollectionGUIDParameter = projectCollectionGUID.HasValue ?
                new ObjectParameter("projectCollectionGUID", projectCollectionGUID) :
                new ObjectParameter("projectCollectionGUID", typeof(System.Guid));
    
            var workItemIdListParameter = workItemIdList != null ?
                new ObjectParameter("workItemIdList", workItemIdList) :
                new ObjectParameter("workItemIdList", typeof(string));
    
            var linkPathParameter = linkPath != null ?
                new ObjectParameter("linkPath", linkPath) :
                new ObjectParameter("linkPath", typeof(string));
    
            var asOfDateParameter = asOfDate.HasValue ?
                new ObjectParameter("asOfDate", asOfDate) :
                new ObjectParameter("asOfDate", typeof(System.DateTime));
    
            var maxHopsParameter = maxHops.HasValue ?
                new ObjectParameter("maxHops", maxHops) :
                new ObjectParameter("maxHops", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetWorkItemsForLinkPathXml_Result>("[TFSWarehouseEntities].[GetWorkItemsForLinkPathXml](@projectCollectionGUID, @workItemIdList, @linkPath, @asOfDate, @maxHops)", projectCollectionGUIDParameter, workItemIdListParameter, linkPathParameter, asOfDateParameter, maxHopsParameter);
        }
    
        [DbFunction("TFSWarehouseEntities", "GetWorkItemsTree")]
        public virtual IQueryable<GetWorkItemsTree_Result> GetWorkItemsTree(Nullable<System.Guid> projectCollectionGUID, string workItemIdList, string linkName, Nullable<System.DateTime> asOfDate)
        {
            var projectCollectionGUIDParameter = projectCollectionGUID.HasValue ?
                new ObjectParameter("projectCollectionGUID", projectCollectionGUID) :
                new ObjectParameter("projectCollectionGUID", typeof(System.Guid));
    
            var workItemIdListParameter = workItemIdList != null ?
                new ObjectParameter("workItemIdList", workItemIdList) :
                new ObjectParameter("workItemIdList", typeof(string));
    
            var linkNameParameter = linkName != null ?
                new ObjectParameter("linkName", linkName) :
                new ObjectParameter("linkName", typeof(string));
    
            var asOfDateParameter = asOfDate.HasValue ?
                new ObjectParameter("asOfDate", asOfDate) :
                new ObjectParameter("asOfDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetWorkItemsTree_Result>("[TFSWarehouseEntities].[GetWorkItemsTree](@projectCollectionGUID, @workItemIdList, @linkName, @asOfDate)", projectCollectionGUIDParameter, workItemIdListParameter, linkNameParameter, asOfDateParameter);
        }
    
        [DbFunction("TFSWarehouseEntities", "GetWorkItemsTreeXml")]
        public virtual IQueryable<GetWorkItemsTreeXml_Result> GetWorkItemsTreeXml(Nullable<System.Guid> projectCollectionGUID, string workItemIdXml, string linkName, Nullable<System.DateTime> asOfDate)
        {
            var projectCollectionGUIDParameter = projectCollectionGUID.HasValue ?
                new ObjectParameter("projectCollectionGUID", projectCollectionGUID) :
                new ObjectParameter("projectCollectionGUID", typeof(System.Guid));
    
            var workItemIdXmlParameter = workItemIdXml != null ?
                new ObjectParameter("workItemIdXml", workItemIdXml) :
                new ObjectParameter("workItemIdXml", typeof(string));
    
            var linkNameParameter = linkName != null ?
                new ObjectParameter("linkName", linkName) :
                new ObjectParameter("linkName", typeof(string));
    
            var asOfDateParameter = asOfDate.HasValue ?
                new ObjectParameter("asOfDate", asOfDate) :
                new ObjectParameter("asOfDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetWorkItemsTreeXml_Result>("[TFSWarehouseEntities].[GetWorkItemsTreeXml](@projectCollectionGUID, @workItemIdXml, @linkName, @asOfDate)", projectCollectionGUIDParameter, workItemIdXmlParameter, linkNameParameter, asOfDateParameter);
        }
    
        public virtual int LinkData_AddUpdate(string linkDataSet, string linkTypeDataSet, string tpcBK)
        {
            var linkDataSetParameter = linkDataSet != null ?
                new ObjectParameter("linkDataSet", linkDataSet) :
                new ObjectParameter("linkDataSet", typeof(string));
    
            var linkTypeDataSetParameter = linkTypeDataSet != null ?
                new ObjectParameter("linkTypeDataSet", linkTypeDataSet) :
                new ObjectParameter("linkTypeDataSet", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LinkData_AddUpdate", linkDataSetParameter, linkTypeDataSetParameter, tpcBKParameter);
        }
    
        public virtual int prc_ChangeHostId(Nullable<System.Guid> targetHostId)
        {
            var targetHostIdParameter = targetHostId.HasValue ?
                new ObjectParameter("targetHostId", targetHostId) :
                new ObjectParameter("targetHostId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_ChangeHostId", targetHostIdParameter);
        }
    
        public virtual int prc_DestroyPlans(string plans, string tpcBK)
        {
            var plansParameter = plans != null ?
                new ObjectParameter("plans", plans) :
                new ObjectParameter("plans", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_DestroyPlans", plansParameter, tpcBKParameter);
        }
    
        public virtual int prc_DestroyPoints(string points, string tpcBK)
        {
            var pointsParameter = points != null ?
                new ObjectParameter("points", points) :
                new ObjectParameter("points", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_DestroyPoints", pointsParameter, tpcBKParameter);
        }
    
        public virtual int prc_DestroyResults(string data, Nullable<byte> format, string tpcBK, Nullable<int> limit)
        {
            var dataParameter = data != null ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(string));
    
            var formatParameter = format.HasValue ?
                new ObjectParameter("format", format) :
                new ObjectParameter("format", typeof(byte));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            var limitParameter = limit.HasValue ?
                new ObjectParameter("limit", limit) :
                new ObjectParameter("limit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_DestroyResults", dataParameter, formatParameter, tpcBKParameter, limitParameter);
        }
    
        public virtual int prc_DestroySuites(string suites, string tpcBK)
        {
            var suitesParameter = suites != null ?
                new ObjectParameter("suites", suites) :
                new ObjectParameter("suites", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_DestroySuites", suitesParameter, tpcBKParameter);
        }
    
        public virtual int prc_Dimension_DimArea_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimArea_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimArea_Find(string areaGUID, ObjectParameter memberExists)
        {
            var areaGUIDParameter = areaGUID != null ?
                new ObjectParameter("AreaGUID", areaGUID) :
                new ObjectParameter("AreaGUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimArea_Find", areaGUIDParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimArea_SetPaths(string dataSet)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimArea_SetPaths", dataSetParameter);
        }
    
        public virtual int prc_Dimension_DimArea_UpdateOverlay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimArea_UpdateOverlay");
        }
    
        public virtual int prc_Dimension_DimAssembly_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimAssembly_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimAssembly_Find(string assemblyBK, ObjectParameter memberExists)
        {
            var assemblyBKParameter = assemblyBK != null ?
                new ObjectParameter("AssemblyBK", assemblyBK) :
                new ObjectParameter("AssemblyBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimAssembly_Find", assemblyBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimBuild_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimBuild_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimBuild_Find(string buildBK, ObjectParameter memberExists)
        {
            var buildBKParameter = buildBK != null ?
                new ObjectParameter("BuildBK", buildBK) :
                new ObjectParameter("BuildBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimBuild_Find", buildBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimBuildFlavor_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimBuildFlavor_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimBuildFlavor_Find(string buildFlavorName, ObjectParameter memberExists)
        {
            var buildFlavorNameParameter = buildFlavorName != null ?
                new ObjectParameter("BuildFlavorName", buildFlavorName) :
                new ObjectParameter("BuildFlavorName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimBuildFlavor_Find", buildFlavorNameParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimBuildPlatform_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimBuildPlatform_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimBuildPlatform_Find(string buildPlatformName, ObjectParameter memberExists)
        {
            var buildPlatformNameParameter = buildPlatformName != null ?
                new ObjectParameter("BuildPlatformName", buildPlatformName) :
                new ObjectParameter("BuildPlatformName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimBuildPlatform_Find", buildPlatformNameParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimBuildQuality_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimBuildQuality_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimBuildQuality_Find(string buildQualityName, ObjectParameter memberExists)
        {
            var buildQualityNameParameter = buildQualityName != null ?
                new ObjectParameter("BuildQualityName", buildQualityName) :
                new ObjectParameter("BuildQualityName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimBuildQuality_Find", buildQualityNameParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimBuildStatus_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimBuildStatus_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimBuildStatus_Find(string buildStatusName, ObjectParameter memberExists)
        {
            var buildStatusNameParameter = buildStatusName != null ?
                new ObjectParameter("BuildStatusName", buildStatusName) :
                new ObjectParameter("BuildStatusName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimBuildStatus_Find", buildStatusNameParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimChangeset_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimChangeset_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimChangeset_Find(string changesetBK, ObjectParameter memberExists)
        {
            var changesetBKParameter = changesetBK != null ?
                new ObjectParameter("ChangesetBK", changesetBK) :
                new ObjectParameter("ChangesetBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimChangeset_Find", changesetBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimCodeElement_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimCodeElement_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimCodeElement_Find(string codeElementBK, ObjectParameter memberExists)
        {
            var codeElementBKParameter = codeElementBK != null ?
                new ObjectParameter("CodeElementBK", codeElementBK) :
                new ObjectParameter("CodeElementBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimCodeElement_Find", codeElementBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimConfiguration_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimConfiguration_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimConfiguration_Find(string configurationBK, ObjectParameter memberExists)
        {
            var configurationBKParameter = configurationBK != null ?
                new ObjectParameter("ConfigurationBK", configurationBK) :
                new ObjectParameter("ConfigurationBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimConfiguration_Find", configurationBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimDate_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimDate_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimDate_Find(Nullable<System.DateTime> dateTime, ObjectParameter memberExists)
        {
            var dateTimeParameter = dateTime.HasValue ?
                new ObjectParameter("DateTime", dateTime) :
                new ObjectParameter("DateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimDate_Find", dateTimeParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimFile_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimFile_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimFile_Find(string fileBK, ObjectParameter memberExists)
        {
            var fileBKParameter = fileBK != null ?
                new ObjectParameter("FileBK", fileBK) :
                new ObjectParameter("FileBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimFile_Find", fileBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimIteration_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimIteration_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimIteration_Find(string iterationGUID, ObjectParameter memberExists)
        {
            var iterationGUIDParameter = iterationGUID != null ?
                new ObjectParameter("IterationGUID", iterationGUID) :
                new ObjectParameter("IterationGUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimIteration_Find", iterationGUIDParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimIteration_SetPaths(string dataSet)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimIteration_SetPaths", dataSetParameter);
        }
    
        public virtual int prc_Dimension_DimIteration_UpdateOverlay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimIteration_UpdateOverlay");
        }
    
        public virtual int prc_Dimension_DimMachine_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimMachine_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimMachine_Find(string machine, ObjectParameter memberExists)
        {
            var machineParameter = machine != null ?
                new ObjectParameter("Machine", machine) :
                new ObjectParameter("Machine", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimMachine_Find", machineParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimPerson_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimPerson_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimPerson_Find(string sID, ObjectParameter memberExists)
        {
            var sIDParameter = sID != null ?
                new ObjectParameter("SID", sID) :
                new ObjectParameter("SID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimPerson_Find", sIDParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimTeamProject_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTeamProject_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimTeamProject_Find(Nullable<System.Guid> projectNodeGUID, ObjectParameter memberExists)
        {
            var projectNodeGUIDParameter = projectNodeGUID.HasValue ?
                new ObjectParameter("ProjectNodeGUID", projectNodeGUID) :
                new ObjectParameter("ProjectNodeGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTeamProject_Find", projectNodeGUIDParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimTeamProject_SetPaths(string dataSet)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTeamProject_SetPaths", dataSetParameter);
        }
    
        public virtual int prc_Dimension_DimTestCase_UpdateOverlay(ObjectParameter actionPerformed)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTestCase_UpdateOverlay", actionPerformed);
        }
    
        public virtual int prc_Dimension_DimTestPlan_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTestPlan_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimTestPlan_Find(string testPlanBK, ObjectParameter memberExists)
        {
            var testPlanBKParameter = testPlanBK != null ?
                new ObjectParameter("TestPlanBK", testPlanBK) :
                new ObjectParameter("TestPlanBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTestPlan_Find", testPlanBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimTestResult_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTestResult_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimTestResult_Find(string resultBK, ObjectParameter memberExists)
        {
            var resultBKParameter = resultBK != null ?
                new ObjectParameter("ResultBK", resultBK) :
                new ObjectParameter("ResultBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTestResult_Find", resultBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimTestResultAttributes_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTestResultAttributes_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimTestResultAttributes_Find(string resultAttributeBK, ObjectParameter memberExists)
        {
            var resultAttributeBKParameter = resultAttributeBK != null ?
                new ObjectParameter("ResultAttributeBK", resultAttributeBK) :
                new ObjectParameter("ResultAttributeBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTestResultAttributes_Find", resultAttributeBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimTestRun_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTestRun_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimTestRun_Find(string testRunBK, ObjectParameter memberExists)
        {
            var testRunBKParameter = testRunBK != null ?
                new ObjectParameter("TestRunBK", testRunBK) :
                new ObjectParameter("TestRunBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTestRun_Find", testRunBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimTestSuite_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTestSuite_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimTestSuite_Find(string testSuiteBK, ObjectParameter memberExists)
        {
            var testSuiteBKParameter = testSuiteBK != null ?
                new ObjectParameter("TestSuiteBK", testSuiteBK) :
                new ObjectParameter("TestSuiteBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimTestSuite_Find", testSuiteBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimToday_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimToday_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimToday_Find(Nullable<int> index, ObjectParameter memberExists)
        {
            var indexParameter = index.HasValue ?
                new ObjectParameter("Index", index) :
                new ObjectParameter("Index", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimToday_Find", indexParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimToolArtifactDisplayUrl_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimToolArtifactDisplayUrl_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimToolArtifactDisplayUrl_Find(string toolArtifactDisplayUrlBK, ObjectParameter memberExists)
        {
            var toolArtifactDisplayUrlBKParameter = toolArtifactDisplayUrlBK != null ?
                new ObjectParameter("ToolArtifactDisplayUrlBK", toolArtifactDisplayUrlBK) :
                new ObjectParameter("ToolArtifactDisplayUrlBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimToolArtifactDisplayUrl_Find", toolArtifactDisplayUrlBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimWorkItem_AddUpdate(string dataSet, string tpcBK, string batchConstIds, Nullable<int> fieldId)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            var batchConstIdsParameter = batchConstIds != null ?
                new ObjectParameter("batchConstIds", batchConstIds) :
                new ObjectParameter("batchConstIds", typeof(string));
    
            var fieldIdParameter = fieldId.HasValue ?
                new ObjectParameter("fieldId", fieldId) :
                new ObjectParameter("fieldId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimWorkItem_AddUpdate", dataSetParameter, tpcBKParameter, batchConstIdsParameter, fieldIdParameter);
        }
    
        public virtual int prc_Dimension_DimWorkItemCategory_AddUpdate(string referenceName, string displayName, string projectName, string projectGuid, string tpcBK, Nullable<int> fDeleted)
        {
            var referenceNameParameter = referenceName != null ?
                new ObjectParameter("referenceName", referenceName) :
                new ObjectParameter("referenceName", typeof(string));
    
            var displayNameParameter = displayName != null ?
                new ObjectParameter("displayName", displayName) :
                new ObjectParameter("displayName", typeof(string));
    
            var projectNameParameter = projectName != null ?
                new ObjectParameter("projectName", projectName) :
                new ObjectParameter("projectName", typeof(string));
    
            var projectGuidParameter = projectGuid != null ?
                new ObjectParameter("projectGuid", projectGuid) :
                new ObjectParameter("projectGuid", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            var fDeletedParameter = fDeleted.HasValue ?
                new ObjectParameter("fDeleted", fDeleted) :
                new ObjectParameter("fDeleted", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimWorkItemCategory_AddUpdate", referenceNameParameter, displayNameParameter, projectNameParameter, projectGuidParameter, tpcBKParameter, fDeletedParameter);
        }
    
        public virtual int prc_Dimension_DimWorkItemCategory_Find(string workItemCategoryBK, ObjectParameter memberExists)
        {
            var workItemCategoryBKParameter = workItemCategoryBK != null ?
                new ObjectParameter("WorkItemCategoryBK", workItemCategoryBK) :
                new ObjectParameter("WorkItemCategoryBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimWorkItemCategory_Find", workItemCategoryBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_DimWorkItemLinkType_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimWorkItemLinkType_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_DimWorkItemLinkType_Find(string workItemLinkTypeBK, ObjectParameter memberExists)
        {
            var workItemLinkTypeBKParameter = workItemLinkTypeBK != null ?
                new ObjectParameter("WorkItemLinkTypeBK", workItemLinkTypeBK) :
                new ObjectParameter("WorkItemLinkTypeBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_DimWorkItemLinkType_Find", workItemLinkTypeBKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_vDimTestCaseOverlay_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_vDimTestCaseOverlay_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_vDimTestCaseOverlay_Find(Nullable<int> workItemSK, ObjectParameter memberExists)
        {
            var workItemSKParameter = workItemSK.HasValue ?
                new ObjectParameter("WorkItemSK", workItemSK) :
                new ObjectParameter("WorkItemSK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_vDimTestCaseOverlay_Find", workItemSKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_vDimWorkItemOverlay_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_vDimWorkItemOverlay_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_vDimWorkItemOverlay_Find(Nullable<int> workItemSK, ObjectParameter memberExists)
        {
            var workItemSKParameter = workItemSK.HasValue ?
                new ObjectParameter("WorkItemSK", workItemSK) :
                new ObjectParameter("WorkItemSK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_vDimWorkItemOverlay_Find", workItemSKParameter, memberExists);
        }
    
        public virtual int prc_Dimension_vDimWorkItemTreeOverlay_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_vDimWorkItemTreeOverlay_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Dimension_vDimWorkItemTreeOverlay_Find(Nullable<int> workItemTreeSK, ObjectParameter memberExists)
        {
            var workItemTreeSKParameter = workItemTreeSK.HasValue ?
                new ObjectParameter("WorkItemTreeSK", workItemTreeSK) :
                new ObjectParameter("WorkItemTreeSK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Dimension_vDimWorkItemTreeOverlay_Find", workItemTreeSKParameter, memberExists);
        }
    
        public virtual int prc_EnablePrefixCompression(Nullable<bool> online, Nullable<bool> disable)
        {
            var onlineParameter = online.HasValue ?
                new ObjectParameter("online", online) :
                new ObjectParameter("online", typeof(bool));
    
            var disableParameter = disable.HasValue ?
                new ObjectParameter("disable", disable) :
                new ObjectParameter("disable", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_EnablePrefixCompression", onlineParameter, disableParameter);
        }
    
        public virtual int prc_Fact_FactBuildChangeset_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Fact_FactBuildChangeset_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Fact_FactBuildCoverage_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Fact_FactBuildCoverage_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Fact_FactBuildDetails_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Fact_FactBuildDetails_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Fact_FactBuildProject_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Fact_FactBuildProject_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Fact_FactCodeChurn_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Fact_FactCodeChurn_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Fact_FactRunCoverage_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Fact_FactRunCoverage_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Fact_FactTestResult_AddUpdate(string dataSet, Nullable<bool> update)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var updateParameter = update.HasValue ?
                new ObjectParameter("update", update) :
                new ObjectParameter("update", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Fact_FactTestResult_AddUpdate", dataSetParameter, updateParameter);
        }
    
        public virtual int prc_Fact_FactWorkItem_AddUpdate(string dataSet, string tpcBK, Nullable<int> fieldId)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            var fieldIdParameter = fieldId.HasValue ?
                new ObjectParameter("fieldId", fieldId) :
                new ObjectParameter("fieldId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Fact_FactWorkItem_AddUpdate", dataSetParameter, tpcBKParameter, fieldIdParameter);
        }
    
        public virtual int prc_Fact_WorkItemToCategory_AddUpdate(string categoryReferenceName, string projectName, string projectGuid, string tpcBK, string typeName, Nullable<int> fDeleted)
        {
            var categoryReferenceNameParameter = categoryReferenceName != null ?
                new ObjectParameter("categoryReferenceName", categoryReferenceName) :
                new ObjectParameter("categoryReferenceName", typeof(string));
    
            var projectNameParameter = projectName != null ?
                new ObjectParameter("projectName", projectName) :
                new ObjectParameter("projectName", typeof(string));
    
            var projectGuidParameter = projectGuid != null ?
                new ObjectParameter("projectGuid", projectGuid) :
                new ObjectParameter("projectGuid", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            var typeNameParameter = typeName != null ?
                new ObjectParameter("typeName", typeName) :
                new ObjectParameter("typeName", typeof(string));
    
            var fDeletedParameter = fDeleted.HasValue ?
                new ObjectParameter("fDeleted", fDeleted) :
                new ObjectParameter("fDeleted", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Fact_WorkItemToCategory_AddUpdate", categoryReferenceNameParameter, projectNameParameter, projectGuidParameter, tpcBKParameter, typeNameParameter, fDeletedParameter);
        }
    
        public virtual int prc_Get_Boundary_Entries_For_Date_Dimension(ObjectParameter minDate, ObjectParameter maxDate)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Get_Boundary_Entries_For_Date_Dimension", minDate, maxDate);
        }
    
        public virtual int prc_Get_Date_Count(ObjectParameter dateCount)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Get_Date_Count", dateCount);
        }
    
        public virtual int prc_LastUpdatedTime_DeleteAllJobs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_LastUpdatedTime_DeleteAllJobs");
        }
    
        public virtual int prc_LastUpdatedTime_DeleteCollectionJobs(Nullable<System.Guid> collectionId)
        {
            var collectionIdParameter = collectionId.HasValue ?
                new ObjectParameter("CollectionId", collectionId) :
                new ObjectParameter("CollectionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_LastUpdatedTime_DeleteCollectionJobs", collectionIdParameter);
        }
    
        public virtual int prc_LastUpdatedTime_Set_AnalysisLastUpdated()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_LastUpdatedTime_Set_AnalysisLastUpdated");
        }
    
        public virtual int prc_LastUpdatedTime_Set_EnabledState(Nullable<System.Guid> collectionId, string jobName, Nullable<int> enabledState)
        {
            var collectionIdParameter = collectionId.HasValue ?
                new ObjectParameter("CollectionId", collectionId) :
                new ObjectParameter("CollectionId", typeof(System.Guid));
    
            var jobNameParameter = jobName != null ?
                new ObjectParameter("JobName", jobName) :
                new ObjectParameter("JobName", typeof(string));
    
            var enabledStateParameter = enabledState.HasValue ?
                new ObjectParameter("EnabledState", enabledState) :
                new ObjectParameter("EnabledState", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_LastUpdatedTime_Set_EnabledState", collectionIdParameter, jobNameParameter, enabledStateParameter);
        }
    
        public virtual int prc_LastUpdatedTime_Set_SnapshotLastUpdated()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_LastUpdatedTime_Set_SnapshotLastUpdated");
        }
    
        public virtual int prc_LastUpdatedTime_Set_WarehouseLastUpdated(string collectionName, Nullable<System.Guid> collectionId, string jobName, Nullable<System.Guid> jobId, Nullable<int> enabledState, Nullable<System.DateTime> warehouseLastUpdated)
        {
            var collectionNameParameter = collectionName != null ?
                new ObjectParameter("CollectionName", collectionName) :
                new ObjectParameter("CollectionName", typeof(string));
    
            var collectionIdParameter = collectionId.HasValue ?
                new ObjectParameter("CollectionId", collectionId) :
                new ObjectParameter("CollectionId", typeof(System.Guid));
    
            var jobNameParameter = jobName != null ?
                new ObjectParameter("JobName", jobName) :
                new ObjectParameter("JobName", typeof(string));
    
            var jobIdParameter = jobId.HasValue ?
                new ObjectParameter("JobId", jobId) :
                new ObjectParameter("JobId", typeof(System.Guid));
    
            var enabledStateParameter = enabledState.HasValue ?
                new ObjectParameter("EnabledState", enabledState) :
                new ObjectParameter("EnabledState", typeof(int));
    
            var warehouseLastUpdatedParameter = warehouseLastUpdated.HasValue ?
                new ObjectParameter("WarehouseLastUpdated", warehouseLastUpdated) :
                new ObjectParameter("WarehouseLastUpdated", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_LastUpdatedTime_Set_WarehouseLastUpdated", collectionNameParameter, collectionIdParameter, jobNameParameter, jobIdParameter, enabledStateParameter, warehouseLastUpdatedParameter);
        }
    
        public virtual int prc_LastUpdatedTime_Set_Warning(string collectionName, Nullable<System.Guid> collectionId, string jobName, Nullable<System.Guid> jobId, Nullable<int> enabledState, string warning)
        {
            var collectionNameParameter = collectionName != null ?
                new ObjectParameter("CollectionName", collectionName) :
                new ObjectParameter("CollectionName", typeof(string));
    
            var collectionIdParameter = collectionId.HasValue ?
                new ObjectParameter("CollectionId", collectionId) :
                new ObjectParameter("CollectionId", typeof(System.Guid));
    
            var jobNameParameter = jobName != null ?
                new ObjectParameter("JobName", jobName) :
                new ObjectParameter("JobName", typeof(string));
    
            var jobIdParameter = jobId.HasValue ?
                new ObjectParameter("JobId", jobId) :
                new ObjectParameter("JobId", typeof(System.Guid));
    
            var enabledStateParameter = enabledState.HasValue ?
                new ObjectParameter("EnabledState", enabledState) :
                new ObjectParameter("EnabledState", typeof(int));
    
            var warningParameter = warning != null ?
                new ObjectParameter("Warning", warning) :
                new ObjectParameter("Warning", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_LastUpdatedTime_Set_Warning", collectionNameParameter, collectionIdParameter, jobNameParameter, jobIdParameter, enabledStateParameter, warningParameter);
        }
    
        public virtual int prc_OptimizeDatabase()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_OptimizeDatabase");
        }
    
        public virtual int prc_OptimizeTableStats()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_OptimizeTableStats");
        }
    
        public virtual int prc_PropertyBag_Delete(string property_Scope, string property_Key)
        {
            var property_ScopeParameter = property_Scope != null ?
                new ObjectParameter("Property_Scope", property_Scope) :
                new ObjectParameter("Property_Scope", typeof(string));
    
            var property_KeyParameter = property_Key != null ?
                new ObjectParameter("Property_Key", property_Key) :
                new ObjectParameter("Property_Key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_PropertyBag_Delete", property_ScopeParameter, property_KeyParameter);
        }
    
        public virtual int prc_PropertyBag_Get(string property_Scope, string property_Key, ObjectParameter property_Value)
        {
            var property_ScopeParameter = property_Scope != null ?
                new ObjectParameter("Property_Scope", property_Scope) :
                new ObjectParameter("Property_Scope", typeof(string));
    
            var property_KeyParameter = property_Key != null ?
                new ObjectParameter("Property_Key", property_Key) :
                new ObjectParameter("Property_Key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_PropertyBag_Get", property_ScopeParameter, property_KeyParameter, property_Value);
        }
    
        public virtual int prc_PropertyBag_Set(string property_Scope, string property_Key, string property_Value)
        {
            var property_ScopeParameter = property_Scope != null ?
                new ObjectParameter("Property_Scope", property_Scope) :
                new ObjectParameter("Property_Scope", typeof(string));
    
            var property_KeyParameter = property_Key != null ?
                new ObjectParameter("Property_Key", property_Key) :
                new ObjectParameter("Property_Key", typeof(string));
    
            var property_ValueParameter = property_Value != null ?
                new ObjectParameter("Property_Value", property_Value) :
                new ObjectParameter("Property_Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_PropertyBag_Set", property_ScopeParameter, property_KeyParameter, property_ValueParameter);
        }
    
        public virtual int prc_remove_field_data(string table, string field, string tpcBk, Nullable<bool> updateLastUpdatedDateTime)
        {
            var tableParameter = table != null ?
                new ObjectParameter("table", table) :
                new ObjectParameter("table", typeof(string));
    
            var fieldParameter = field != null ?
                new ObjectParameter("field", field) :
                new ObjectParameter("field", typeof(string));
    
            var tpcBkParameter = tpcBk != null ?
                new ObjectParameter("tpcBk", tpcBk) :
                new ObjectParameter("tpcBk", typeof(string));
    
            var updateLastUpdatedDateTimeParameter = updateLastUpdatedDateTime.HasValue ?
                new ObjectParameter("updateLastUpdatedDateTime", updateLastUpdatedDateTime) :
                new ObjectParameter("updateLastUpdatedDateTime", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_remove_field_data", tableParameter, fieldParameter, tpcBkParameter, updateLastUpdatedDateTimeParameter);
        }
    
        public virtual int prc_SetTransactionMark(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_SetTransactionMark", nameParameter);
        }
    
        public virtual int prc_Update_ForwardDeleted_CSS_Nodes(string table, string column, Nullable<int> type)
        {
            var tableParameter = table != null ?
                new ObjectParameter("table", table) :
                new ObjectParameter("table", typeof(string));
    
            var columnParameter = column != null ?
                new ObjectParameter("column", column) :
                new ObjectParameter("column", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_Update_ForwardDeleted_CSS_Nodes", tableParameter, columnParameter, typeParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> prc_WarehouseUpdate_CreateSnapshot()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("prc_WarehouseUpdate_CreateSnapshot");
        }
    
        public virtual ObjectResult<prc_WarehouseUpdate_GetSnapshot_Result> prc_WarehouseUpdate_GetSnapshot()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_WarehouseUpdate_GetSnapshot_Result>("prc_WarehouseUpdate_GetSnapshot");
        }
    
        public virtual int prc_WarehouseUpdate_Update(string iD, Nullable<short> status)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_WarehouseUpdate_Update", iDParameter, statusParameter);
        }
    
        public virtual int RenameWorkItemType(string workItemTypeName, string newWorkItemTypeName, string projectName, string tpcBK)
        {
            var workItemTypeNameParameter = workItemTypeName != null ?
                new ObjectParameter("workItemTypeName", workItemTypeName) :
                new ObjectParameter("workItemTypeName", typeof(string));
    
            var newWorkItemTypeNameParameter = newWorkItemTypeName != null ?
                new ObjectParameter("newWorkItemTypeName", newWorkItemTypeName) :
                new ObjectParameter("newWorkItemTypeName", typeof(string));
    
            var projectNameParameter = projectName != null ?
                new ObjectParameter("projectName", projectName) :
                new ObjectParameter("projectName", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RenameWorkItemType", workItemTypeNameParameter, newWorkItemTypeNameParameter, projectNameParameter, tpcBKParameter);
        }
    
        public virtual int WorkItemChangeSetLinks_AddUpdate(string dataSet, string tpcBK)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WorkItemChangeSetLinks_AddUpdate", dataSetParameter, tpcBKParameter);
        }
    
        public virtual int WorkItemTestResultLinks_AddUpdate(string dataSet, string tpcBK)
        {
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("dataSet", dataSet) :
                new ObjectParameter("dataSet", typeof(string));
    
            var tpcBKParameter = tpcBK != null ?
                new ObjectParameter("tpcBK", tpcBK) :
                new ObjectParameter("tpcBK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WorkItemTestResultLinks_AddUpdate", dataSetParameter, tpcBKParameter);
        }
    }
}
