//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketHistorico
    {
        public TicketHistorico()
        {
            this.historicoInformacionTicket = new HashSet<HistoricoInformacionTicket>();
        }
    
        public int SecuencialTicket { get; set; }
        public int Version { get; set; }
        public int SecuencialEstadoTicket { get; set; }
        public int SecuencialPrioridadTicket { get; set; }
        public int SecuencialCategoriaTicket { get; set; }
        public string Detalle { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public int NumeroVerificador { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public int SecuencialUsuario { get; set; }
        public string Telefono { get; set; }
        public int Estimacion { get; set; }
        public string ReportadoPor { get; set; }
        public decimal Reputacion { get; set; }
        public string Asunto { get; set; }
        public int SecuencialPersona_Cliente { get; set; }
        public decimal Reprocesos { get; set; }
        public bool IngresoInterno { get; set; }
        public bool SeFactura { get; set; }
        public bool Facturado { get; set; }
        public int SecuencialProximaActividad { get; set; }
        public int SecuencialTipoRecurso { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> RequiereTesting { get; set; }
        public Nullable<int> SecuencialCategoriaRevisada { get; set; }
        public Nullable<int> SecuencialPrioridadRevisada { get; set; }
        public Nullable<System.DateTime> FechaRevisado { get; set; }
    
        public virtual CategoriaTicket categoriaTicket { get; set; }
        public virtual EstadoTicket estadoTicket { get; set; }
        public virtual PrioridadTicket prioridadTicket { get; set; }
        public virtual Ticket ticket { get; set; }
        public virtual Usuario usuario { get; set; }
        public virtual Persona_Cliente persona_cliente { get; set; }
        public virtual ICollection<HistoricoInformacionTicket> historicoInformacionTicket { get; set; }
        public virtual ProximaActividad proximaActividad { get; set; }
        public virtual TipoRecurso tipoRecurso { get; set; }
        public virtual CategoriaTicket categoriaRevisadaTicket { get; set; }
        public virtual PrioridadTicket prioridadRevisadaTicket { get; set; }
    }
}
