//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Resolucion
    {
        public Ticket_Resolucion()
        {
            this.ticket_resolucionDesacuerdo = new HashSet<Ticket_ResolucionDesacuerdo>();
        }
    
        public int SecuencialTicket { get; set; }
        public int SecuencialColaborador { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> NumeroVerificador { get; set; }
    
        public virtual Colaborador colaborador { get; set; }
        public virtual Ticket ticket { get; set; }
        public virtual ICollection<Ticket_ResolucionDesacuerdo> ticket_resolucionDesacuerdo { get; set; }
    }
}
