//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTarea
    {
        public TicketTarea()
        {
            this.ticketAsignacionTFS = new HashSet<TicketAsignacionTFS>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialTicket { get; set; }
        public int SecuencialTarea { get; set; }
        public decimal EstaActiva { get; set; }
    
        public virtual Ticket ticket { get; set; }
        public virtual Tarea tarea { get; set; }
        public virtual ICollection<TicketAsignacionTFS> ticketAsignacionTFS { get; set; }
    }
}
