//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_ResolucionDesacuerdo
    {
        public int Secuencial { get; set; }
        public int SecuencialColaborador { get; set; }
        public int SecuencialTicket_Resolucion { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Detalle { get; set; }
    
        public virtual Colaborador colaborador { get; set; }
        public virtual Ticket_Resolucion ticket_resolucion { get; set; }
    }
}
