//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_ContratoCliente
    {
        public int SecuencialTicket { get; set; }
        public int SecuencialContratoCliente { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual ContratoCliente contratoCliente { get; set; }
        public virtual Ticket ticket { get; set; }
    }
}
