//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketMantenimientoAgregar
    {
        public int Secuencial { get; set; }
        public int TicketTarea { get; set; }
        public string Detalle { get; set; }
        public string Reportado { get; set; }
        public string Tecnico { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public int Tiempo { get; set; }
        public string Cliente { get; set; }
    }
}
