//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAsignacionTFS
    {
        public int Secuencial { get; set; }
        public int SecuencialProyectoTFS { get; set; }
        public int SecuencialTicketTarea { get; set; }
        public int WorkItemID { get; set; }
    
        public virtual ProyectoTFS proyectoTFS { get; set; }
        public virtual TicketTarea ticketTarea { get; set; }
    }
}
