//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.adjuntoTicket = new HashSet<AdjuntoTicket>();
            this.ticketHistorico = new HashSet<TicketHistorico>();
            this.ticketFuncionalidad = new HashSet<TicketFuncionalidad>();
            this.ticketTarea = new HashSet<TicketTarea>();
            this.estimacionTicket = new HashSet<EstimacionTicket>();
            this.cotizacionTicket = new HashSet<CotizacionTicket>();
            this.comentarioTicket = new HashSet<ComentarioTicket>();
            this.NotificacionTicket = new HashSet<NotificacionTicket>();
            this.noTerminacionTicket = new HashSet<NoTerminacionTicket>();
            this.motivoPrioridadTicket = new HashSet<MotivoPrioridadTicket>();
            this.motivoTrabajoTicket = new HashSet<MotivoTrabajoTicket>();
            this.TICKETSMANTENIMIENTO = new HashSet<TicketsMantenimiento>();
            this.TICKETMANTENIMIENTOBORAR = new HashSet<TicketMantenimientoBorar>();
            this.ENTREGABLETICKET = new HashSet<EntregableTicket>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialEstadoTicket { get; set; }
        public int SecuencialCategoriaTicket { get; set; }
        public int SecuencialPrioridadTicket { get; set; }
        public string Detalle { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public int NumeroVerificador { get; set; }
        public string Telefono { get; set; }
        public int Estimacion { get; set; }
        public decimal Reputacion { get; set; }
        public string ReportadoPor { get; set; }
        public string Asunto { get; set; }
        public int SecuencialPersona_Cliente { get; set; }
        public decimal Reprocesos { get; set; }
        public bool IngresoInterno { get; set; }
        public bool SeFactura { get; set; }
        public bool Facturado { get; set; }
        public int SecuencialProximaActividad { get; set; }
        public int SecuencialTipoRecurso { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> RequiereTesting { get; set; }
        public Nullable<System.DateTime> FechaRevisado { get; set; }
        public Nullable<int> SecuencialTicketVersionCliente { get; set; }
        public Nullable<int> DiasGarantia { get; set; }
        public Nullable<int> HorasCreado { get; set; }
        public Nullable<int> HorasResolucion { get; set; }
        public Nullable<bool> PendienteAPago { get; set; }
        public Nullable<int> SecuencialModulo { get; set; }
    
        public virtual ICollection<AdjuntoTicket> adjuntoTicket { get; set; }
        public virtual CategoriaTicket categoriaTicket { get; set; }
        public virtual EstadoTicket estadoTicket { get; set; }
        public virtual PrioridadTicket prioridadTicket { get; set; }
        public virtual ICollection<TicketHistorico> ticketHistorico { get; set; }
        public virtual Ticket_ContratoCliente ticket_contratoCliente { get; set; }
        public virtual ICollection<TicketFuncionalidad> ticketFuncionalidad { get; set; }
        public virtual ICollection<TicketTarea> ticketTarea { get; set; }
        public virtual ICollection<EstimacionTicket> estimacionTicket { get; set; }
        public virtual ICollection<CotizacionTicket> cotizacionTicket { get; set; }
        public virtual Persona_Cliente persona_cliente { get; set; }
        public virtual ProximaActividad proximaActividad { get; set; }
        public virtual TipoRecurso tipoRecurso { get; set; }
        public virtual Ticket_Resolucion ticket_resolucion { get; set; }
        public virtual Ticket_Error ticket_error { get; set; }
        public virtual Ticket_PrioridadRevisada ticket_prioridadRevisada { get; set; }
        public virtual Ticket_CategoriaRevisada ticket_categoriaRevisada { get; set; }
        public virtual ICollection<ComentarioTicket> comentarioTicket { get; set; }
        public virtual Ticket_RequierePublicacion ticket_requierePublicacion { get; set; }
        public virtual ICollection<NotificacionTicket> NotificacionTicket { get; set; }
        public virtual ICollection<NoTerminacionTicket> noTerminacionTicket { get; set; }
        public virtual TICKET_COMPLEMENTO TICKET_COMPLEMENTO { get; set; }
        public virtual ICollection<MotivoPrioridadTicket> motivoPrioridadTicket { get; set; }
        public virtual ICollection<MotivoTrabajoTicket> motivoTrabajoTicket { get; set; }
        public virtual ICollection<TicketsMantenimiento> TICKETSMANTENIMIENTO { get; set; }
        public virtual ICollection<TicketMantenimientoBorar> TICKETMANTENIMIENTOBORAR { get; set; }
        public virtual ICollection<EntregableTicket> ENTREGABLETICKET { get; set; }
        public virtual TicketVersionCliente ticketVersionClliente { get; set; }
    }
}
