//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_COMPLEMENTO
    {
        public int SECUENCIALTICKET { get; set; }
        public string TECNICOSUGERIDO { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual Ticket TICKET { get; set; }
    }
}
