//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiemposProyecto
    {
        public int Secuencial { get; set; }
        public int SecuencialServicioImplantacionCore { get; set; }
        public int HorasServicio { get; set; }
        public string Rp { get; set; }
        public int HorasConsumidas { get; set; }
        public string Detalle { get; set; }
        public int SecuencialColaborador { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> SecuencialClienteAuxiliar { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual ServicioImplantacionCore ServicioImplantacionCore { get; set; }
        public virtual ClienteAuxiliar clienteAuxiliar { get; set; }
    }
}
