//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.usuarioRol = new HashSet<UsuarioRol>();
            this.historicoTareaEstado = new HashSet<HistoricoTareaEstado>();
            this.ticketHistorico = new HashSet<TicketHistorico>();
            this.tareaActividadRealizada = new HashSet<TareaActividadRealizada>();
            this.gestion_solicitudTarea = new HashSet<Gestion_SolicitudTarea>();
            this.comentarioTarea = new HashSet<ComentarioTarea>();
            this.gestionPermiso = new HashSet<GestionPermiso>();
            this.colaboradorIncidencia = new HashSet<ColaboradorIncidencia>();
            this.tareaCompensatoria = new HashSet<TareaCompensatoria>();
            this.MENSAJE = new HashSet<Mensaje>();
            this.MENSAJE1 = new HashSet<Mensaje>();
            this.USUARIOLEECOMENTARIOGENERAL = new HashSet<UsuarioLeeComentarioGeneral>();
            this.COMENTARIOGENERAL = new HashSet<ComentarioGeneral>();
            this.motivoTrabajoSeguimiento = new HashSet<MotivoTrabajoSeguimiento>();
        }
    
        public int Secuencial { get; set; }
        public int SecuencialPersona { get; set; }
        public string Passw { get; set; }
        public string Email { get; set; }
        public decimal EstaActivo { get; set; }
        public int NumeroVerificador { get; set; }
    
        public virtual Persona persona { get; set; }
        public virtual ICollection<UsuarioRol> usuarioRol { get; set; }
        public virtual ICollection<HistoricoTareaEstado> historicoTareaEstado { get; set; }
        public virtual ICollection<TicketHistorico> ticketHistorico { get; set; }
        public virtual ICollection<TareaActividadRealizada> tareaActividadRealizada { get; set; }
        public virtual ICollection<Gestion_SolicitudTarea> gestion_solicitudTarea { get; set; }
        public virtual ICollection<ComentarioTarea> comentarioTarea { get; set; }
        public virtual ICollection<GestionPermiso> gestionPermiso { get; set; }
        public virtual ICollection<ColaboradorIncidencia> colaboradorIncidencia { get; set; }
        public virtual ICollection<TareaCompensatoria> tareaCompensatoria { get; set; }
        public virtual ICollection<Mensaje> MENSAJE { get; set; }
        public virtual ICollection<Mensaje> MENSAJE1 { get; set; }
        public virtual ICollection<UsuarioLeeComentarioGeneral> USUARIOLEECOMENTARIOGENERAL { get; set; }
        public virtual ICollection<ComentarioGeneral> COMENTARIOGENERAL { get; set; }
        public virtual ICollection<MotivoTrabajoSeguimiento> motivoTrabajoSeguimiento { get; set; }
    }
}
