//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDimIterationOverlay
    {
        public int IterationSk { get; set; }
        public Nullable<int> ParentIterationSk { get; set; }
        public string IterationProjectGUID { get; set; }
        public string IterationPath { get; set; }
        public Nullable<long> Iteration0GUIDInt1 { get; set; }
        public Nullable<long> Iteration1GUIDInt1 { get; set; }
        public Nullable<long> Iteration2GUIDInt1 { get; set; }
        public Nullable<long> Iteration3GUIDInt1 { get; set; }
        public Nullable<long> Iteration4GUIDInt1 { get; set; }
        public Nullable<long> Iteration5GUIDInt1 { get; set; }
        public Nullable<long> Iteration6GUIDInt1 { get; set; }
        public Nullable<long> Iteration7GUIDInt1 { get; set; }
        public Nullable<long> Iteration8GUIDInt1 { get; set; }
        public Nullable<long> Iteration9GUIDInt1 { get; set; }
        public Nullable<long> Iteration10GUIDInt1 { get; set; }
        public Nullable<long> Iteration11GUIDInt1 { get; set; }
        public Nullable<long> Iteration12GUIDInt1 { get; set; }
        public Nullable<long> Iteration13GUIDInt1 { get; set; }
        public Nullable<long> Iteration0GUIDInt2 { get; set; }
        public Nullable<long> Iteration1GUIDInt2 { get; set; }
        public Nullable<long> Iteration2GUIDInt2 { get; set; }
        public Nullable<long> Iteration3GUIDInt2 { get; set; }
        public Nullable<long> Iteration4GUIDInt2 { get; set; }
        public Nullable<long> Iteration5GUIDInt2 { get; set; }
        public Nullable<long> Iteration6GUIDInt2 { get; set; }
        public Nullable<long> Iteration7GUIDInt2 { get; set; }
        public Nullable<long> Iteration8GUIDInt2 { get; set; }
        public Nullable<long> Iteration9GUIDInt2 { get; set; }
        public Nullable<long> Iteration10GUIDInt2 { get; set; }
        public Nullable<long> Iteration11GUIDInt2 { get; set; }
        public Nullable<long> Iteration12GUIDInt2 { get; set; }
        public Nullable<long> Iteration13GUIDInt2 { get; set; }
        public string IterationLevel0 { get; set; }
        public string IterationLevel1 { get; set; }
        public string IterationLevel2 { get; set; }
        public string IterationLevel3 { get; set; }
        public string IterationLevel4 { get; set; }
        public string IterationLevel5 { get; set; }
        public string IterationLevel6 { get; set; }
        public string IterationLevel7 { get; set; }
        public string IterationLevel8 { get; set; }
        public string IterationLevel9 { get; set; }
        public string IterationLevel10 { get; set; }
        public string IterationLevel11 { get; set; }
        public string IterationLevel12 { get; set; }
        public string IterationLevel13 { get; set; }
    }
}
