//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDimTestResultOverlay
    {
        public int ResultSK { get; set; }
        public string Outcome { get; set; }
        public Nullable<byte> OutcomeId { get; set; }
        public string FailureType { get; set; }
        public Nullable<byte> FailureTypeId { get; set; }
        public string ResolutionState { get; set; }
        public string ReadinessState { get; set; }
        public Nullable<byte> ReadinessStateId { get; set; }
        public Nullable<byte> Priority { get; set; }
        public string Owner__Name { get; set; }
        public string Owner__SID { get; set; }
        public string ExecutedBy__Name { get; set; }
        public string ExecutedBy__SID { get; set; }
        public string ResultBK { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    }
}
