//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDimTeamProjectAreaOverlay
    {
        public int AreaSk { get; set; }
        public string AreaPath { get; set; }
        public Nullable<long> Area0GUIDInt1 { get; set; }
        public Nullable<long> Area0GUIDInt2 { get; set; }
        public string AreaLevel0 { get; set; }
        public Nullable<long> Area1GUIDInt1 { get; set; }
        public Nullable<long> Area1GUIDInt2 { get; set; }
        public string AreaLevel1 { get; set; }
        public Nullable<long> Area2GUIDInt1 { get; set; }
        public Nullable<long> Area2GUIDInt2 { get; set; }
        public string AreaLevel2 { get; set; }
        public Nullable<long> Area3GUIDInt1 { get; set; }
        public Nullable<long> Area3GUIDInt2 { get; set; }
        public string AreaLevel3 { get; set; }
        public Nullable<long> Area4GUIDInt1 { get; set; }
        public Nullable<long> Area4GUIDInt2 { get; set; }
        public string AreaLevel4 { get; set; }
        public Nullable<long> Area5GUIDInt1 { get; set; }
        public Nullable<long> Area5GUIDInt2 { get; set; }
        public string AreaLevel5 { get; set; }
        public Nullable<long> Area6GUIDInt1 { get; set; }
        public Nullable<long> Area6GUIDInt2 { get; set; }
        public string AreaLevel6 { get; set; }
        public Nullable<long> Area7GUIDInt1 { get; set; }
        public Nullable<long> Area7GUIDInt2 { get; set; }
        public string AreaLevel7 { get; set; }
        public Nullable<long> Area8GUIDInt1 { get; set; }
        public Nullable<long> Area8GUIDInt2 { get; set; }
        public string AreaLevel8 { get; set; }
        public Nullable<long> Area9GUIDInt1 { get; set; }
        public Nullable<long> Area9GUIDInt2 { get; set; }
        public string AreaLevel9 { get; set; }
        public Nullable<long> Area10GUIDInt1 { get; set; }
        public Nullable<long> Area10GUIDInt2 { get; set; }
        public string AreaLevel10 { get; set; }
        public Nullable<long> Area11GUIDInt1 { get; set; }
        public Nullable<long> Area11GUIDInt2 { get; set; }
        public string AreaLevel11 { get; set; }
        public Nullable<long> Area12GUIDInt1 { get; set; }
        public Nullable<long> Area12GUIDInt2 { get; set; }
        public string AreaLevel12 { get; set; }
        public Nullable<long> Area13GUIDInt1 { get; set; }
        public Nullable<long> Area13GUIDInt2 { get; set; }
        public string AreaLevel13 { get; set; }
        public string AreaTeamProjectCollection { get; set; }
        public string AreaTeamProject { get; set; }
    }
}
