//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDimTestPlanOverlay
    {
        public int TestPlanSK { get; set; }
        public string TestPlanBK { get; set; }
        public Nullable<int> TestPlanId { get; set; }
        public string Name { get; set; }
        public Nullable<byte> StateId { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public Nullable<int> PlanOwnerSK { get; set; }
        public string PlanOwner__Name { get; set; }
        public string PlanOwner__SID { get; set; }
        public Nullable<int> AreaSk { get; set; }
        public string AreaPath { get; set; }
        public Nullable<long> Area0GUIDInt1 { get; set; }
        public Nullable<long> Area0GUIDInt2 { get; set; }
        public string AreaLevel0 { get; set; }
        public Nullable<long> Area1GUIDInt1 { get; set; }
        public Nullable<long> Area1GUIDInt2 { get; set; }
        public string AreaLevel1 { get; set; }
        public Nullable<long> Area2GUIDInt1 { get; set; }
        public Nullable<long> Area2GUIDInt2 { get; set; }
        public string AreaLevel2 { get; set; }
        public Nullable<long> Area3GUIDInt1 { get; set; }
        public Nullable<long> Area3GUIDInt2 { get; set; }
        public string AreaLevel3 { get; set; }
        public Nullable<long> Area4GUIDInt1 { get; set; }
        public Nullable<long> Area4GUIDInt2 { get; set; }
        public string AreaLevel4 { get; set; }
        public Nullable<long> Area5GUIDInt1 { get; set; }
        public Nullable<long> Area5GUIDInt2 { get; set; }
        public string AreaLevel5 { get; set; }
        public Nullable<long> Area6GUIDInt1 { get; set; }
        public Nullable<long> Area6GUIDInt2 { get; set; }
        public string AreaLevel6 { get; set; }
        public Nullable<long> Area7GUIDInt1 { get; set; }
        public Nullable<long> Area7GUIDInt2 { get; set; }
        public string AreaLevel7 { get; set; }
        public Nullable<long> Area8GUIDInt1 { get; set; }
        public Nullable<long> Area8GUIDInt2 { get; set; }
        public string AreaLevel8 { get; set; }
        public Nullable<long> Area9GUIDInt1 { get; set; }
        public Nullable<long> Area9GUIDInt2 { get; set; }
        public string AreaLevel9 { get; set; }
        public Nullable<long> Area10GUIDInt1 { get; set; }
        public Nullable<long> Area10GUIDInt2 { get; set; }
        public string AreaLevel10 { get; set; }
        public Nullable<long> Area11GUIDInt1 { get; set; }
        public Nullable<long> Area11GUIDInt2 { get; set; }
        public string AreaLevel11 { get; set; }
        public Nullable<long> Area12GUIDInt1 { get; set; }
        public Nullable<long> Area12GUIDInt2 { get; set; }
        public string AreaLevel12 { get; set; }
        public Nullable<long> Area13GUIDInt1 { get; set; }
        public Nullable<long> Area13GUIDInt2 { get; set; }
        public string AreaLevel13 { get; set; }
        public string AreaTeamProjectCollection { get; set; }
        public string AreaTeamProject { get; set; }
        public Nullable<int> IterationSk { get; set; }
        public string IterationPath { get; set; }
        public Nullable<long> Iteration0GUIDInt1 { get; set; }
        public Nullable<long> Iteration0GUIDInt2 { get; set; }
        public string IterationLevel0 { get; set; }
        public Nullable<long> Iteration1GUIDInt1 { get; set; }
        public Nullable<long> Iteration1GUIDInt2 { get; set; }
        public string IterationLevel1 { get; set; }
        public Nullable<long> Iteration2GUIDInt1 { get; set; }
        public Nullable<long> Iteration2GUIDInt2 { get; set; }
        public string IterationLevel2 { get; set; }
        public Nullable<long> Iteration3GUIDInt1 { get; set; }
        public Nullable<long> Iteration3GUIDInt2 { get; set; }
        public string IterationLevel3 { get; set; }
        public Nullable<long> Iteration4GUIDInt1 { get; set; }
        public Nullable<long> Iteration4GUIDInt2 { get; set; }
        public string IterationLevel4 { get; set; }
        public Nullable<long> Iteration5GUIDInt1 { get; set; }
        public Nullable<long> Iteration5GUIDInt2 { get; set; }
        public string IterationLevel5 { get; set; }
        public Nullable<long> Iteration6GUIDInt1 { get; set; }
        public Nullable<long> Iteration6GUIDInt2 { get; set; }
        public string IterationLevel6 { get; set; }
        public Nullable<long> Iteration7GUIDInt1 { get; set; }
        public Nullable<long> Iteration7GUIDInt2 { get; set; }
        public string IterationLevel7 { get; set; }
        public Nullable<long> Iteration8GUIDInt1 { get; set; }
        public Nullable<long> Iteration8GUIDInt2 { get; set; }
        public string IterationLevel8 { get; set; }
        public Nullable<long> Iteration9GUIDInt1 { get; set; }
        public Nullable<long> Iteration9GUIDInt2 { get; set; }
        public string IterationLevel9 { get; set; }
        public Nullable<long> Iteration10GUIDInt1 { get; set; }
        public Nullable<long> Iteration10GUIDInt2 { get; set; }
        public string IterationLevel10 { get; set; }
        public Nullable<long> Iteration11GUIDInt1 { get; set; }
        public Nullable<long> Iteration11GUIDInt2 { get; set; }
        public string IterationLevel11 { get; set; }
        public Nullable<long> Iteration12GUIDInt1 { get; set; }
        public Nullable<long> Iteration12GUIDInt2 { get; set; }
        public string IterationLevel12 { get; set; }
        public Nullable<long> Iteration13GUIDInt1 { get; set; }
        public Nullable<long> Iteration13GUIDInt2 { get; set; }
        public string IterationLevel13 { get; set; }
        public string IterationTeamProjectCollection { get; set; }
        public string IterationTeamProject { get; set; }
    }
}
