//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDimChangesetOverlay
    {
        public int ChangesetSK { get; set; }
        public string ChangesetBK { get; set; }
        public Nullable<int> ChangesetID { get; set; }
        public string ChangesetTitle { get; set; }
        public string PolicyOverrideComment { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public Nullable<int> CheckedInBySK { get; set; }
        public string CheckedInBy__Name { get; set; }
        public string CheckedInBy__SID { get; set; }
    }
}
