//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDimWorkItemOverlay
    {
        public int WorkItemSK { get; set; }
        public string WorkItem { get; set; }
        public string PreviousState { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public Nullable<System.DateTime> System_ChangedDate { get; set; }
        public Nullable<int> System_Id { get; set; }
        public string System_Title { get; set; }
        public string System_State { get; set; }
        public Nullable<int> System_Rev { get; set; }
        public Nullable<int> System_ChangedBy__PersonSK { get; set; }
        public string System_Reason { get; set; }
        public Nullable<int> System_AssignedTo__PersonSK { get; set; }
        public string System_WorkItemType { get; set; }
        public Nullable<System.DateTime> System_CreatedDate { get; set; }
        public Nullable<int> System_CreatedBy__PersonSK { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Common_ActivatedDate { get; set; }
        public Nullable<int> Microsoft_VSTS_Common_ActivatedBy__PersonSK { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Common_ResolvedDate { get; set; }
        public Nullable<int> Microsoft_VSTS_Common_ResolvedBy__PersonSK { get; set; }
        public string Microsoft_VSTS_Common_ResolvedReason { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Common_ClosedDate { get; set; }
        public Nullable<int> Microsoft_VSTS_Common_ClosedBy__PersonSK { get; set; }
        public Nullable<int> Microsoft_VSTS_Common_Priority { get; set; }
        public string Microsoft_VSTS_Common_Severity { get; set; }
        public Nullable<double> Microsoft_VSTS_Common_StackRank { get; set; }
        public string Microsoft_VSTS_Build_IntegrationBuild { get; set; }
        public string Microsoft_VSTS_Build_FoundIn { get; set; }
        public string Microsoft_VSTS_CodeReview_ClosedStatus { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_CodeReview_AcceptedDate { get; set; }
        public Nullable<int> Microsoft_VSTS_CodeReview_AcceptedBy__PersonSK { get; set; }
        public string Microsoft_VSTS_Common_Risk { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_TargetDate { get; set; }
        public string Microsoft_VSTS_Common_Rating { get; set; }
        public string Microsoft_VSTS_Common_Issue { get; set; }
        public string Microsoft_VSTS_Common_Activity { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_StartDate { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_FinishDate { get; set; }
        public string Microsoft_VSTS_TCM_AutomationStatus { get; set; }
        public Nullable<System.DateTime> Microsoft_VSTS_Scheduling_DueDate { get; set; }
        public string Microsoft_VSTS_CMMI_Blocked { get; set; }
        public string Sifizsoft_Identificador { get; set; }
        public string Sifizsoft_TipoTrabajo { get; set; }
        public string Sifizsoft_TiempoUtilizado { get; set; }
        public string Sifizsoft_TiempoFaltante { get; set; }
        public Nullable<System.DateTime> Sifizsoft_FechaEjecucion { get; set; }
        public string Tipo_TipoTrabajo { get; set; }
        public string Sifizsoft_Orden { get; set; }
        public string Sifizsoft_TiempoInterno { get; set; }
        public string Sifizsoft_TipoRecurso { get; set; }
        public string Sifizsoft_TipoTarea { get; set; }
        public string Sifizsoft_Criterio { get; set; }
        public string Sifizsoft_Exigibilidad { get; set; }
        public string Sifizsoft_Origen { get; set; }
        public string Sifizsoft_TiempoTarea { get; set; }
        public string Sifizsoft_TiempoRestante { get; set; }
        public Nullable<int> AreaSk { get; set; }
        public string AreaPath { get; set; }
        public Nullable<long> Area0GUIDInt1 { get; set; }
        public Nullable<long> Area0GUIDInt2 { get; set; }
        public string AreaLevel0 { get; set; }
        public Nullable<long> Area1GUIDInt1 { get; set; }
        public Nullable<long> Area1GUIDInt2 { get; set; }
        public string AreaLevel1 { get; set; }
        public Nullable<long> Area2GUIDInt1 { get; set; }
        public Nullable<long> Area2GUIDInt2 { get; set; }
        public string AreaLevel2 { get; set; }
        public Nullable<long> Area3GUIDInt1 { get; set; }
        public Nullable<long> Area3GUIDInt2 { get; set; }
        public string AreaLevel3 { get; set; }
        public Nullable<long> Area4GUIDInt1 { get; set; }
        public Nullable<long> Area4GUIDInt2 { get; set; }
        public string AreaLevel4 { get; set; }
        public Nullable<long> Area5GUIDInt1 { get; set; }
        public Nullable<long> Area5GUIDInt2 { get; set; }
        public string AreaLevel5 { get; set; }
        public Nullable<long> Area6GUIDInt1 { get; set; }
        public Nullable<long> Area6GUIDInt2 { get; set; }
        public string AreaLevel6 { get; set; }
        public Nullable<long> Area7GUIDInt1 { get; set; }
        public Nullable<long> Area7GUIDInt2 { get; set; }
        public string AreaLevel7 { get; set; }
        public Nullable<long> Area8GUIDInt1 { get; set; }
        public Nullable<long> Area8GUIDInt2 { get; set; }
        public string AreaLevel8 { get; set; }
        public Nullable<long> Area9GUIDInt1 { get; set; }
        public Nullable<long> Area9GUIDInt2 { get; set; }
        public string AreaLevel9 { get; set; }
        public Nullable<long> Area10GUIDInt1 { get; set; }
        public Nullable<long> Area10GUIDInt2 { get; set; }
        public string AreaLevel10 { get; set; }
        public Nullable<long> Area11GUIDInt1 { get; set; }
        public Nullable<long> Area11GUIDInt2 { get; set; }
        public string AreaLevel11 { get; set; }
        public Nullable<long> Area12GUIDInt1 { get; set; }
        public Nullable<long> Area12GUIDInt2 { get; set; }
        public string AreaLevel12 { get; set; }
        public Nullable<long> Area13GUIDInt1 { get; set; }
        public Nullable<long> Area13GUIDInt2 { get; set; }
        public string AreaLevel13 { get; set; }
        public string AreaTeamProjectCollection { get; set; }
        public string AreaTeamProject { get; set; }
        public Nullable<int> IterationSk { get; set; }
        public string IterationPath { get; set; }
        public Nullable<long> Iteration0GUIDInt1 { get; set; }
        public Nullable<long> Iteration0GUIDInt2 { get; set; }
        public string IterationLevel0 { get; set; }
        public Nullable<long> Iteration1GUIDInt1 { get; set; }
        public Nullable<long> Iteration1GUIDInt2 { get; set; }
        public string IterationLevel1 { get; set; }
        public Nullable<long> Iteration2GUIDInt1 { get; set; }
        public Nullable<long> Iteration2GUIDInt2 { get; set; }
        public string IterationLevel2 { get; set; }
        public Nullable<long> Iteration3GUIDInt1 { get; set; }
        public Nullable<long> Iteration3GUIDInt2 { get; set; }
        public string IterationLevel3 { get; set; }
        public Nullable<long> Iteration4GUIDInt1 { get; set; }
        public Nullable<long> Iteration4GUIDInt2 { get; set; }
        public string IterationLevel4 { get; set; }
        public Nullable<long> Iteration5GUIDInt1 { get; set; }
        public Nullable<long> Iteration5GUIDInt2 { get; set; }
        public string IterationLevel5 { get; set; }
        public Nullable<long> Iteration6GUIDInt1 { get; set; }
        public Nullable<long> Iteration6GUIDInt2 { get; set; }
        public string IterationLevel6 { get; set; }
        public Nullable<long> Iteration7GUIDInt1 { get; set; }
        public Nullable<long> Iteration7GUIDInt2 { get; set; }
        public string IterationLevel7 { get; set; }
        public Nullable<long> Iteration8GUIDInt1 { get; set; }
        public Nullable<long> Iteration8GUIDInt2 { get; set; }
        public string IterationLevel8 { get; set; }
        public Nullable<long> Iteration9GUIDInt1 { get; set; }
        public Nullable<long> Iteration9GUIDInt2 { get; set; }
        public string IterationLevel9 { get; set; }
        public Nullable<long> Iteration10GUIDInt1 { get; set; }
        public Nullable<long> Iteration10GUIDInt2 { get; set; }
        public string IterationLevel10 { get; set; }
        public Nullable<long> Iteration11GUIDInt1 { get; set; }
        public Nullable<long> Iteration11GUIDInt2 { get; set; }
        public string IterationLevel11 { get; set; }
        public Nullable<long> Iteration12GUIDInt1 { get; set; }
        public Nullable<long> Iteration12GUIDInt2 { get; set; }
        public string IterationLevel12 { get; set; }
        public Nullable<long> Iteration13GUIDInt1 { get; set; }
        public Nullable<long> Iteration13GUIDInt2 { get; set; }
        public string IterationLevel13 { get; set; }
        public string IterationTeamProjectCollection { get; set; }
        public string IterationTeamProject { get; set; }
        public Nullable<int> TeamProjectCollectionSK { get; set; }
        public Nullable<int> TeamProjectSK { get; set; }
        public Nullable<System.DateTime> System_RevisedDate { get; set; }
    }
}
