//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFactLinkedCurrentWorkItemTestCase
    {
        public int SourceWorkItemSK { get; set; }
        public int TargetWorkitemSK { get; set; }
        public Nullable<int> WorkItemLinkTypeSK { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    }
}
