//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifizPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFactWorkItemToTree
    {
        public int WorkItemSK { get; set; }
        public Nullable<int> WorkItemTreeSk { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    }
}
